### ISSUE TITLE
Editing icons not shown for CEs inside content areas on 7.6

### ISSUE THREAD

**Issue by jsegars** [FluidTYPO3/flux#1019]
As of TYPO3 7.6, it appears that regular editors do not see editing icons for content elements that are placed inside a content area.  When clicking the content element icon, the context menu still has the expected options but edit, hide, and delete are all missing from the CE header.  For admin users, everything works fine.  This also affects the ability to drag and drop content for regular editors.

It looks like this is due to a change of behavior in the core between TYPO3 7.5 and 7.6. The following revision tightened up permissions checking throughout the core's PageLayoutView.  These checks rely on PageLayoutView->pageinfo, which the core initializes in the getTable_tt_content() method.

https://forge.typo3.org/projects/typo3cms-core/repository/revisions/fd1bdd076cd62a81da12fa1f3b32c63c2a5e9ada

I believe Flux needs to initialize this pageinfo in PreviewView->getInitializedPageLayoutView(). Unfortunately the core current declares this as a protected property so options are limited.

Before I open a core issue on this, I'd like to figure out what the preferred approach for flux would be.  The simplest solution is of course flipping pageinfo to a public property or providing a setter and initializing that inside Flux.  Is that good enough or is there another preferred solution that is still simple enough to get into 7.6.1?

Thanks!

**Comment by NamelessCoder** [comment]
Hi Jeff,

Thanks for the awesome bug description - tells us everything we need to know!

There is a connection to https://github.com/FluidTYPO3/flux/pull/1017 and https://github.com/FluidTYPO3/flux/pull/1014 here and we absolutely need some way to access this particular property.

I've considered Reflection at first, then also considered @monosize's (rather light weight) XCLASS style subclassing, but I think we may end up needing something else. Upon closer investigation it seems that the `pageInfo` property, although not accessible from the outside, is consistently filled if we call the standard "list content elements" method. This needs a bit of further investigation but my assumption is that we only get a slight overhead since this method internally then caches all the records we later pull manually from the PageLayoutView.

However, if the overhead is too severe we have to come back to the two solutions above; we reflect and make accessible the property and worries over - or we subclass and use our own implementation and worries over (except of course if those very specific and few parts we actually override are ever implemented in the core in an incompatible way - chances very remote).

The ideal situation however would be one that would let us actually use the output of the standard content listing method on PageLayoutView - the main problem with that is the HTML produced by that method contains links and dropzone target values that we 1) need to change in order to make it behave as expected in a nested context, and 2) cannot manipulate by manipulating properties of PageLayoutView at least as far as I am personally aware.

Perhaps this inspires you to put some puzzle pieces together that I'm currently missing. Any solution that lets us reach the ideal situation would be... **tremendously** appreciated. It would pretty much let us discard our PreviewView's entire column handling!

**Comment by NamelessCoder** [comment]
Hi Jeff,

The mentioned pull request is now merged - would you mind checking on development branches if this solves your issue as well? It should work as a first solution but it would still be great to have one based entirely on public API of PageLayoutView ;)

**Comment by jsegars** [comment]
Hey Claus,
Thanks for the update (and the earlier pointer to the pull request).  I switched our composer setup over to this pull request earlier this morning for testing and it seemed to solve the issue well.  I'll double check on the development branch but I'll be shocked if there's any issue.

I'd love to look at a more robust solution like you describe eventually, but I'll have to get a large project launched first and lightweight XCLASS serves us well for the time being.

Thanks!
Jeff

**Comment by NamelessCoder** [comment]
That's great news indeed.

> I'd love to look at a more robust solution like you describe eventually, but I'll have to get a large project launched first and lightweight XCLASS serves us well for the time being.

Yep, that's why I merged it with the XCLASS solution - better to get that out and perfect it later, than not properly support LTS.

Looks like we're close to new releases for FluidTYPO3 as well so stay tuned :)

**Comment by jsegars** [comment]
Just to circle back, all is good on the development branch. Thanks!

**Comment by xf-** [comment]
We can close this one @jsegars ?

**Comment by jsegars** [comment]
Yep, fine by me.  If I get moving on larger refactoring I'll open up a new issue / pull request.
