### ISSUE TITLE
Select element only allows integer values on nested elements

### ISSUE THREAD

**Issue by arnekolja** [FluidTYPO3/flux#1020]
When nesting the form into multiple sections/objects, I cannot use string values any more, as they're not saved.

e.g:

This does not work:

    <flux:field.select name="layer_type" label="Typ" items="{0: {0: 'Text', 1: 'text'}, 1: {0: 'Bild', 1: 'image'}, 2: {0: 'Video', 1: 'video'}, 3: {0: 'Hotspot', 1: 'hotspot'}}" default="image" requestUpdate="true" />

But this does:

    <flux:field.select name="layer_type" label="Typ" items="{0: {0: 'Text', 1: '0'}, 1: {0: 'Bild', 1: '1'}, 2: {0: 'Video', 1: '2'}, 3: {0: 'Hotspot', 1: '3'}}" default="1" />

Also tested it with

    items="text,image,video,hotspot"

This seems to only occur on nested elements. When using the string-value notation on the main element, it works.

The nesting I tested was, simplified:

    <f:section name="Configuration">
        <flux:form id="myelement" label="My Element">
            <flux:form.sheet name="sheet_elements" label="Elemente">
                <flux:form.section name="elements" label="Elemente" inherit="0">
                    <flux:form.object name="element" label="Einzelelement" inherit="0">
                        <flux:form.section name="layers" label="Ebenen">
                            <flux:form.object name="layer" label="Ebene">
                                <flux:field.select name="layer_type" label="Typ" items="{0: {0: 'Text', 1: 'text'}, 1: {0: 'Bild', 1: 'image'}, 2: {0: 'Video', 1: 'video'}, 3: {0: 'Hotspot', 1: 'hotspot'}}" default="image" />
                            </flux:form.object>
                        </flux:form.section>
                    </flux:form.object>
                </flux:form.section>
            </flux:form.sheet>
        </flux:form>
    </f:section>

"Does not work" means: Attribute "default" does not work (always first element preselected) and after save the value is empty again, again preselecting the first value.

**Comment by arnekolja** [comment]
I took a look into the database and noticed, that the values are actually saved. But when they're saved, this means that it does not get correctly parsed, right? In my case this breaks functionality, as I am depending on requestUpdate / displayCond, which don't work.

tl'dr:
Field values and displayCond'ed fields don't show up correctly, despite the fact, that the values are saved correctly.

**Comment by NamelessCoder** [comment]
Hi Arne,

There's a significant number of issues reported and some fixed in the TYPO3 core regarding both section objects and displayCond in FlexForms - I'm fairly sure your issues are also explained by those. As far as I am aware it is completely about the display in the backend (which also matches what you experience, values get saved but the form doesn't reflect this) - displayCond obviously is completely about display ;)

You can find a list of all open issues regarding these things at https://forge.typo3.org/projects/typo3cms-core/issues?set_filter=1&f%5B%5D=status_id&op%5Bstatus_id%5D=o&f%5B%5D=category_id&op%5Bcategory_id%5D=%3D&v%5Bcategory_id%5D%5B%5D=983&f%5B%5D=&c%5B%5D=tracker&c%5B%5D=status&c%5B%5D=priority&c%5B%5D=subject&c%5B%5D=assigned_to&c%5B%5D=category&c%5B%5D=fixed_version&group_by=

And as mentioned, some are fixed which means an update of your TYPO3 core will also improve the situation.

**Comment by arnekolja** [comment]
Thanks I'll look into it
