### ISSUE TITLE
Custom label translation of fields not working

### ISSUE THREAD

**Issue by MarvinRudolph** [FluidTYPO3/flux#1027]
Hey,

normally you define the ID of the flux field like `<flux:form id="myForm">` and in the `locallang.xlf / xx.locallang.xlf` the `<trans-unit>` would be `<trans-unit id="flux.myForm"> [...]`.
But you can define custom "translation paths/IDs" with the `label=""` attribute. 

When I use `<flux:form id="pageStandard" label="{f:translate(key: 'page.standard')}">` it loads the translation of the `locallang.xlf` but not of the `xx.locallang.xlf` files.  So the translation is always in English.

Without defining the custom one it works fine with the `flux.` prefix.

**Comment by NamelessCoder** [comment]
Hi Marvin,

When you use the "label" property the value gets cached and no longer changes according to backend language. Using `LLL:` in front of the name will resolve it on each execution. Alternatively, do not use `label` and instead use the expected label names based on component names (see https://fluidtypo3.org/documentation/templating-manual/templating/creating-templates/language-usage.html). So this is expected behavior / unexpected usage and you can easily fix it ;)

**Comment by MarvinRudolph** [comment]
Awesome, thanks! That really helped me alot. :+1: :)
