### ISSUE TITLE
[ERROR] flux was requested to be downloaded in different versions (7.2.3 and 7.3.0)

### ISSUE THREAD

**Issue by ste101** [FluidTYPO3/flux#1040]
At installations where I'm using flux 7.1.2 I'm getting this error when I click at 'Extension Manager':
```flux was requested to be downloaded in different versions (7.2.3 and 7.3.0)```
Is this a TYPO3 core problem or a flux problem?

**Comment by NamelessCoder** [comment]
It's a case of one or more extensions which depend on flux not being upgraded. If TYPO3 is completely unable to resolve your particular dependencies, uninstall them, upgrade Flux and then reinstall the extensions you uninstalled. When you get to the one that wants an earlier version of Flux, upgrade it, ignore the constraint, or edit the dependencies if the extension is one you've created yourself.

**Comment by ste101** [comment]
Thanks. I made a bugreport:
https://forge.typo3.org/issues/72110

**Comment by NamelessCoder** [comment]
I'm not sure it will be seen as a bug - could be expected behavior in this particular case of dependencies - but it will of course be good to get an opinion from the core guys ;)

PS: forgot to mention (and not sure it can still be done?) but when you are in the "get extensions" view of extension manager you should be able to pick a specific version of Flux to download (that's sort of the same as removing the 7.3 version manually from tables). It might help to do that, pick version 7.2, then upgrade fluidpages/fluidcontent and finally upgrade Flux to 7.3. That puzzle should theoretically work with the constraints.

**Comment by neufeind** [comment]
Afaik never really was resolved, was it? There is also a core-issue without a solution: https://forge.typo3.org/issues/72110
Upgrading to latest 6.2.x didn't resolve the issue.
