### ISSUE TITLE
[ Typo3 7.6.1 + Flux 7.3.0 ] FAL Inline element: Change upload path

### ISSUE THREAD

**Issue by julianxhokaxhiu** [FluidTYPO3/flux#1044]
Hi there,

I was curious to know if it's possible to introduce a configurable flag for FAL elements, or if possible, find a way to make it generic by default, to upload all the files inside `uploads/tx_extensioname` ( see here http://stackoverflow.com/questions/23364209/change-upload-path-for-typo3-extension ).

Actually it's uploading inside the extension folder, directory `user_upload` and it's not nice, expecially because editors can choose files inside any folder of the extension: `Classes`, `Resources`, etc.

Thank you in advance

**Comment by julianxhokaxhiu** [comment]
Forget it, was not a fault of TCA configuration but the mountpoint of FAL was somehow set into the extension. Maybe the `site` extension installation script is doing that but it's not cool. Should be left on `fileadmin/`.

**Comment by NamelessCoder** [comment]
Hi Julian,

I'm not sure about the possible reasons but it may be that TYPO3 switched to the FAL mount point created by EXT:site, as you mention. I've checked plenty times and in all tests those mount points are created as not-default and sorted below the default one, but perhaps something caused the mount point to become default. Maybe we can prevent it but I suspect not. To narrow it down maybe you can answer these:

* Did you manually sort the EXT:site created mount points at any time?
* Was the `fileadmin` storage offline for whichever reason at some point?
* Are you using the default FAL "local filesystem" driver or another one?

If you can answer yes to one or all of those I would write this off as expected (although perhaps too "magic") behavior, possibly caused by the FAL driver being used. If the mount points were sorted manually the priority could have hanged - and if the storage was ever offline, TYPO3 may have set another as default, e.g. TYPO3 detects: mount point uses storage X but storage X reports as offline in the FAL driver, uses next working mount point as default.

I'm also not sure if any (new) features in TYPO3 7.6 might allow us to "demote" the mount points EXT:site creates so they won't be used as defaults.

PS: the ability to browse the EXT:site mount point when selecting files is intentional - it allows TYPO3 to select things like CSS assets and images from the provider extension. If you don't really need the mount point for that, or for editing the assets via the TYPO3 backend, I would recommend to just not create the mount point. It's mostly there for people who are used to editing templates and assets via `fileadmin` :)

**Comment by julianxhokaxhiu** [comment]
Hi @NamelessCoder,

Let me first answer your questions:

1) Nope. I used the site extension stock default as it came from your git repo
2) Totally not. I just installed Typo3 7.6 first and then I installed the site extension later. Everything else came up from PHP installation script routine.
3) Yes, default driver, never had needs to change it.

As said before, I just installed a fresh typo3 7.6, then I installed the site extension and after it was done I refresh the backend and I start to work on the integration of my website. But I never bothered with the mount point until now that the editors used a picture file from a FAL element, which was living inside Resources folder.

So I had to change in the backend the mount point back to fileadmin and now everything is working fine.

Honestly I don't know why the mount point was set inside my extension ( created from site ), but I just found it this way.

Maybe if we try it now with Typo3 7.6.1 and the current site extension status is not doing that anymore. I don't know, I should try it but I don't have the time right now :)

Thanks for the feedback btw!

**Comment by NamelessCoder** [comment]
I'll give the clean install a try when I get some time, perhaps something was changed in 7.6.1 regarding how/when the default storage gets selected. If we can pin down whatever condition caused the file browser to default to the other mount point, we can probably prevent it. Obviously that mount point shouldn't be used as default, ever :)

**Comment by julianxhokaxhiu** [comment]
Thank you :D Let's hope that is already fixed

**Comment by NamelessCoder** [comment]
PS: feel free to open an issue in the "site" repository, if we can prevent this I bet it has to be in the statement that creates the mount point.

**Comment by julianxhokaxhiu** [comment]
Done :)
