### ISSUE TITLE
flux:field.select throws "not all tags were closed"

### ISSUE THREAD

**Issue by kersten** [FluidTYPO3/flux#1050]
Hello,

I have an flux:field.select with 162 entries. If I try to add more than 27 entries, the system throws the error: 

```
1238169398: Not all tags were closed! (More information)

TYPO3\CMS\Fluid\Core\Parser\Exception thrown in file
/var/www/typo3_src-7.6.2/typo3/sysext/fluid/Classes/Core/Parser/TemplateParser.php in line 518.

44 TYPO3\CMS\Fluid\Core\Parser\TemplateParser::buildObjectTree(array, 2)

/var/www/typo3_src-7.6.2/typo3/sysext/fluid/Classes/Core/Parser/TemplateParser.php:
00355:         $splitTemplate = $this->splitTemplateAtDynamicTags($templateString);
00356: 
00357:         $parsingState = $this->buildObjectTree($splitTemplate, self::CONTEXT_OUTSIDE_VIEWHELPER_ARGUMENTS);
00358: 
00359:         $variableContainer = $parsingState->getVariableContainer();

43 TYPO3\CMS\Fluid\Core\Parser\TemplateParser::parse("<div xmlns="http://www.w3.org/1999/xhtml" lang="en…                         }"/>↵	</f:section>↵</div>")

/var/www/typo3_src-7.6.2/typo3/sysext/fluid/Classes/View/AbstractTemplateView.php:
00272:             $parsedPartial = $this->templateCompiler->get($partialIdentifier);
00273:         } else {
00274:             $parsedPartial = $this->templateParser->parse($this->getPartialSource($partialName));
00275:             if ($parsedPartial->isCompilable()) {
00276:                 $this->templateCompiler->store($partialIdentifier, $parsedPartial);
```

This happened after updating to PHP7 and latest commit from this repository.

May this be a problem with my PHP? With 5.6 I don't get this error.

**Comment by NamelessCoder** [comment]
Hi Kersten,

The error is apparently unrelated to FluidTYPO3 classes. It is without question caused by an actual syntax error or some aspect of the template source code causing the regular expression to not split it correctly - that's all part of Fluid's engine and the error occurs well before any of our classes become involved.

I cannot tell you the exact cause but a general tip would be: if you have to define a big array, such as items for a selector, consider defining it in TypoScript (which makes it integrator-friendly and page-context-sensitive) or creating a custom Form component which adds those items from within a ViewHelper class so you don't have to define them in your template. In summary: keep your template files lean and you'll have less issues with syntax errors.

It *is* possible something changed in PHP7 about some internals of PCRE but I'm unaware of any such change and have not experienced any similar problems. Nor do the unit tests fail (and they are intentionally fitted with some pretty badly formatted templates).

PS: future versions of TYPO3 and Fluid will allow dumping a piece of template code along with errors, making it easier to locate such problems but until then, the only way to locate this problem is by reading or by trial and error in changing the template code.
