### ISSUE TITLE
FAL not working again

### ISSUE THREAD

**Issue by kersten** [FluidTYPO3/flux#1063]
Hello,

after using the pull #1058 I can't open the FAL dialog anymore. I only see this before clicking:

![image](https://cloud.githubusercontent.com/assets/487289/12224457/2d37219e-b7f1-11e5-82c7-476d5f308877.png)

And in the popup I get the following declaration warning:

```php
#1: PHP Warning: Declaration of TYPO3\CMS\Recordlist\Tree\View\ElementBrowserPageTreeView::wrapTitle($title, $row, $ext_pArrPages) should be compatible with TYPO3\CMS\Backend\Tree\View\ElementBrowserPageTreeView::wrapTitle($title, $v, $ext_pArrPages = false) in /var/www/vendor/typo3/cms/typo3/sysext/recordlist/Classes/Tree/View/ElementBrowserPageTreeView.php line 24 (More information)
```

System: Typo3 7.6.2 Composer mode
PHP: 7.0.2
flux: dev-development

**Comment by NamelessCoder** [comment]
Hi Kersten,

The error is caused by a TYPO3 class because TYPO3 is not yet completely PHP7 safe and is specifically due to an unclean class inheritance structure in the two classes mentioned in the error message. There are others like it and I know work is being done in that area right now.

But this is entirely unrelated to FluidTYPO3.
