### ISSUE TITLE
[BUG] Flux container in workspaces does not handle translations correctly in BE

### ISSUE THREAD

**Issue by mshdev** [FluidTYPO3/flux#1078]
TYPO3: 6.2.17
flux: 6.2.3
fluidcontent: 4.3.3

1.initial situation in workspaces

![image](https://cloud.githubusercontent.com/assets/17313487/13141586/743c3ed4-d638-11e5-9d4f-17fe259fc05a.png)

2.after pressing "copy default content elements [1]" button

![image](https://cloud.githubusercontent.com/assets/17313487/13141620/92b2dd96-d638-11e5-8d17-7def23f8a76a.png)
**still every row shows the button "copy default content elements [1]"**

3.after pressing "copy default content elements [1]" button again (first row => "Linke Spalte")

![image](https://cloud.githubusercontent.com/assets/17313487/13141712/0b905d1a-d639-11e5-9370-02118503f0b3.png)
**the translated content element "Test1" is now also in the first row "Linke Spalte" of the default language**

**Comment by mjankiewicz** [comment]
Hi, I had similar problem with flux and TYPO3 6.2. You may try me fixes https://github.com/mjankiewicz/flux/commit/4e25b4ce05c50edfdf5794cfd0174a3fbaa1ee8a - in my case it helped

**Comment by NamelessCoder** [comment]
Please switch to the `legacy` branch from Git to make sure you have all the most recent bug fixes. I should note here that we still cannot claim full workspaces support (and changes to this code tends to be complicated because it has to coexist with so many other use cases). Will close this issue since it concerns a now deprecated Flux version - you're welcome to open pull requests to merge code into the `legacy` branch but please be aware that it receives *very* low priority.

@mjankiewicz If you can, please open a pull request for that change (for `development` as well as `legacy` branch if it applies to both) so the team gets a chance to evaluate it!

**Comment by NamelessCoder** [comment]
Most detailed info we have so far about workspaces-related drag and drop: https://github.com/FluidTYPO3/flux/issues/961
