### ISSUE TITLE
Not able to print flux fields in preview if there is flux:grid

### ISSUE THREAD

**Issue by vinayn** [FluidTYPO3/flux#1080]
In the below code {object.addtext} is not printented in Preview section. Is there any way to print  content along with content area.

```
<f:for each="{items}" as="itemSectionObjects">
			<f:for each="{itemSectionObjects}" as="object" key="objectType" iteration="iteration">
				<v:switch value="{objectType}">
						<v:case case="addtext" break="TRUE">
							{object.addtext}
						</v:case>
						<v:case case="userinput" break="TRUE">
							{object.userinput}
						</v:case>
						<v:case case="uicontrol" break="TRUE">
							{object.uicontrol}
						</v:case>
						<v:case case="codeblock" break="TRUE">
							{object.codeblock}
						</v:case>
						<v:case case="codeph" break="TRUE">
							{object.codeph}
						</v:case>
						<v:case case="systemoutput" break="TRUE">
							{object.systemoutput}
						</v:case>
						<v:case case="image" break="TRUE">
													
						</v:case>
						<v:case case="ditacontent" break="TRUE">

							{object.ditacontenttitle}
								<flux:grid>
								<flux:grid.row>
									<flux:grid.column name="ditacontent{iteration.index}" />

								</flux:grid.row>

								</flux:grid>

						</v:case>
						<v:case case="default">

							{object.text}

						</v:case>
				</v:switch>
			</f:for>
		</f:for>

```

**Comment by NamelessCoder** [comment]
The `flux:grid` ViewHelper is only for using in the `Configuration` section (or whichever section name you used if you override the default name). It cannot be used in the `Preview` section and will most likely cause a lot of problems if you do - although it won't throw any exceptions about it since technically you could override things in such a way that you intentionally store the configuration in the Preview section.

Content gets output automatically, no need to call anything. What you cannot do is determine *where* in the Preview your content elements should be displayed, but what you can do is modify the Preview-related parameters in `flux:form` to make the content list come before or after your custom content - or not be displayed at all.

At the time of writing this the options are undocumented - see https://github.com/FluidTYPO3/documentation/issues/40
