### ISSUE TITLE
field.inline.fal not usable if relation is removed

### ISSUE THREAD

**Issue by farconada** [FluidTYPO3/flux#1085]
Hello

If you have a relation like this

`<flux:field.inline.fal name="settings.images" label="Image" required="1" maxItems="1" minItems="1"/>`

adds a relation and then removed the item the relation is not usable 
![captura de pantalla 2016-02-23 a las 17 18 36](https://cloud.githubusercontent.com/assets/469221/13258057/d85565fe-da51-11e5-968a-ff8ab13cabbe.png)

Tested with TYPO3 7.6.3 and flux  cc384df

**Comment by NamelessCoder** [comment]
I *think* this one is a TYPO3 core issue (looks like FormEngine + JS operating on the HTML, possibly because `minitems > 0` in TCA array) that would affect any FlexForm implementation, not just Flux. It may even have been fixed since, but I'm not sure.

My main reason for thinking this is that `maxitems` and `minitems` are very young supports for IRRE fields and I would not be surprised if a small bug hides away in there. Especially since there are two different rendering methods for IRRE fields; one outside and one inside FlexForms.

If you open an issue there or find one that already describes the problem please link to it here (for other users to find in the future) :)
