### ISSUE TITLE
Passing arguments to flux-enabled controller does not work

### ISSUE THREAD

**Issue by demacrocom** [FluidTYPO3/flux#1117]
As mentioned in a [comment by Claus Due](https://worksonmymachine.org/blog/page-and-content-controllers-in-fluidtypo3#comment-1223582686), it should be possible to pass arguments to flux-enabled controllers, just like they were simple extbase controllers.

Unfortunately this is not possible, [as described here](http://stackoverflow.com/questions/36505001/how-to-pass-argument-to-controller-action-with-fluidtypo3). As you can see in my post on stack overflow, I set up a new, clean install of TYPO3 with only the least required things and tested it there. As it doesn't even work in that clean environment, I suspect this is a bug.

**Comment by jkkauhan** [comment]
I had the same problem when using `f:link.action` but found out that I need to add argument `extensionName` without underscores (that is, `my_extension` becomes `myextension`) to get the arguments to ContentController. Without `extensionName` defined the URL parameters have too many underscores if the extension key has any. 

I think this is a bug because it worked in old version of `fluidcontent` but not in `flux`.

**Comment by jkkauhan** [comment]
This is how I create the links in my view (CategoryNews.html):

```
<f:link.action extensionName="myextension" arguments="{category:'{cat.uid}'}">
    ...
</f:link.action>
```

And this is how I read the arguments in `my_extension/Classes/Controller/ContentController.php`:

```
public function categoryNewsAction()
{
    $args = $this->request->getArguments();
    $category = intval($args['category']);
    ....
```

I have also disabled caching on the page to make sure everything works.

Note that I don't even need to specify the action, because it's the same content element in the same page I'm linking to. However now I need to specify the extensionName to make it work.

**Comment by schoeppe** [comment]
I can confirm the problem still exists in flux 9.2.0.

For me it was not possible to use the fluid paginator widget which relies on the page parameter being passed in the plugin namespace. It took me a while to debug the problem but it seems like this is caused by the parameter handling (mapping URL parameters to request arguments) in the [AbstractFluxController](https://github.com/FluidTYPO3/flux/blob/development/Classes/Controller/AbstractFluxController.php).

**The mapping there fails for extensions containing underscores, e.g. my_extension!**

The mapping of the URL parameters to the request arguments is done using custom code for determining the plugin namespace. This custom code replaces underscores in the extension name, which is the root cause for the failed mapping. I think the plugin namespace should be determined "the extbase way", namely using an injected extbase ExtensionService.

When debugging the problem I found two other possible issues within this class:
- the parameter handling won't work at all if you don't use a custom controller class
- the parameter mapping ignores files

As a workaround I am using my own extended version of the fluidpages [PageController](https://github.com/FluidTYPO3/fluidpages/blob/development/Classes/Controller/PageController.php) - see [attached file](https://github.com/FluidTYPO3/flux/files/3247022/PageController.php.txt).

I would prepare a pullrequest if someone could confirm this problem and the proposed way of solving it.

**Comment by NamelessCoder** [comment]
Solved, see example of usage on https://github.com/FluidTYPO3/test_provider_extension/commit/634aeef41e602347d9e05b524d4f967c81f464d7. No need to manually pass `extensionName` even if your extension key contains underscores.
