### ISSUE TITLE
[BUG][TYPO3-6.2] Localize child element with more than 2 languages (TYPO3 6.2, flux 7.2.3)

### ISSUE THREAD

**Issue by clickstorm** [FluidTYPO3/flux#1149]
Hi,

I had some trouble by localizing a child element in a third language (TYPO3 6.2, flux 7.2.3). Then the flux_parent was the ID of the parent element in the second language.

I found the problem in Classes/Service/ContentService.php line 305. I added the sys_language_uid in the SQL-WHERE clause:

Before my debugging:
`$translatedParents = (array) $this->workspacesAwareRecordService->get('tt_content', 'uid', " t3_origuid = '" . $oldRecord['tx_flux_parent'] . "'" . BackendUtility::deleteClause('tt_content'));`

After my debugging:
`$translatedParents = (array) $this->workspacesAwareRecordService->get('tt_content', 'uid', " sys_language_uid = " . $newLanguageUid . " AND t3_origuid = '" . $oldRecord['tx_flux_parent'] . "'" . BackendUtility::deleteClause('tt_content'));`

Could you please fix this in the flux extension? Thanks!

**Comment by NamelessCoder** [comment]
Hi @clickstorm - thanks for the suggested patch! Since we no longer officially support any 6.2 compatible versions there is only the following way to get this patch included:

* Clone the Flux repository and create a new branch based on `legacy`
* Prepare the fix in this branch publish this branch on your remote
* Prepare a pull request targeting the `legacy` branch
* Make sure the commit and code lives up to coding guidelines

We ask this since we do not allot time to assist with patches for versions we no longer support - but we are happy to keep merging pull requests into the `legacy` branch as long as users keep making them ;)

In general we recommend you use the `legacy` branch from git for your 6.2 sites even though it is not officially supported. This branch still receives bug fixes (when users make pull requests) but we no longer publish it to TER.
