### ISSUE TITLE
Using Flux annotations to generate TCA is not working

### ISSUE THREAD

**Issue by TarasZakus** [FluidTYPO3/flux#1150]
Since the _TCEforms_-wrapper was removed [here](https://github.com/FluidTYPO3/flux/commit/0aaa843287c175cf506c7693974a633c2e71bd58#diff-3e9f4668cd7342861e6c2692710c5603L197), the `array_pop($field->build())` in `\FluidTYPO3\Flux\Backend::processFormForTable($table, Form $form)` is no longer needed.

**Comment by kai-plusb** [comment]
Had the same Problem. Overriding the class and unwrapping the `array_pop($field->build())` into simply `$field->build()` helped me, too.

**Comment by RozbehSharahi** [comment]
This also causes the m:n relations in the frontend not to work, since the TCA definition is missing. Kind regards.

**Comment by NamelessCoder** [comment]
Feature is now deprecated and you can expect removal when Flux 9.0 gets released - which should be quite soon. If you want to follow the status of that work, feel free to follow/subscribe to  https://github.com/FluidTYPO3/flux/pull/1378.

I am really sorry to disappoint you by removing this (since you're obviously using it). As an alternative I suggest you construct `Form` instances and add components using its API until you have a Flux form that represents your domain object - then register that as form for the table your model object belongs to. Some day, perhaps, we'll revive this feature based on Doctrine annotations - but it's unlikely this will get done until the core switches officially to Doctrine annotations in Extbase.
