### ISSUE TITLE
flux:field.select renderMode, multipe...

### ISSUE THREAD

**Issue by Eumolp** [FluidTYPO3/flux#1152]
Using T3 7.6, flux 7.4
<flux:field.select name="settings.header.className"
	renderMode="checkbox" 
	size="2" multiple="true" items="{settings.header.classNames}" label="LLL:fields.classNames"
/>
wether renderMode nor multipe seems to have any effect. You cant unselect items, too.
Can you confirm this?

Christian.

**Comment by Eumolp** [comment]
digging depper into it, not easy for a Developement-Noop...

debugging 
ViewHelpers/Field/AbstractMultiValueFieldViewHelper.php
AbstractMultiValueFieldViewHelper::getPreparedComponent()
width "debug($arguments);" just before return-$components-statement, shows that 
$component->setRenderMode($arguments['renderMode']);
ist never set, but  $arguments['renderType'].

Checking the reference (https://fluidtypo3.org/viewhelpers/flux/development/Field/SelectViewHelper.html)  does not list renderType (master/develope), but renderMode.

using renderType does still not allow multipe items to be saved, al least i can now delete the selected item.  #-(

...going on digging deeper, I would welcome any help from a person knowing the flux-code...

**Comment by Eumolp** [comment]
<flux:field.select name="settings.header.className"
		label="LLL:fields.classNames"  
		renderType="selectMultipleSideBySide"
		minItems="0"
		maxItems="10"
		size="5"
		items="{settings.header.classNames}" 
	/>
"multiple" is deprecated (?)
use at least maxItems>1

Did I miss some documentation? Of course I did, but can you tell me where this is documented?
Usind fluidTypo3 alwas is a pain but this seems to me that using fluidTypo3 is a kind of russian roulett! Nobody knows what happens next...

But I still love the consequent way to do everything without unsing this EXT here and that EXT there, but this comfort is bought at a high price, too.

**Comment by NamelessCoder** [comment]
Hi Christian,

We understand your frustration, but you're expressing it in the wrong direction. There's a more detailed article explaining that very situation here: https://fluidtypo3.org/blog/news/bugs-core-or-flux.html

I'll summarise it for you here:

Flux is an API for TCEforms and this component of TYPO3 has undergone some fundamental changes (FormEgine). Those changes have brought some regressions (some are fixed, some are not yet, some are too complex to be fixed currently) and some breaking changes. Most important of those breaking changes are the new Exceptions TYPO3 will throw if you use what TYPO3 considers to be invalid structures for a data source for FormEngine.

It all boils down to this:

You would face the same issues if you did not use a single community extension. If all you did was manually configure every aspect that Flux is merely an API for (e.g. defined your form's data structure directly in TCA or made a flexform XML file) you would have the exact same Exceptions thrown at you.

This is essentially outside the scope that we in FluidTYPO3 control and can fix. With *extremely* few exceptions we do *not* replace core classes in order to fix problems or hack structures that TYPO3 now considers invalid. It is the responsibility of users to know how TYPO3's TCA / TCEforms need to be configured and migrated (but we do help point to that knowledge and in some cases explain it).

So why are Flux users in particular affected?

That's simply because Flux is what Flux is - an API letting you do some usually very complicated or very large setups using an API that condenses that (to ViewHelpers which then generate that structure). The things you can do with great ease in Flux (take your field as an example) takes tremendous amounts of setup and knowledge of some of the stranger parts of TCA or even user functions (to fetch things like items for your select component). Compare that to your single line of Flux ViewHelper in your template.

Where will you find documentation?

For any Flux component that generates a field or other TCEforms based component you find the documentation in the TYPO3 TCA documentation, and be careful you read the version of docs applying to your TYPO3 version. Components that are not documented there includes the grid and option components plus pipes/outlets; grid and option is easy enough to understand and documented in ViewHelpers, pipes/outlets are as of writing this still undocumented but completely opt-in and designed for use cases not covered by the standard TYPO3 features themselves.

> Nobody knows what happens next...

Some people do know, but I will concede that as one person, keeping up with such changes as they are being made in the TYPO3 master and that way knowing what to expect, is a task that's so big I myself can't keep up (and still be able to serve my clients). If you do study the release notes for each TYPO3 version you will find such breaking changes documented - but even those digest format change logs are VERY big and take a lot of time to read and remember.

What I'd like you to take away from this is that we absolutely care. We do our best to keep up with changes to the TYPO3 code that we act as API for (we sometimes fail and arrive late with solutions) and we do our best to at least be able to tell users *why* changes like those happen and whether or not we agree with them. When we don't agree we share this disagreement and any alternatives we can suggest, with the TYPO3 core teams.

That's the best we can do - and we do it ;)
