### ISSUE TITLE
flux:content.render changes context 

### ISSUE THREAD

**Issue by kraemer-igroup** [FluidTYPO3/flux#1168]
Hello, I use TYPO3 7.6.10 with fluidcontent 4.4.1 an flux 7.4.0.

My template has a grid and a fal field (flux:field.inline.fal). After I render a column with `flux:content.render` for the frontend I can not get the fal field with `v:content.resources.fal(field: 'myField')}`.

It is online working before I render the column. So I guess `flux:content.render` is changing the context to the rendered content element. It is also working if I set `render="0"` as option in `flux:content.render`.

In my opinion the output of a column should not change the context. I tried to avoid it but `v:content.render` seems to have the same issue.

**Comment by NamelessCoder** [comment]
Sorry, but this is not within our control. What happens is that the *content* you render in the column, not the column itself, is setting the new context in ConfigurationManager etc.

Since they don't reset the context after rendering, you experience this problem. It would be the same, mind you, if you used any other method of rendering your content. As such this is not a flux or FluidTYPO3 issue - it is simply the way TYPO3 works when you render content.

A very similar issue is described on https://forge.typo3.org/issues/76489.

**Comment by kraemer-igroup** [comment]
Thank your for the explanation! In case someone has the same issue, as workaround I saved my FAL resources in a variable before rendering child content:

`<f:for each="{v:content.resources.fal(field: 'images')}" as="image">`

`<v:variable.set name="tmpImages" value="{tmpImages}<div class=\"column\">{f:image(src:image.url)}</div>" />`

`</f:for>`

...

`<flux:content.render area="myContent" />`

...

`<f:format.html>{tmpImages}</f:format.html>`
