### ISSUE TITLE
flux:form.container broken with flux 7.4.0

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/flux#1201]
When trying to use `flux:form.container` in a FCE with flux 7.4.0 and TYPO3 7.6.10 I get an exception in the backend:

> #1: PHP Warning: Invalid argument supplied for foreach() in /var/www/site/htdocs/typo3_src/typo3/sysext/backend/Classes/Form/Container/FlexFormElementContainer.php line 48

The example content element code I used is available at http://p.cweiske.de/234

**Comment by NamelessCoder** [comment]
I'm afraid this one hasn't worked since the introduction of FormEngine - and it does not appear that FormEngine even has a replacement for this particular type of half-section, half-sectionobject.

I would open an issue in the TYPO3 bug tracker to clarify if this is supposed to be supported. If it is not, we should probably request that a specific exception be thrown in this case, since right now FormEngine allows the structure but cannot render it.

I've also tried a few direct approaches using FormEngine components directly, but none of the methods give the correct result - so even a fallback may not be possible for this.

**Comment by philippjbauer** [comment]
@cweiske Did you open an issue in the TYPO3 bug tracker? I was searching but couldn't find anything. Is there any progress on this?

**Comment by cweiske** [comment]
No, I did not open an issue elsewhere.

**Comment by cweiske** [comment]
I've opened a bug report for TYPO3 CMS: https://forge.typo3.org/issues/79433

**Comment by NamelessCoder** [comment]
Closing; to be continued in the TYPO3 core issue. Thanks for taking care of that @cweiske :)
