### ISSUE TITLE
error: Tried to get a variable "sections" which is not stored in the context

### ISSUE THREAD

**Issue by blueamerican** [FluidTYPO3/flux#1211]
Hello Claus,

i have this error in the frontend after clearing the cache.

I have read this:
https://forge.typo3.org/issues/72231
https://github.com/FluidTYPO3/flux/issues/938

But i do not understand this error and don't know how to debug it.

TYPO3 7.6.12 and
fluidcontent 	4.4.1 	
fluidpages 	3.6.1 	
flux 	7.4.0 

Can you help?

Best regards Markus

**Comment by NamelessCoder** [comment]
This is almost surely caused by one or more templates being detected in folders for fluidcontent or fluidpages templates not having at least one `<f:section>`. The files can be in any supported format.

To avoid this, don't place template files without sections in any of the detected folders. The comment on #938 is the hint to understand this:

> Sorry, it was my fault: Reason for my Problem was a empty template file in flux content folder: It needs the configuration section to work.

A less likely cause for this can be `f:render` attempting to render a section from a partial template which does not contain sections.

**Comment by thomaszbz** [comment]
@NamelessCoder I experienced this issue whereas I don't have a fluid template installed. That use case can happen e.g. for a multi domain scenario where some extensions need to be installed but are not used by all domains.

For details: I reported my scenario here: https://forge.typo3.org/issues/79383 (because initially I took powermail into account).
