### ISSUE TITLE
<flux:grid> now always required, even if not used

### ISSUE THREAD

**Issue by monosize** [FluidTYPO3/flux#1212]
Something changed in the behaviour!
 
now an <flux:grid> element is always required in the Configuration section, even if it isn't used.
Using fluid_content and fluid_contentcore.

got error: #1243325768: No value found for key "FluidTYPO3\Flux\ViewHelpers\FormViewHelper->grids"

The error appears in this call: https://github.com/FluidTYPO3/flux/blob/ebf71a5bdbfbadbd00692dc4e3642b36eab8c13e/Classes/View/ExposedTemplateView.php#L92

I have tested it with a workaround and catch the error. Then it works again.
Make it sense to catch the error at this point?

tested in TYPO3 7.6.13-dev

**Comment by NamelessCoder** [comment]
Catching the exception there and returning NULL would be okay - side note though, on TYPO3v8+ this is not an issue since the container no longer throws Exceptions if a variable is missing (just returns null which works perfectly with the current Flux code).

A temporary try/catch around this until we drop 7.6 LTS support would be appreciated! :)
