### ISSUE TITLE
flux:field.inline.fal on condition f:if or f:switch

### ISSUE THREAD

**Issue by rupasix** [FluidTYPO3/flux#1214]
Test case:
```<flux:form id="logostest">
			<flux:field.select 
				name="settings.type"  
				requestUpdate="1" 
				items="{0:{0:'with Images',1:'2'},1:{0:'without',1:'1'},}" 
				label="Slider type" />
			<f:if condition="{settings.type} == 2">
				<flux:field.inline.fal name="settings.imagestest" multiple="1" maxItems="123" label="Items" collapseAll="1"/>
			</f:if>
		</flux:form>
```

When flux:field.inline.fal is inside some sort of condition (f:if and f:switch/case tested) and then that content is copypasted , strange things will happen - images in original content will be doubled and copy of it will be empty. Database shows that **uid_foreign** for new references are not connected with copy of tt_content but with original one. Consequences may be brutal when someone copy one page with CE containing images x time - in our case few content elements had about 40k references. 

![20161114_865](https://cloud.githubusercontent.com/assets/9860558/20265331/c48e67d8-aa70-11e6-9dbd-0127853914ff.png)
![20161114_864](https://cloud.githubusercontent.com/assets/9860558/20265330/c48b9d14-aa70-11e6-91af-9e5ebd15d30a.png)

Flux: 7.4.0
VHS: 3.1.0
TYPO3: 7.6.12

**Comment by NamelessCoder** [comment]
This one has a lot of connections to things going on in both Flux and the TYPO3 core. It boils down to this:

The relations' schema is defined in a FlexForm DataSource (DS) and the combination of Flux and TYPO3 means the DS is delivered by a hook, in order to make it dynamic (for Flux, reading it from template file, PHP or TS).

This hook is undergoing some changes:

* The old hook will be deprecated in TYPO3 8.5
* A different method is added which restores *some* but not all of the semi-buggy handling that the FormEngine rewrite had removed, or the re-introduction of which had regressions.

This means that part of the issue you face is expected to "solve itself" if using TYPO3 8.5 (which is not yet released).

Then there is a second part to this issue:

Both of the hooks that execute 1) after the FormEngine rewrite, up to and after 2) the mentioned reworking of DS delivery *no longer receive the complete database record, set of default fields or an original record when creating new records or copies of records*.

Because of this we will be forced to do a few things in the coming time:

* Flux FlexForm fields will be fitted with a `displayCond` that makes the field invisible until the record has a `uid` value (this prevents problems creating new records).
* Flux should/must switch the pragma used for generating the dynamic DS so that the DS becomes stored in a way that the TYPO3 core understands without triggering hooks, and the DS becomes rewritten when saving a record (unless the DS is declared static in which case it won't be rebuilt).

The latter of those two tasks will solve the issue you face, by making the DS retrieval independent of the record having a UID. Unfortunately I can't give you an ETA on when that may be done.

**Comment by rupasix** [comment]
Thanks for quick response and explanation. This is important for us and we can't upgrade to 8.5 so my teammate write "quick'n'dirty" fix for that:
at bottom of **processCmdmap_postProcess** function https://github.com/FluidTYPO3/flux/blob/master/Classes/Backend/TceMain.php#L113
`  
if ($reference->copyMappingArray['sys_file_reference'] && $reference->copyMappingArray['tt_content']) {
   foreach ($reference->copyMappingArray['tt_content'] as $ttUidOld => $ttUidNew) {
    $GLOBALS['TYPO3_DB']->exec_UPDATEquery(
     'sys_file_reference',
     'uid IN ('.implode(',', $reference->copyMappingArray['sys_file_reference']).') AND uid_foreign='.$ttUidOld,
     array('uid_foreign' => $ttUidNew)
    );
   }
  }
`

Maybe someone will consider it useful.

**Comment by DenisMir** [comment]
We found a similar behavior described right here #1380. This is a pretty severe bug as you mentioned in your entry post.

**Comment by NamelessCoder** [comment]
Solved as well as we can solve it for now. The DS can now be resolved correctly also for new records - so you should not experience this problem again if you upgrade Flux.
