### ISSUE TITLE
Flux\Configuration\BackendConfigurationManager:getPageIdFromRecordIdentifiedInEditUrlArgument returns wrong id

### ISSUE THREAD

**Issue by wazum** [FluidTYPO3/flux#1319]
This method called `getPageIdFromRecordUid` even if the edit command ID (like edit[tt_content][44733]=new) was positive and therefore already the page ID, so in fact returning a random value found by querying a < table > record with this (page) ID as uid.

The following patch fixes this issue:

```
diff --git a/Classes/Configuration/BackendConfigurationManager.php b/Classes/Configuration/BackendConfigurationManager.php
index e2245924..dcc5f9cb 100644
--- a/Classes/Configuration/BackendConfigurationManager.php
+++ b/Classes/Configuration/BackendConfigurationManager.php
@@ -121,7 +121,9 @@ class BackendConfigurationManager extends CoreBackendConfigurationManager implem
         } elseif (0 <> $id && 'pages' !== $table) {
             // if any identified record is being edited, load it and return the PID value.
             // if the (new) record is relative to another, $id is negative UID of relative record, hence abs().
-            return $this->getPageIdFromRecordUid($table, abs($id));
+            if (0 > $id && 'new' === $command) {
+                return $this->getPageIdFromRecordUid($table, abs($id));
+            }
         }
         return $id;
     }
@@ -147,9 +149,6 @@ class BackendConfigurationManager extends CoreBackendConfigurationManager implem
         $argumentPair = reset($editArgument);
         $id = (integer) key($argumentPair);
         $command = reset($argumentPair);
-        // if TYPO3 wants to insert a new tt_content element after the element
-        // with uid=abs($id), translate ID.
-        $id = (integer) (0 > $id && 'tt_content' === $table) ? $id = -$id : $id;
         return [$table, $id, $command];
     }

```

**Comment by wazum** [comment]
This was not the whole story, it requires another condition, if the command is not 'new' (then it's the record ID again)

```
            if (0 > $id && 'new' === $command) {
                return $this->getPageIdFromRecordUid($table, abs($id));
            }
            elseif (0 < $id && 'new' !== $command) {
                return $this->getPageIdFromRecordUid($table, abs($id));
            }
```

**Comment by OttoAndras** [comment]
I think this is still an issue. Currently only the first add content element button works, every other one with the negative IDs are wrong:

We use a TYPO3 8.7.5 and flux 8.2.1.

We had experienced a very strange problem. One of our plugin (nothing to du with flux) showed no items by a select. It should have been filled through an itemProcFunc call. 

We could reproduce the error but only if there was an other element already inserted to the page:
![bildschirmfoto 2017-09-11 um 17 49 45](https://user-images.githubusercontent.com/4362334/30283910-c031fc18-9719-11e7-88d8-5e0bae8b755d.png)

So by the second and third links the link URL contains the ID of the previous element as a negative uid_pid. So far is everything fine, but in the function:
BackendConfigurationManager.php 
getPageIdFromRecordIdentifiedInEditUrlArgument() (line 117)

this part of the code makes trouble:

  if (in_array($table, ['pages', 'tt_content']) && 'new' === $command) {
            // if TYPO3 wants to insert a new page, URL argument is already the PID value.
            return $id;
        } 

The problem, that this is a new tt_content element, and because the pid stays from, the BE delivers a totally wrong TypoScript Setting. It depends on the tt_content ID and could be a different page (different website in a multidomain environment). We used a TS Setting for our userFunc and that caused the problem.

Unfortunately at this moment the negative ID is already an absolute one, so it can not be differenced in two different cases.

1. case: The first button, it has the correct pid.
2. case: Every other button, they gut the previous id as a negative uid_pid.

**Comment by NamelessCoder** [comment]
Flux's ConfigurationManager is now removed - see https://github.com/FluidTYPO3/flux/commit/4e147ef5b1ec6e14730cea75067a09461a110102 for a bit more detail. If the configuration that gets resolved now is incorrect, please report the issue to the TYPO3 core bug tracker.

If you want to confirm this solution on your current use case that would be nice. You can do that by removing the lines in https://github.com/FluidTYPO3/flux/commit/4e147ef5b1ec6e14730cea75067a09461a110102#diff-650ba9004d55b4534a27f8ad3463dc21L61 and flushing system caches.

**Comment by dogawaf** [comment]
Hello @OttoAndras 
Did you find a workaround for this problem?

@NamelessCoder , the removing of the Flux's ConfigurationManager does not fix the issue for me.
The TS config is still not the right one if I try to insert a content after an existing one.

**Comment by dogawaf** [comment]
If anyone interested, 
[here is a working patch for me](https://github.com/FluidTYPO3/flux/files/1835110/flux_configuration_manager.txt) of the BackendConfigurationManager (TYPO3 8.7.11 + Flux 8.2.1)

**Comment by wazum** [comment]
@dogawaf the class BackendConfigurationManager is not available anymore. Please use the development branch, Flux 8.2.1 is nearly a year old!

**Comment by dogawaf** [comment]
@wazum , I no. But development branch is not working for me with fluidcontent, and 8.2.1 is.
