### ISSUE TITLE
tx_flux_column empty when fluidcontent added into fluidcontent grid

### ISSUE THREAD

**Issue by rupasix** [FluidTYPO3/flux#1330]
Typo3 7.6.15
flux 8.0.2
fluidcontent: 5.0.0

Whats happened: i created new content with flud grid column, tested it with standard tt_content (text + media) and everything was fine (tx_flux_column == 'main'). Next time i created new fluidcontent on that grid and ... it's gone. After short research in db we've found empty column "tx_flux_column". Please help ;(

**Comment by rupasix** [comment]
Ok, sorry, i've found issue #1312. Maybe reopen that one to avoid another issue repetition until fluidcontent is not patched?

**Comment by grimmcreative** [comment]
Same here. tx_flux_column gets not written in Database if an Standard TYPO3 (fluid_styled_content) Element is used.

**Comment by grimmcreative** [comment]
Putting this line to ext_tables.php of your Provider Extension solved the Problem:

`require_once(TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('flux', 'Configuration/TCA/Overrides/tt_content.php'));`

but i dont think its the nice way to do it. And i think other issues comes with this because now i get many errors like

`should be compatible with TYPO3\CMS\Extbase\Mvc\Controller\ActionController::initializeView`
with my other extensions.

**Comment by NamelessCoder** [comment]
The field is now added to every type in `tt_content` *except* if you manually overwrite the entire TCA for your type in an extension that gets loaded after Flux is loaded. I doubt you'll be affected by that edge case.
