### ISSUE TITLE
Using tt_content.header with disabled header in TCA didn't work

### ISSUE THREAD

**Issue by TheNaderio** [FluidTYPO3/flux#1340]
I'm using `<flux:filed.input name="tt_content.header"/>` to set the header for my FCE's. I don't want to use the header in frontend - only as title in listview and similar.
When I add text into it, I can use it in my templates. In Backend there is the same text in the standard-field and in my custom field.

Now I set in my `myext/Configuration/TCA/Overrides/tt_content.php` th following code to hide the standard header field:
`$GLOBALS['TCA']['tt_content']['columns']['header']['displayCond'] = FIELD:CType:!=:fluidcontent_content;`

The standard-header field is gone now, but i cannot update the tt_content.header with my flux-field  anymore. The "title" of the content element is still the "old" header.

**Comment by NamelessCoder** [comment]
For various reasons - security being the most important - we cannot allow writing field values in fields which are not accessible to the editor. Using `displayCond` to render a field invisible means the field is removed and does not get processed. The best advise I can give you is to avoid `displayCond` and instead manipulate the `showitem` TCA of the content type (this leaves the field as a valid field but does not render the form field). Note though that this becomes a problem when you use `fluidcontent` because of the shared `CType` value. For a solution that gives you a custom `CType` for each template I suggest you take a look at the newly added Flux feature to register templates as new content types; https://github.com/FluidTYPO3/flux/commit/fc219687346bbe8cb51704c1eca1a70a1b83129f.

**Comment by NamelessCoder** [comment]
See also: https://github.com/FluidTYPO3/flux/issues/1250
