### ISSUE TITLE
Flux 8.0.2 "FluidTYPO3\Flux\ViewHelpers\Widget\GridViewHelper" maybe not loaded or no autoloader? Class FluidTYPO3\Flux\ViewHelpers\Widget\GridViewHelper

### ISSUE THREAD

**Issue by wabajwa** [FluidTYPO3/flux#1346]
Hi,
As, @NamelessCoder  you already told about it in #1336  but i saw and found that `<flux:widget.grid>`has already removed in version 8.0.2 which i am using now. It has been also discussed in #1269, So, might be it is the issue of upgrade or some thing else. I am new to typo3 so i have no clue where could be the issue. 
If you or someone else have idea how to solve it, would be appreciated . 
Thanks

**Comment by NamelessCoder** [comment]
@wabajwa Search your typo3conf/ext folder for any occurrences of `flux:widget.grid` and edit all the (.html) template files you get in that result - and simply remove the entire `<flux:widget.grid />` tag from the template.

**Comment by wabajwa** [comment]
Hi, 
Yeah, \htdocs\typo3conf\ext\flux\Tests\Fixtures\Templates
Here,  I have checked in all (.html) file but there are no presence of `flux:widget.grid`nor `<flux:widget.grid/>`, because i have seen your previous commit in 1269 issue, where you have deprecated these things, so in this current version of `Flux 8.0.2` these are not present. So it could be any other issue?

**Comment by NamelessCoder** [comment]
If you really are experiencing that exact error, there's no other possible cause than a template file containing the deprecated-and-removed `<flux:widget.grid />` tag. If your setup doesn't use our recommendation to put templates in a provider extension then you may need to look for this somewhere else, e.g. fileadmin folder.

To be clear: the error you get is caused by Fluid being unable to load a class that it resolves based on a ViewHelper tag that you used. Fluid only tries to load classes if you explicitly use the ViewHelper in a template, so this error wouldn't happen if you removed all occurrences. I guess you must have missed at least one?

Also, don't forget to clear system caches (via the install tool) to make sure compiled Fluid templates get recompiled.

**Comment by wabajwa** [comment]
yeah it has been solved, thanks
