### ISSUE TITLE
Wizard suggest not displaying in flux backend 

### ISSUE THREAD

**Issue by ebincm** [FluidTYPO3/flux#1386]
We are not able to use wizard.suggest in  flux form FCE under 8.6.1V and our fluid version is 2.3.1 

**Code** 
<f:section name="Configuration">
   <flux:form id="FCE" options="{group: 'FCE',icon: 'iconpath" label="label">
      <flux:grid>
         <flux:grid.row>
            <flux:grid.column  name="example_content" label="Example Content"></flux:grid.column>
         </flux:grid.row>
      </flux:grid>
      <flux:field.relation label="Jobs Region 3" table="table" condition="AND table.deleted = 0 AND table.hidden = 0" size="6" multiple="true" minItems="0" maxItems="500" name="field_table">
         <flux:wizard.suggest />
      </flux:field.relation>
   </flux:form>
</f:section>

**Comment by NamelessCoder** [comment]
Only works with `group` type (`flux:field.multiRelation`) for some reason. Which components this works with is unfortunately not up to us, so the only two recommendations I can give are:

* Switch to the `multiRelation` type
* And/or ask or this as a feature request in the TYPO3 core bug tracker, https://forge.typo3.org/projects/typo3cms-core/issues

NB: your example would indicate that perhaps you've forgotten to include `hidden` and `deleted` as special hide/delete fields in your TCA for the table you point to. Normally you'd never need to filter the query this way since those enable fields (and in particular the delete field!) should always apply. If there's some reason you *must* specify these, you probably also *must* specify them in the suggest wizard.
