### ISSUE TITLE
New record icon path is deprecated and not working

### ISSUE THREAD

**Issue by RozbehSharahi** [FluidTYPO3/flux#1387]
Hello,

in TYPO3 8.5.1 the icon path is wrong when you create a new record, that was registered with `Cor::registerAutoFormForModelObjectClassName`. 

It can be fixed by changing the line 191 in Table `/typo3conf/ext/flux/Classes/Backend/TableConfigurationPostProcessor.php` from

```
$tableConfiguration['iconfile'] = ExtensionManagementUtility::extRelPath($extensionKey) .
            $form->getOption(Form::OPTION_ICON);
```
to the following
```
$tableConfiguration['iconfile'] = ExtensionManagementUtility::extPath($extensionKey) .
            $form->getOption(Form::OPTION_ICON);
```

At least this is working for me.

Kind regards
Rozbeh Chiryai Sharahi

**Comment by NamelessCoder** [comment]
I'm sorry to say that the TCA-from-model feature in Flux has been removed since it had fallen into disrepair and was never fully completed with all support for TCA such as dividing fields into sheets and sorting them.

It would still be possible to create a package that reads model class annotations (Extbase has a utility for that purpose) and creates a Flux `Form` instance based on it. I'd be happy to assist with information about the Flux API if someone creates such an extension - but it is no longer within the domain of Flux to interact with model annotations.

Hope you understand. Extbase and Flux still provide all the pieces you'd need to make such a feature work (and work better than Flux's variant did) but we no longer force any decisions on you in this regard. In fact, you could wrap all of that in a Provider class that works with your table!
