### ISSUE TITLE
flux:field.tree.category issue with transform

### ISSUE THREAD

**Issue by pixelplant** [FluidTYPO3/flux#1394]
I added a flux category field to my content and the backend selection works properly.
```
<flux:field.tree.category name="categories" transform="TYPO3\CMS\Extbase\Persistence\ObjectStorage<TYPO3\CMS\Extbase\Domain\Model\Category>" maxLevels="10" label="Categories"/>
```

The problem is that I cannot retrieve the list of selected categories in my transform. 

For example, let's say I select 2 categories. I can see they get saved properly in the sys_category_record_mm table, but once I try to display them either in the front or in the backend section, it does not load those 2 records BUT only 1 record (category), and it loads the category with uid "2", because I selected 2 categories. If I select 3 categories, it only returns 1 category with the uid 3, and so on, instead of returning a list of 3 categories (those that I actually selected).

Is this a bug or am I missing something in the configuration in order to properly return the list of selected categories as Extbase Category objects?

Thank you

**Comment by NamelessCoder** [comment]
This isn't exactly fresh in memory, but as far as I remember, Flux is naive about the transformation and assumes the value is either a single or a CSV list of UIDs that get stored in the record itself. We probably need a new FEATURE here which analyses the DS to detect MM tables and does a sub-query to find the real UIDs.

**Comment by pixelplant** [comment]
Yes, you are right. It only gets the id stored in the column, which is actually the count of how many records you're referencing.
In the end I had to write my own method in the controller that fetches the categories based on the current record's uid and did all the referencing by hand

**Comment by fkalka** [comment]
Hi pixelplant,
do you mind to share your code? I am facing the same issue.
Thanks.

**Comment by fkalka** [comment]
Did it myself, here is the code, maybe someone can use it:

$result = $GLOBALS['TYPO3_DB']->exec_SELECTquery('uid_local', 'sys_category_record_mm', 'tablenames = "tt_content" and fieldname = "extensionkey_settings.category" and uid_foreign = '.$this->getRecord()['uid']);

This example works in the ContentController from fluidcontent. Replace 'extensionkey_settings.categories' with your value.

**Comment by NamelessCoder** [comment]
There are three things you can do about this, either of which will solve the problem:

1. Use the (very) newly added hooks, https://github.com/FluidTYPO3/flux/commit/1f76e8a60b99d7b93ee8752345573530d4b81d8e - specifically `VALUE_BEFORE_TRANSFORM` which lets you apply arbitrary transformation using any method you want.
2. Create a custom class with a function which receives a single (string) value and is capable of transforming that to your desired type, then reference that class name in the `transform` attribute, for example `transform="\My\Special\Transformer->convertThisToThat"`. Note that the `->` is the part that triggers the custom class usage (but the method can be static if you like; it still gets defined the same way in the attribute).
3. Choose to convert the value in the controller instead.

So I'll close this issue since we have plenty ways to achieve the goal now.

FYI, I may decide to remove even more of the transformation logic, substituting it with this custom conversion class approach. This way you can already pass a reference to a Repository method which takes the right input argument and returns your desired entities so it has basically made the current Repository integration obsolete.
