### ISSUE TITLE
Reset of children in \FluidTYPO3\Flux\Form::modify

### ISSUE THREAD

**Issue by sruegg** [FluidTYPO3/flux#1412]
Hello,

Just wondering if there is any reason to reset $this->children here : https://github.com/FluidTYPO3/flux/blob/master/Classes/Form.php#L436

This is probably not a bug, but this method is called by https://github.com/FluidTYPO3/flux/blob/master/Classes/View/ExposedTemplateView.php#L81

This is very usefull to override or add some configuration (project specific) via TS for base elements we use in our projects and with this reset, there is a **complete** override of the sheet 😢 .

Thanks for your lights 😉 

P.S.: this reset comitted here : https://github.com/FluidTYPO3/flux/commit/b1694190ed2ed53066bf66cf58518a073fe580f3

**Comment by NamelessCoder** [comment]
If I recall, the reset is there to allow you to remove unwanted children but the tradeoff is you then have to declare all the children you *do* want. We could solve this by not resetting and instead, allowing TS to contain an empty string or zero (so we can check with `empty($value) === true`) to indicate you want a child removed. Then in the modify() function we do the usual thing of calling modify() when a child exists - and we can call removeChild() when detecting an empty value in the overrides.

If you want to take a stab at creating a pull request with this that would be appreciated. It probably isn't too hard to do since it sounds like you've already investigated and have a nice use case ready ;)

**Comment by NamelessCoder** [comment]
This should no longer happen - Flux will now recursively call `->modify` on children of a container (such as Sheet).
