### ISSUE TITLE
[BUG][TYPO3-7.6.18] Moving a record to another page causes colpos to be set to the pid of the new page

### ISSUE THREAD

**Issue by sypets** [FluidTYPO3/flux#1415]
**System environment**
TYPO3 7.6.18
flux version : 8.2.1 (current version)

I used a fresh TYPO3 7.6.18 installation with introduction package to reproduce this to ensure a clean environment without sideeffects from other extensions. 

Under TYPO3 8, the same actions produce a different error, for which I will open another issue.

**Reproduce**

You can reproduce this with minimal TYPO3 system without having created any flux containers.

1. Select a record from a  page (e.g. pid=35) and cut it to clipboard. 
2. Select a different page (e.g. pid=2), in list mode choose "paste in clipboard content". This will cause colpos of the moved record to be set to the pid, e.g.:

```
+-----+-----+--------+
| uid | pid | colpos |
+-----+-----+--------+
|  12 |   2 |      2 |
+-----+-----+--------+
![flux-clipboard2](https://cloud.githubusercontent.com/assets/13206455/26354855/bd528daa-3fc6-11e7-8d4c-c15fcfa7f619.png)

```
This results in the new content element being usually not visible in page mode (but in list mode).

**Comment by sypets** [comment]
I debugged this. 

1. As sugggested in the documentation (https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Typo3CoreEngine/Database/Index.html), on move the hook function processCmdmap_postProcess is called with the pid to be passed as forth argument ($relativeTo)
2. This will result in moveRecord to be passed with the pid as second argument ($relativeTo)
https://github.com/FluidTYPO3/flux/blob/4985f4f61473907c0a3cea404c1e06769d3eba49/Classes/Backend/TceMain.php#L314
3. This causes colpos to be set to $relativeTo (which can't really be correct, 'cause it's the pid. 
https://github.com/FluidTYPO3/flux/blob/4985f4f61473907c0a3cea404c1e06769d3eba49/Classes/Service/ContentService.php#L200

**Comment by NamelessCoder** [comment]
Thank you very much for a detailed report. I definitely had misunderstood the nature of the `$relativeTo` argument - and have refactored accordingly. While I'm not completely sure that the linked commit fixes your issue (you will probably have to cherry pick it), it should at least make the usage of the argument consistent with the arguments TYPO3 will pass.

I've also reduced the number of cases which can set the `colPos` value of records to a minimum- basically, it only happens if you move a record relative to another and when Flux is certain it needs to force the `colPos` value to `18181`, which only happens if a parent content element can be found.

In the case this doesn't fix your issue I'd like to hear from you again (just ping me and I'll reopen the issue).

**Comment by sypets** [comment]
Thanks for the fix. I'll let you know.
