### ISSUE TITLE
[BUG][8.7.1] Ajax not completed when draging element to first position in gridelements column 

### ISSUE THREAD

**Issue by dacostafilipe** [FluidTYPO3/flux#1420]
Typo3 : 8.7.1
Flux : 8.2.1
Gridelements : dev-master f0098d7

Dragging an element inside a gridelement column at the first position does produce a SQL error that leads to non completion of the Ajax call because the JSON response is corrupted:

![screen shot 2017-06-02 at 16 57 25](https://cloud.githubusercontent.com/assets/922998/26731558/bc2fcd98-47b4-11e7-83b5-0ff918d9e24a.png)

The SQL error is `Column 'colPos' cannot be null` and the query is :

`UPDATE tt_content SET tstamp='1496393229',pid='42',sorting='0',uid='67',tx_flux_parent=NULL,tx_flux_column=NULL,colPos=NULL WHERE uid = '67'`

But the element is correctly moved as if I reload the page, the element is on the right position.

**Comment by NamelessCoder** [comment]
Please help track down the source of that query:

* Is it dispatched from Flux, and if so, from where in the code?
* What were the input variables / input record values that caused the error?
* Were those values processed before by gridelements? - because at the very least, `colPos` is not an expected value from either DB or command arguments when moving records.

I'm not sure about the cause, but in pure FluidTYPO3 sites the described situation cannot happen; `colPos` will always either remain untouched or be changed to `18181`.

**Comment by NamelessCoder** [comment]
I can provide additional information:

There is exactly two places where Flux would potentially be capable of setting `NULL` as value of `colPos`, both in `ContentService->moveRecord()`:

1. If `$relativeTo < 0` we assume a relative record (negative UID value) and fetch the relative record (w/o restrictions) and assign `$row['colPos'] = $relativeToRecord['colPos'];`.
2. If `$relativeTo >= 0` we assume the value must be used as `colPos` value.

All other cases either assign a constant as value or contain conditions.

The first case might fail if Gridelements passes a "magic" negative value that isn't a relative record UID, or if the record for some reason can't be resolved, or (and this is just for the theoretical completeness) some XCLASS is causing database returns to not contain the `colPos` column.

The second case is more likely: if Gridelements actually passes `NULL` in `$relativeTo` that would cause Flux to copy `$row['colPos'] = $relativeTo;` and the condition allows `NULL` (which would be cast to `0` before comparing).

I've taken what I can of precautions in Flux (see linked commit which reduces the potential `NULL` assignment case to only case 1 above). This should help you find the last information we need:

* Is this because `$relativeTo` gets set to an invalid value by Gridelements? If so, you'd have to request a fix there (obviously) - and if that's the case, Flux might not be the only extension affected by this which makes it even more appropriate to prevent the invalid value in Gridelements.
* Or is this because the relative record resolving fails (or the move placeholder gets applied incorrectly)? If this is the case you can take a closer look at the criteria used to select the record, how it gets transformed for move placeholder, and what `colPos` of the resulting overlaid record is.

If you find that the problem is with the record resolving then please come back here with information about which part fails and what the conditions are which must be true before this happens.

But of course it's also possible that the linked commit completely works around the issue. If it does work around the problem then the processing in ContentService is safe to combine with Gridelements - and if it does, please close this issue ;)

**Comment by dacostafilipe** [comment]
The issue was that my `$relativeTo` has "-1" as value.

I switched to the `development` branch, where this issue is fixed.

Thanks for your time @NamelessCoder !
