### ISSUE TITLE
[FEATURE] FAL transform

### ISSUE THREAD

**Issue by ogrosko** [FluidTYPO3/flux#1425]
Is it possible to use transformation for fal field?
Something like this:

`<flux:field.inline.fal name="image" transform="TYPO3\CMS\Core\Resource\FileReference" />`

Now it throws:
`Argument 1 passed to TYPO3\CMS\Core\Resource\FileReference::__construct() must be of the type array, string given`

Would be great to have this possibility ;)

**Comment by NamelessCoder** [comment]
Your wish is my command (also, that was a pretty good idea!). The linked commit is sort of a compromise because there's still no easy way to resolve relationships, but it definitely solves this use case in a neat fashion when you've got a UID, file path, etc. as input and a "factory" object that can give you something else based on that value.
