### ISSUE TITLE
flux:field.relation emptyOption not saved

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/flux#1427]
I've got a `<flux:field.relation>` with an `emptyOption` attribute in a `fluidpages` page configuration.

The empty option appears, but after saving the page, the element is rendered with the last option (from the `table` attribute) selected. It is also not saved in the flexform xml in the page settings.

This happens with flux 8.0.2 and flux 8.2.1, in combination with fluidpages 4.1.0 and fluidpages 3.6.1.

Also any values from the `items` attribute are also not saved, showing the same behavior as the `emptyOption` value.

```
  <f:section name="Configuration">
    <!-- backend page configuration -->
    <flux:form id="article">
      <flux:field.relation
          name="settings.advisor" label="Advisor"
          emptyOption="All"
          items="{0:{0:'All2',1:'0'}}"
          table="tx_dossiers_advisors"
          />
```

![2017-06-28 flux relation emptyoption](https://user-images.githubusercontent.com/59036/27630423-c24c8cfc-5bf5-11e7-9181-4d1e57888a58.png)

----
Related to #1070 and 27d5d81.

**Comment by NamelessCoder** [comment]
Just to clarify:

* Do you actually specify `items` this way or is it just to illustrate? We achieve the empty option by manipulating the items array so using both may not be compatible.
* Have you confirmed this also fails on `dev-development` of Flux since merging https://github.com/FluidTYPO3/flux/commit/d5cde03a4ee31226cae9a21472fa446dd8c6b841 which I have a hunch could be related (FormEngine confused and mishandles items because array is not wrapped with expected TCEforms tag).

**Comment by cweiske** [comment]
- I tried it with and without `items`
- I did not try with development, only with the latest TER version

**Comment by NamelessCoder** [comment]
I haven't been able to reproduce this one on TYPO3 8.7.3-dev (sorry, haven't updated to most recent HEAD for testing - stuck in the middle of a big pile of code). I'm not sure if the problem was fixed in Flux or Fluidpages but it seems to be fixed all the same.

I can confirm that it works with any combination of `items`, `table` and `emptyOption` and the empty option value gets saved.

This could be an issue with inheritance (but you don't say if this is a child page which expects inheritance). Since empty values would be inherited by default, this could explain why an empty option cannot be saved - you can probably quickly determine if the value that gets saved when you select the empty option, is the value that is defined in the parent page's sub-page configuration. The options `inherit` and `inheritEmpty` apply here and give you (some) control over the inheritance.

**Comment by cweiske** [comment]
Then we'll close this.
