### ISSUE TITLE
[QUESTION] Add a FlexForm XML file

### ISSUE THREAD

**Issue by mmsdivino** [FluidTYPO3/flux#1436]
I know that here is not a place for questions, but I was looking for in documentation and I didn't find.
I have a template and I want to add a FlexForm XML file, like in TCA, in type = flex. Is there a way to do it similarity for TCA?

Thanks

**Comment by NamelessCoder** [comment]
I'm not sure I understand the question (but it looks like it's a TYPO3, not a FluidTYPO3 question). If you want to add a separate XML-format DS file you use the TCA type `flex` and put a DS array or file reference in the `ds` array. If this really is a question about Flux and your intention is to use an XML file with a Flux template then I have to disappoint you and say that's not possible (at least not without some significant customisation for example in the form of a custom Provider class).

If you need more info about the TCA `flex` type check the official TYPO3 documentation (and select the version of TYPO3 you're using because changes do happen every now and then).
