### ISSUE TITLE
Duplicate content elements

### ISSUE THREAD

**Issue by papillon6** [FluidTYPO3/flux#1437]
After I upgraded TYPO3 6.2 to 8.7 all content elements created with "fluidcontent" are shown twice in the "content element wizard":

![image](https://user-images.githubusercontent.com/10079852/28309651-48d390d6-6baa-11e7-9901-66ece90f991d.png)

Another weird issue:
All content elements using a "grid" (e.g. a two column element) in backend show the content areas twice as well:
![image](https://user-images.githubusercontent.com/10079852/28309761-b37a36ce-6baa-11e7-943c-9fbcf99b00c6.png)

Frontend is not affected. Content is rendered correctly.

Using TYPO3 8.7.3, flux 8.2.1 and fluidcontent 5.2.0
Is this a bug or did I miss any update scripts during the upgrade?

**Comment by NamelessCoder** [comment]
How are you registering your templates in this case? Just by provider extension key?

Did you check the migration info on fluidtypo3.org to see if you need to, for example, change the use of ViewHelpers (case in point: `flux:form.content` must no longer be used in `flux:grid.column` because that does exactly cause duplicate grids - the VH is now a shorthand to add a single column).

**Comment by papillon6** [comment]
Hi NamelessCoder,

thanks for pointing me in the right direction.

Just in case someone else is struggling with a similar problem:
`flux:grid:column` was still in use. Removing it from the flux config solved it.
The provider extension was registered twice indeed. In ext_localconf.php as well as ext_tables.php ...
