### ISSUE TITLE
Page grid strange behavior

### ISSUE THREAD

**Issue by dahaupt** [FluidTYPO3/flux#1454]
**First of all, thanks for your great work with this library and I'm thankful for any help on this one.**

The flux [ViewHelper reference](https://fluidtypo3.org/viewhelpers/flux/8.1.0/Grid/ColumnViewHelper.html) says:

> Use the name attribute for grids in content elements, and the colPos attribute for grids in pages templates.

I have this template file in `Private/Templates/Page/Standard.html` with the following configuration:
```
<f:section name="Configuration">
        <flux:form id="Standard" label="Standard">
            <flux:grid>
                <flux:grid.row>
                    <flux:grid.column colPos="0" label="Spalte 1"/>
                    <flux:grid.column colPos="1" label="Spalte 2"/>
                    <flux:grid.column colPos="2" label="Spalte 3"/>
                </flux:grid.row>
                <flux:grid.row>
                    <flux:grid.column colPos="3" name="column4" label="Spalte 4"/>
                    <flux:grid.column colPos="4" name="column5" label="Spalte 5"/>
                    <flux:grid.column colPos="5" name="column6" label="Spalte 6"/>
                </flux:grid.row>
            </flux:grid>
        </flux:form>
 </f:section>
```

This results in the following backend page grid: 
![image](https://user-images.githubusercontent.com/15915048/29831351-2544f9b4-8ce5-11e7-90f2-ba095d2b0d12.png)

**Problem:**
As the documentation says the `name` attribute should only be used on content templates but this is a page template. Without the `name` it's not working correctly and/or even behaving strange with just showing me the last grid.

**Environment:**
Typo3 v8.7.4
"fluidtypo3/flux": "^8.2",
"fluidtypo3/vhs": "^4.3",
"fluidtypo3/fluidcontent": "^5.2",
"fluidtypo3/fluidpages": "dev-development"

OS: Windows 10 (using xampp)
PHP: 7.1.1
MySQL: 5.5.5

**Comment by dahaupt** [comment]
It's also very confusing that in the documentation for page templates it's done like this with the use of the `name` attribute:

```
<!-- Backend layout grid (TYPO3 6.x and greater only) -->
        <flux:grid>
            <flux:grid.row>
                <flux:grid.column colPos="1" name="Sidebar" style="width: 25%" />
                <flux:grid.column colPos="0" name="Content" style="width: 75%" />
            </flux:grid.row>
        </flux:grid>
```

https://fluidtypo3.org/documentation/templating-manual/templating/creating-templates/page-template.html

**Comment by NamelessCoder** [comment]
Thanks for reporting, @dahaupt - the documentation is a bit misleading, it should actually be stating that the `name` **and** `colPos` are required for page templates, while content ones can get by with just the `name`.

There are two reasons for that:

1. The `name` is used when building the array; it becomes the index. That's why you only see one column: the 2nd and 3rd columns both override the first because they have the same name.
2. It is possible to add LLL for page columns to make the label header translatable. Such references use the column name to identify each column.

If you feel up to it, extending the ViewHelper documentation is pretty easy. If you find the class file here on GitHub and click the "edit" icon, you can edit the phpdoc/argument labels and this way prepare a pull request for us to get the ball rolling! ;)
