### ISSUE TITLE
Should respect existing tabs in New Content Wizard

### ISSUE THREAD

**Issue by Josta** [FluidTYPO3/flux#1459]
When adding a Flux content element with a group configured in the form options, Flux (in _Classes/Helper/ContentTypeBuilder.php_ Line 238) creates a new tab for the wizard. Say I want to add an element to an existing tab like "Typical page content". It works in general, but unfortunately the page TSConfig for that tab gets overridden, resulting in the loss of the tab label and the tab "show" configuration.

Flux should check if the tab exists, and (if true) only include
`mod.wizards.newContentElement.wizardItems.[groupname].show := addToList([contentname])`

**As an afterthought:** if the tab doesn't exist yet, the label for the new tab should not be the group name, but a language key from the provider extension's locallang.xlf, like "flux.groups.[groupname]". That way we can localize it.

**Comment by NamelessCoder** [comment]
> the label for the new tab should not be the group name, but a language key from the provider extension's locallang.xlf, like "flux.groups.[groupname]". That way we can localize it.

This part we can't facilitate. The problem is that the group isn't "only yours" in the sense that any extension could add the same tab. If they did, the label would either override yours or be ignored because of yours, or worse, duplicate the tab (I don't recall the pageTSconfig well enough to say which). You can however override the `label` property via pageTSconfig and set it to an LLL reference.

**Comment by NamelessCoder** [comment]
Pushed solution is the best I can do, but it only protects the hardcoded list of system tabs from being overridden. Since pageTSconfig is simply not parsed at the time this happens, it is not possible for Flux to determine if a tab was already added.
