### ISSUE TITLE
Replace deprecated Wizards

### ISSUE THREAD

**Issue by dacostafilipe** [FluidTYPO3/flux#1465]
flux : **8.2.1**
Typo3: **8.7.7**

```xml
<flux:field.input name="name" label="Label">
	<flux:wizard.link
		activeTab="page"
		blindLinkOptions="folder,mail,file,spec"
		blindLinkFields="class,target,params"
	 />
</flux:field.input>
```

I would expect the "page" tab to be active, but the active one is still "url" (External URL).

**Comment by xf-** [comment]
https://docs.typo3.org/typo3cms/extensions/core/8.7/Changelog/8.6/Deprecation-79440-TcaChanges.html
We need to implement the simpler renderType and fieldControl

**Comment by geronimoooo** [comment]
In Typo3 10.2.2 and Flux 9.2 the link wizards don't work at all, seems like the wizards are gone in the TCA, as xf- said. Currently, there seems so be no way to create a useable link field in flux. I added the renderType attribute as hotfix to get my 10.2.2 instance up and running.

To get a working link field in 10.2.2, simply replace the [attached files](https://github.com/FluidTYPO3/flux/files/4039955/flux_field_renderType_hotfix.zip) and then create the field like that:

`<flux:field.input name="link" label="Linkziel (optional)" size="10" default="" **renderType="inputLink"** /> `

[flux_field_renderType_hotfix.zip](https://github.com/FluidTYPO3/flux/files/4039955/flux_field_renderType_hotfix.zip)

**Comment by NamelessCoder** [comment]
All wizards and field types in Flux will be deprecated and scheduled for removal, since it is no longer feasible to maintain a unified API for individual types. TYPO3 versions increasingly throws exceptions rather than ignoring unknown/deprecated TCA configuration options and this means the same field syntax will not be possible on all supported versions.

The replacement solution will be:

* Fields will be replaced with one generic field type with arguments to enforce a certain TCA `type` value and a generic `config` array, through which you can pass things like `fieldWizard` and `renderType` without Flux having to declare these as arguments.
* Wizards will have no replacements (but can be attached by passing `config` arrays with the necessary setup).

This eases the maintenance effort and means Flux can refer to external documentation for all supported options, specific to the TYPO3 version being used.

While this is less than ideal in terms of future migrations, it drastically reduces the maintenance and compatibility efforts while also reducing the code base of Flux.

**Comment by MartinH0** [comment]
@NamelessCoder would you please provide a example how we should now create links in TYPO3 v10?
I can not create any links with Flux. As the ols method is gone, will there be a new way to create links or will this never come back to FLUX?

Also: if its not coming back to FLUX how do you think should we now implement links in TYPO3?

**Comment by NamelessCoder** [comment]
@MartinH0 The future approach should be `flux:field` with a `config` array provided, there you can specify `renderType="inputLink"` iirc. The new wizards strategy in TYPO3 no longer allows for a sub-array of added wizards, it's all done with custom rendering types if I'm not mistaken. It's been a while since I've had to create a field with wizards... in any case, `flux:field` is the substitute for creating any field type (and was implemented because I've no longer got the time to keep up with multiple changes to TCA structure which differ from version to version).

**Comment by Martin-Ernst** [comment]
How is it now (TYPO3 10) possible to add configuration to the `renderType="inputLink"`? like

```
        'fieldControl' => [
            'linkPopup' => [
                'options' => [
                    'blindLinkOptions' => 'folder',
                    'blindLinkFields' => 'class, target',
                    'allowedExtensions' => 'jpg',
                ],
            ],
        ],
```

**Comment by X-Tender** [comment]
@Martin-Ernst Maybe it comes to late but you have to nest it this way:
`config="{renderType:'inputLink', fieldControl: {linkPopup: {options: {blindLinkOptions: 'telephone,folder,mail,url,file,news'}}}}"`
