### ISSUE TITLE
$templateRootPath for registerProviderExtensionKey must be configurable!

### ISSUE THREAD

**Issue by Atsyn** [FluidTYPO3/flux#1478]
Right now path to template files is hardcoded and can't be edited: https://github.com/FluidTYPO3/flux/blob/development/Classes/Core.php#L107

It's not good and create a lot of problems and limits for folder structure in extensions.
This path must be editable via TypoScript, extension configuration or additional attribute for this function.

**Comment by NamelessCoder** [comment]
You should note that this method is, as the comment says, a temporary case that's designed to consume Fluidcontent templates automatically by detecting the templates. Referring to how Fluidcontent detected these templates, the expected folder path was exactly the conventional path with no way to change this. Since Fluidcontent is now deprecated and Flux has other methods to register a specific template file as CType, the right way to target non-conventional template files for use as CType, is through `\FluidTYPO3\Flux\Core::registerTemplateAsContentType`.

You should also be aware that these registrations happen at a time when TypoScript is simply not available, which is why you can't override the *registration-time* paths. We have to rely on the convention here, but that said, you can override the partial- and layout root paths so that when you *render* your template, Flux will look in additional places. The one path you can't override is the `templateRootPath` but registering a template by absolute path means this path array becomes redundant.

Finally, you can use newly added Flux hooks to manipulate pretty much everything, including resolving of template files and gaining access to Provider instances right after they're registered.

So while I understand the reason for requesting this, the request concerns temporary code that's there for migration purposes, the alternative (recommended) usage supports custom paths, and there are several hooks how that will let you change such context variables - which is why I will close this issue as "won't fulfil / already possible with public API".

Tips:

* Your `<f:section name="Configuration">` and `<flux:form>` will not be evaluated with template path overrides - if you render partials from within this section, only your extension's partials will be used. And your Layout must exist in the conventional path even if you override it later.
* Your `Main` (or other) section *will* be evaluated with partial- and layout path overrides enabled since this happens long after TypoScript is available.
* Overriding which template file gets used is also possible now using hooks, for example `\FluidTYPO3\Flux\Hooks\HookHandler::PROVIDER_RESOLVED_TEMPLATE` - see https://github.com/FluidTYPO3/flux/commit/1f76e8a60b99d7b93ee8752345573530d4b81d8e for how to use those hooks.

**Comment by Atsyn** [comment]
@NamelessCoder thank you for answer.
