### ISSUE TITLE
Get page Uid of a page linked with flux:wizard.link in a flux:field.input

### ISSUE THREAD

**Issue by spackmat** [FluidTYPO3/flux#1480]
Hi, when I have an `flux:field.input` field using `flux:wizard.link` to choose a page, it creates a link like `t3://page?uid=123`. This is no problem, when I just want to render a link [as described in the templating manual](https://fluidtypo3.org/documentation/templating-manual/templating/creating-templates/content-element.html) using `<f:link.page pageUid="{targetPage}">My link text</f:link.page>`.

But now I want to display content from that page like this
`{v:page.info(pageUid: '{targetPage}', field: 'whateverfield')}`, but the `pageUid` parameter of `v:page.info` expects an integer, where `f:link.page` also works with 't3://' formatted URIs.

For now, I'm using a workaround using `v:format.pregReplace` to extract the Uid of the linked page, but I'm pretty sure, that there is a better way to get the page info for a linked page in an input field using the `flux:wizard.link`.

So does anybody have an idea how to solve this?

**Comment by dahaupt** [comment]
@spackmat I think there is no better way at the moment. In the past I've done it in the same way. We could think of accepting a `typolink` as an input in `<v:page.info>` but I'm not sure if that's a great idea.

**Comment by spackmat** [comment]
Why not? It would be consistent with `<f:link.page>`, when the `pageUid` parameter accepts the same inputs. Or the other way around: why does `pageUid` accept typolinks at all then?

**Comment by dahaupt** [comment]
@spackmat There are multiple viewhelpers with a `pageUid` input. If we do it for `<v:page.info>`, we should do it consistently for all viewhelpers. If it's just a rare case to use it like this, I think the solutions to use `<v:format.pregReplace>` is just fine and logical.

@NamelessCoder What is your opinion about this?

**Comment by xf-** [comment]
I think it isn't a nice solution. Wizards supports different stuff like pages or content and sections. Would be more interesting to add an option to get an object of the target + type, section and pageUid and maybe title

**Comment by NamelessCoder** [comment]
I would reject such a feature:

* The request is to add a processing of a standard field value when you use a Wizard, but this processing is in no way Flux-specific.
* _When you need a page UID instead of a link target, you really should declare a relation to pages or use the record selection wizard - not the link wizard._
* This may not even apply in VHS since there are plenty options to get there if you must use the link wizard for some reason. But since the goal of such a feature would be to "abuse" the link wizard generated URLs, I would not want to add it there anyway.

The thing to take away from this is that when you need a certain format of the data, this should be handled by selecting the right TCEForms component types and settings - that will give you the right type of data in the DB. So in this case: the link wizard is out of the question since it can create literally any type of link - but a proper "select page UID" field would 1) restrict to only linking to pages and 2) give you exactly the type of data you need.

Lastly: `f:link.typolink` is the only ViewHelper which officially supports the links generated by the wizard, `f:link.page` and others are simply not spec'ed to receive that type of link. So you should only be using `f:link.typolink` and it will indeed extract and render things like the title of the page you link to.

Hope this explains it.

**Comment by spackmat** [comment]
@NamelessCoder Yesm thanks, this explains it. :)

**Comment by in-session** [comment]
Maybe somebody needs it:

```
<v:condition.string.contains haystack="{link}" needle="t3://page?uid=">
  <f:then>
	  <v:variable.set name="pageuid">{v:iterator.explode(content: '{link}', glue: ' ')->v:iterator.first()->v:format.replace(substring: 't3://page?uid=', replacement: '')}</v:variable.set>
	  {pageuid}
  </f:then>
  <f:else>
	<f:link.typolink parameter="{link}" class="int_btn bg-dark int_btn_one btn mt-2 rounded-0 p-0" />
  </f:else>
</v:condition.string.contains>
```
