### ISSUE TITLE
f:render partial inside flux:form not working properly within custom provider

### ISSUE THREAD

**Issue by jmverges** [FluidTYPO3/flux#1485]
f:render partial inside flux:form doesn't resolve the proper partials paths set up for the extension itself 

@NamelessCoder any clue?

What I've been able to debug so far is baseRenderingContext is just having the typoscript settings from the default extension and not the overwritten ones, regarding partialPaths

**Comment by xf-** [comment]
example element in a gist?

**Comment by NamelessCoder** [comment]
@xf- This should be possible to reproduce by adding a second partialRootPath in a provider extension, with a single partial template file that has a flux form field, then trying to render that partial by name from within the Configuration section.

The cause is that at the time when this happens, TS is not yet available and we only have our standard paths. Though this *does* become available later, the template *must* be able to function initially without it and should not depend on other partials for vital stuff.

We may need some way to handle this - which is why this issue remains open ;)

**Comment by NamelessCoder** [comment]
For anyone finding this issue because they face similar problems:

Flux cannot resolve TS-defined template paths / partial paths - this is by design and is done this way because Flux needs to be able to extract Form definitions from templates at a point in the request where 1) no TS is actually loaded, and 2) a page UID context doesn't necessarily exist, and 3) where paths are predictable and permanent (as in: cannot be changed by page-specific runtime configuration).

Because of this, Flux assumes and is only compatible with templates and partials placed in the default locations in your extension - in the case of partials, `EXT:myext/Resources/Private/Partials`. If you place all partial templates in this path then they will work if you `f:render` a partial even within the `Configuration` section.

That being said, custom paths to partials and layouts are supported when rendering the Flux-enabled asset in FE and in this context, Flux will respect paths / path overrides defined in TS on a specific page or parent page of the asset.
