### ISSUE TITLE
TYPO3 8.7.9 - flux:field.multiRelation transform doesn't work

### ISSUE THREAD

**Issue by MarvinRudolph** [FluidTYPO3/flux#1510]
(Flux Version 8.2.1)

I added a flexform configuration to my plugin with a multi relation field where I can select event categories.
These selected categories should be transformed into an ObjectStorage with the Event model but I only get the id when I debug it.

Maybe I do it wrong but I can't find any documentation how to do it right.

{namespace flux=FluidTYPO3\Flux\ViewHelpers}

<f:layout name="Default" />

<f:section name="Configuration">
	<flux:form id="events">
		<flux:field.multiRelation
			name="settings.eventCategories"
			size="10"
			maxItems="999"
			table="tx_events_domain_model_eventcategory"
			condition="tx_events_domain_model_eventcategory.deleted = 0 AND tx_events_domain_model_eventcategory.hidden = 0"
			transform="TYPO3\CMS\Extbase\Persistence\ObjectStorage<Vendor\IgEvents\Domain\Model\EventCategory>"
		/>
	</flux:form>
</f:section>

So how does it work? Do I miss something or is this "just" a bug?

Thanks in advance!

**Comment by NamelessCoder** [comment]
Multirelation transformation will not work without a custom class to do the transformation. Because the field only stores the relation count, several lookups have to be made before transformation can happen - and it is these lookups that Flux won't do for you. So while multirelation fields do support transformation, they do not support that particular transformation.

The way you do this is to create a class that will transform your particular relation to domain objects - then refer to that class with `transform="My\Vendor\Transformer->transform"`.

In the next version of Flux you can also use hooks to transform these things:

https://github.com/FluidTYPO3/flux/blob/development/Classes/Transformation/FormDataTransformer.php#L62

Using the pre-transform hook you can change the value (an integer) to an array of related UIDs. Flux can then handle those by fetching with standard repositories, using the template you pasted.

**Comment by MarvinRudolph** [comment]
Oh wow I didn't know that. Thanks for your help and your suggestion with the Transformer!
