### ISSUE TITLE
JS Error if flux.field name-attribute contains dot in name and FAL uploader is called

### ISSUE THREAD

**Issue by SchuBu** [FluidTYPO3/flux#1515]
I have a flux field
`<flux:field.inline.fal name="settings.thumbnail" required="true" label="Thumbnail" multiple="false" maxItems="1"/>`
the name of this field contains a dot (settings.thumbnail)

when I want to open up the FAL uploader, I receive this JS error:

> Error: Syntax error, unrecognized expression: #data-1-tt_content-NEW5a775368d0a77034750246-pi_flexform---data---options---lDEF---settings$1thumbnail---vDEF

After renaming the name-attribute to "settings_thumbnail" the error disappears.

**Comment by NamelessCoder** [comment]
You'll have to report this one to TYPO3. Briefly explained, Flux is merely a wrapper for TCA features so the only things we are responsible for, is passing the values you put in your template to TYPO3 in the right places in the TCA API. The only type of issue concerning fields and their behavior, which we *can* do something about, is if Flux does not pass the right TCA parameters or otherwise creates invalid TCA. And that does not appear to be the problem here.

If TCA does not support a dotted field name for the IRRE component that's something that has to be fixed in TYPO3. In particular since dotted field names are intentionally supposed to be supported in Extbase for any field type.

**Comment by SchuBu** [comment]
mea culpa: 
it is only a problem with the developer branch of flux. master branch without problem.

TYPO3 Version is the same (8.7.9). So i dont't think it's a typo problem. until I used the dev branch I could "dot"-named attributes.
