### ISSUE TITLE
Question regarding using flux to create custom content elements

### ISSUE THREAD

**Issue by hm-tim** [FluidTYPO3/flux#1520]
Hi everyone, 

I've recently started using flux to create custom content elements in my TYPO3 projects. One thing I was wondering was if it is still possible use the benefits of Partial-/ TemplateRootPaths.
To my current understanding you have to register the new template directly through ext_localconf.php, there is no way to just provide a folder with templates and there is no way to use template-overrides, is that correct?
If so - are there any plans to reintroduce such a feature?

**Comment by TheNaderio** [comment]
I think you didn‘t understand the usage yet. 
Here is a link to the basic documentation. 
https://fluidtypo3.org/documentation/templating-manual/introduction/template-file-usage.html

Templates/partials etc. are fully usable - this is FluidTYPO3 and definitely uses fluid :)

**Comment by NamelessCoder** [comment]
Hi @hm-tim,

> One thing I was wondering was if it is still possible use the benefits of Partial-/ TemplateRootPaths.

Yes, still possible.

> To my current understanding you have to register the new template directly through ext_localconf.php,

You still have to do this, but...

> there is no way to just provide a folder with templates and there is no way to use template-overrides, is that correct?

...you can also register by controller name instead of registering individual template files. See https://fluidtypo3.org/documentation/templating-manual/templating/provider-extension/registration-in-php.html.

It is however *not recommended* to override the `templateRootPaths` specifically. Extend them, yes - override them, no. The base/default paths should contain all templates referenced by those templates, extended paths can reference base templates and add new ones - but base templates should obviously never reference templates that only exist in your extended paths (this is true for all of the types of paths).
