### ISSUE TITLE
Non-translated group names do not work

### ISSUE THREAD

**Issue by yol** [FluidTYPO3/flux#1524]
flux tries to auto-detect whether a group name given in `<flux:form.option.group>` is available from a `locallang.xlf` here: https://github.com/FluidTYPO3/flux/blob/development/Classes/Helper/ContentTypeBuilder.php#L261

But it does not work, since `LocalizationUtility` needs `$GLOBALS['LANG']` for translating, which is not available at this point. So it will just return the `LLL:...` string unchanged. What should be done here? Initialize `$GLOBALS['LANG']` manually?

**Comment by X-Tender** [comment]
Are there any Updates on this issue? :/

**Comment by X-Tender** [comment]
Oh I've figured it out by digging in the `ContentTypeBuilder` The correct `trans-unit` id have to be `flux.newContentWizard.foobar` with this decleration
`<flux:form.option name="group" value="foobar" />`

**Comment by NamelessCoder** [comment]
@X-Tender is completely right - and this is the only way to have a group name consisting of anything except `a-z0-9`. Since the original reported issue, Flux no longer attempts to translate the group name and will instead generate the expected XLF reference. If the XLF label does not exist the group tab will still be rendered but appears invisible due to the empty name (if you hover the mouse where the tab should be, you will see it highlight and be able to click it).
