### ISSUE TITLE
Usability problems moving panels in accordion since #1563

### ISSUE THREAD

**Issue by pkerling** [FluidTYPO3/flux#1578]
Hi,

first of all - thanks a lot for finishing #1563. I sincerely hope that it solves a lot of issues related to copying, moving, drag-and-drop etc. and so far it looks very good.

However, I think that in the transition a for me quite useful feature has been lost.
If you use flux to describe an accordion with multiple panels (which does not seem uncommon), you run into an usability issue with the new colPos approach when moving panels.

This is my example configuration:
```
	<flux:form id="accordion" label="Accordion">
		<flux:form.sheet name="panels" label="Panels">
			<flux:form.section name="panels" label="Panels">
				<flux:form.object name="panel" label="Panel">
					<flux:field.input name="title" label="Title" />
					<flux:field.checkbox name="active" label="Open?" />
				</flux:form.object>
			</flux:form.section>
		</flux:form.sheet>
		<flux:grid>
			<v:condition.type.isArray value="{panels}">
				<f:for each="{panels}" key="id" as="panel" iteration="iteration">
					<flux:grid.row>
						<flux:grid.column name="content.{id}" colPos="{iteration.cycle}" label="{panel.panel.title -> v:or(alternative: 'Panel #{iteration.cycle}')}" />
					</flux:grid.row>
				</f:for>
			</v:condition.type.isArray>
		</flux:grid>
	</flux:form>
```

Before: Panel contents were associated with the column name which included the panel object id. Therefore, when rearranging panels in the list, the content was rearranged respectively, too.
Now: Panel contents are associated with the colPos which just depends on the position of the panel (for lack of a better association). Therefore, when rearranging panels in the list, the content stays at the same position and gets re-associated to another panel.

For me, the new behavior seems counter-intuitive, even though I understand the technical reasons for it. Is this a) intended and is there b) some way to get the old behavior back in some form?

**Comment by NamelessCoder** [comment]
This could be a bit hard to solve - there are also some open issues about the `id` attribute on section objects when the XML source is saved - but in the end it's going to come down to needing to store a unique number between 0 and 99 along with the section object.

And one way to do that would be to add a field (of arbitrary type, they pretty much all support integers). That then stores the colPos value with the section object so when you change the order, that field moves with the container element. Though I'm not sure how that could be done automatically - all solutions have drawbacks because the TYPO3 core itself lacks some way to identify these section objects (this also has a tangent to how FAL relations can't be supported in such objects). None of the post-processing / default-value based solutions I can think of are really good.

There is however one solution that could work. We could make a new field type - a "column position value definer" - which would be a special `select` type component which can only select values from 0 to 99 and which filters out all incompatible values when the items array is built. At the time when components are converted to TCEforms arrays there is a full context of all fields, so it would be possible to do it this way. The field would need to update the form on every change because each change affects all the other colPos definer fields' values. And it has the same drawback as using a default value would: if you don't save the form between adding each object, you can still select colliding values. I really meant it when I said none of the solutions I can think of currently are truly good ;)

On the other hand, your example and issue text gives me an idea. We could introduce a property on `flux:form.object` which can determine if the object is supposed to become a content column when you add one. If that is marked, it will always add a sub-field for the colPos selector that you can't override or remove. And a companion property on `flux:form.section` which can determine if objects inside it, which are to be handled as nested areas, should be presented as rows or columns in the BE view.

Then you also wouldn't have to iterate over those columns. As you say, it's a fairly common use case to make this kind of structure - and it would be quite a bit easier if you just had to change a toggle on `flux:form.object`.

PS: I don't think it will be possible to bring back the original feature. We have to work within the constraints that from now on, the position within the parent has to be specified with an integer which means we're prevented from using those unique hash values like we did before.

**Comment by NamelessCoder** [comment]
Just so we have some code to relate to when discussing this field, here's what could be a hacky solution to get it working immediately by manually adding a field with a cleverly formulated default value. It still has the drawback of needing to save the form after each section object that you add. But it would work, I think... freestyling:

```xml
<!-- inside flux:form.object -->
<flux:field.input name="colPos" default="{sectionObjects -> v:iterator.column(columnKey: 'colPos') -> v:math.max() ->  v:math.sum(b: 1)}" />
```

The inline expression in words:

* Extract the `colPos` column from all existing objects.
* Find the maximum such value that's currently saved.
* Add `1` to that number for the new column value.

**Comment by pkerling** [comment]
> The field would need to update the form on every change because each change affects all the other colPos definer fields' values. And it has the same drawback as using a default value would: if you don't save the form between adding each object, you can still select colliding values.

I think usability-wise this might be even worse ;-) So I won't use the hacky quick-fix for now. Would it be possible to add JavaScript code client-side to do this kind of calculations on the fly instead of using `default`? We could even hide the field from the user.

> On the other hand, your example and issue text gives me an idea. We could introduce a property on flux:form.object which can determine if the object is supposed to become a content column when you add one. If that is marked, it will always add a sub-field for the colPos selector that you can't override or remove. And a companion property on flux:form.section which can determine if objects inside it, which are to be handled as nested areas, should be presented as rows or columns in the BE view.

I think I like this better. Would we then derive the `colPos` values on save? And would that be preclude using `flux:grid` at the same time?

Another semi-related question: What happens to content elements with `colPos` values of panels that are deleted? What happens if you later re-add a panel with the same `colPos` (this might happen if panels are frequently added/removed and `colPos` grows beyond 99 - then we will have to return to smaller non-occupied numbers).

**Comment by NamelessCoder** [comment]
Hint for implementing that component: see "Custom" component - and the UserFunctions class inside Integration/FormEngine. A copy of the Custom component that's preconfigured with a special UserFunction that renders our weird field and attaches the JS, should be enough :)

**Comment by NamelessCoder** [comment]
WIP for the section-objects-as-grid feature: https://github.com/FluidTYPO3/flux/pull/1582

I will continue with the colPos selector to make it part of that patch.

**Comment by NamelessCoder** [comment]
I think I know how to solve that whole colPos-uniqueness thing. Instead of caring the slightest about the grid structure itself - use the ColumnNumberUtility to make a min/max expected colPos value, then select "colPos" from all records that are within that range, and use the maximum value plus one.

That should also solve the situation with deleting panels. Then a colPos value can only be "reused" if there are no records using that colPos value.

**Comment by NamelessCoder** [comment]
And it might even be possible to avoid the JS. I'm still debugging the colPos selector component to see if we receive the entire FlexForm array with all not-yet-saved objects.

**Comment by pkerling** [comment]
> And again there's a drawback. If you delete the panel with the highest colPos value, then save the parent element, then create a new column - it could get the same colPos value as the one you deleted, or one that was previously deleted.

Yes, that's exactly what I was worrying about. 

> I think I know how to solve that whole colPos-uniqueness thing. Instead of caring the slightest about the grid structure itself - use the ColumnNumberUtility to make a min/max expected colPos value, then select "colPos" from all records that are within that range, and use the maximum value plus one.
> 
> That should also solve the situation with deleting panels. Then a colPos value can only be "reused" if there are no records using that colPos value.

You are right, that would solve the reuse problem. I was thinking about reassigning the CE to an invalid `colPos` or something along those lines when their panel gets deleted, but this sounds like it might be less complicated to actually implement.

I am definitely willing to help out with this, but I'm not sure what the current status of your experiments is. If you still need me to do something, just yell :-) (It might take a few days though)

**Comment by NamelessCoder** [comment]
Current state of the section-object-as-container is that it all works, with the exception of use cases where you add more than one panel without saving the parent record. In this case, the colPos value is the same for the panels you add second, third etc.

I think we'll need the JS we talked about. It needs to somehow listen for creation of new panels and target the colPos field to write a unique value. And to use in that script, there is one thing that I need to add still: a SQL query which resolves all colPos values *that are currently in use* and assigns those to a property somewhere in DOM. This way, that list can be read and use to avoid assigning colPos values from JS that would collide with colPos values being used in the DB currently.

So there's not much left, but if you want to help out with the JS part that would be great :)

**Comment by NamelessCoder** [comment]
Section-objects-becomes-grid feature is merged, JS improvements for the colPos field handling is under review but not linked to this issue. Closing issue.
