### ISSUE TITLE
Translation handling for TYPO3 9

### ISSUE THREAD

**Issue by pkerling** [FluidTYPO3/flux#1581]
`pages_language_overlay` has been effectively removed in core issue 82445:

https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.0/Breaking-82445-PagesAndPageTranslations.html

flux still uses this at least in one place in `AbstractProvider`. I can try a PR if it is enough to fix this single usage, but there might be other problems.

**Comment by NamelessCoder** [comment]
A PR would be welcome for this. Fluidpages also has an extension toggle that we probably need to ignore on TYPO3 9.0+ so a provider doesn't get registered for a table that doesn't exist.

I'm not completely sure what the new behavior is, but perhaps we can read the already translated-overlay'ed data from somewhere instead of reading records from SQL?

**Comment by pkerling** [comment]
Indeed it looks like `$GLOBALS['TSFE']->page` already has the overlayed values.

**Comment by pkerling** [comment]
Seems it was that simple - I was planning on checking whether v8 also had that behaviour but you beat me to it. I'll see what else I'll encounter with the v9 page I'm currently doing. `vhs` will probably be next ;-)
