### ISSUE TITLE
Grid: Copied element contains the flexform of the origin element

### ISSUE THREAD

**Issue by ubrt** [FluidTYPO3/flux#1586]
Hey, 

I've created a grid content element with two cols: 

```xml
 <flux:grid>
    <flux:grid.row name="flux-grid">
      <flux:grid.column name="left" label="LLL:flux.splitters.columns.left" colPos="1" />
      <flux:grid.column name="right" label="LLL:flux.splitters.columns.right" colPos="2" />
    </flux:grid.row>
  </flux:grid>
```
When I insert a content element into a col and create a copy to any position inside or outside the grid , the edit dialog of the copied element contains the flexform of the origin element.

![image](https://user-images.githubusercontent.com/12350410/42819226-383d564c-89d3-11e8-9fa1-739ab8c04713.png)

Typo3 Version is 8.7.17
Relevant Extensions:

- flux: 9.0.0
- fluidpages: 4.2.0
- fluid: 8.7.17
- fluid_styled_content: 8.7.17
- vhs: 5.01

This happens for all content elements. Any ideas or hints? Thanks a lot.

**Comment by chriskrj** [comment]
Its the same Problem like in this Ticket #1580 . There is no Solution to this right now.

**Comment by NamelessCoder** [comment]
@ubrt Could you describe in more detail what's going wrong? What is it you expect - and what's actually happening? From your description it sounds like your problem is that "the copy of the content record has the same values as the original" - and that is definitely intended. Creating a copy is *supposed* to make the same values in the copy. The title may be appended with a "Copy 123" which also appears to happen in your case.

You present screenshots of the "layout" and "section menu" fields but I don't understand what your point is. Those fields are not part of the flexform. And you don't show the flexform fields?

And lastly, it looks like you are clicking the edit icon in a column header, not for an individual content element - since your edit screen shows two records being edited at the same time.

It does not appear to be the issue described in #1580 - either that, or I'm having some serious difficulty understanding what you mean by "has the same flexform". So I hope you can elaborate!

**Comment by ubrt** [comment]
@NamelessCoder I'm sorry, the screenshot is missleading and because of the fact that the topic is new to me I sometimes mix up the wording. But as you said it looks like I'm editing a colum but I'm definitely in the edit dialog of a single content element. This also happens when I drag the cloned element out of the grid and edit it from there.

**Comment by NamelessCoder** [comment]
@ubrt Can you confirm that the tooltip when you hover the mouse over the "edit" icon of the element, shows the text "Edit next three records" when your element is inside a column, but says just "Edit" when the element is outside?

**Comment by NamelessCoder** [comment]
Found and fixed :)

**Comment by ubrt** [comment]
@NamelessCoder I currently don't have my laptop with me. But that could really be the source of this behavior. Is this a known/intended behavior or some kind of missconfiguration? If I manually create the elements without using copy and paste everything is alright. I'll check tomorrow morning and give you an update! Thank you so far.

**Comment by ubrt** [comment]
@NamelessCoder Wow... Great news! Thx!
