### ISSUE TITLE
[BUG] PageTSconfig include

### ISSUE THREAD

**Issue by ogrosko** [FluidTYPO3/flux#1600]
Hi
I have multiple domains in one Typo3 instance. With two provider extensions. For this two domains I have set different RTE settings in pageTSconfig. My problem is with pageTSconfig inclusion which is not working.
When I use inline include in Page properties -> Resources -> [Page TSConfig or Include Page TSConfig (from extensions)] this config is not loaded in flux elements (works fine for regular typo3 elements)

For flux elements works only this inclusion in `ext_localxonf.php`:
`\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addPageTSConfig(
    '<INCLUDE_TYPOSCRIPT: source="DIR:EXT:' . $_EXTKEY . '/Configuration/TSconfig/Page/" extensions="ts,ts2,txt">'
);`

Do you know why pageTS can't be included in typo3 BE page props. ?

Typo3 v8.7.11
flux v8.2.1

**Comment by NamelessCoder** [comment]
Sorry for the very late reply. I'm almost certain this is related to https://github.com/FluidTYPO3/flux/issues/1671, which is caused by TYPO3 being unable to resolve the correct page UID in some contexts, possibly combined with Flux caching the definitions of Flux fields, and possibly caused by the TYPO3 core not applying pageTSconfig correctly when the field exists within a FlexForm.

To avoid caching of the definition you can set `options="{static: 0}"` on `flux:form` but I cannot guarantee this will be enough. If it doesn't solve it then this problem should be reported to forge.typo3.org for further investigation to determine if missing page UID context and/or limitations of FlexForm fields is the cause.

Possible workaround: set `static: 0` as described above and combine this with a custom ViewHelper which can resolve the right pageTSconfig value, then use this ViewHelper inside the `flux:form.field` attribute that you need to manipulate with pageTSconfig. If it is not possible to use a field attribute to specify what you need, please open a new issue with a feature request to make this possible.
