### ISSUE TITLE
flux:field.inline.fal in fluid for

### ISSUE THREAD

**Issue by gianstraf** [FluidTYPO3/flux#1602]
With this test case:

```
<f:for each="{items}" as="sectionItem" iteration="iteration">
    <flux:form.sheet name="additionalTab{iteration.cycle}" label="Items {sectionItem.item.name}">
        <flux:field.inline.fal name="itemImage{iteration.cycle}" label="Item {sectionItem.item.name} Image" multiple="true"
            maxItems="1" />
        <flux:field.text name="itemText{iteration.cycle}" enableRichText="0" label="Item {sectionItem.item.name} content"
        />
    </flux:form.sheet>
</f:for>
```
when I try to copy and paste content element, occurs the same behaviour described here #1214 
The new content does not contains images for additionalTabs, and there are duplicated images in the original content.
In the sys_file_reference table, the image records of the original content element  were copied but the column uid_foreign does not change (see #1214).

Flux: 8.2.1
TYPO3: 8.7.16

**Comment by kimchristiansen** [comment]
Maybe this helps you: https://github.com/FluidTYPO3/flux/issues/1493

**Comment by NamelessCoder** [comment]
@gianstraf In addition to info from #1493 your issue may indicate a TYPO3 core bug in cascade operations and/or detection of FAL relations when contained within FlexForm data sources. It probably won't be easy to track down an open issue, and a solution may be a long time in the future. This isn't exactly a frequent use case.

You may want to consider treating your Flux content elements as "structured data containers" where you use child content elements instead of section objects or other FlexForm structures, to facilitate tab items or other. There are two approaches:

1. Create the content type to render individual tab panels or other, so it spits out the right HTML that has to be placed inside your parent element's markup.
2. Or create content types that do not render anything but only contain data that you then read in the parent element (using `flux:content.get`).

Which one fits best will depend on your project and your editors. The first solution is more correct in that it's predictable how the output occurs - the second one is perhaps easier to control in terms of markup, because it allows you to ignore things like TS wrapping. That is however also the thing that makes it less predictable ;)
