### ISSUE TITLE
flux standalone flexform and l10nmgr: missing langDatabaseOverlay 

### ISSUE THREAD

**Issue by mithri** [FluidTYPO3/flux#1606]
Hi Claus,

in one project we migrated to the standalone flux content elements (without fluidcontent). After hat i've found out that the flexform from the custom CE are missing in the l10nmgr export. We (Jo Hasenau and i) found out that l10nmgr used a hardcoded check for the CType fluidcontent_content, which is no longer present. For all other CTypes the flexform needs "langDatabaseOverlay" in the XML.

Maybe someone can add the "langDatabaseOverlay " parameter for all generated flexforms? Further information for the feature in DCE: https://forge.typo3.org/issues/57900

For now i changed the check in the l10nmgr for our custom elements.

Thanks.
Tobias

**Comment by TimoWinkler** [comment]
Hi,

I looked into this issue since we want to use the extensions together and found out the necessary configurations for l10nmgr from the slack channels of both extensions. 
There is a small patch needed inside the Form::build() function in order to make the translation work:
`
$dataStructArray = [
            'meta' => [
                'langDisable' => $disableLocalisation,
                'langChildren' => $inheritLocalisation,
                'langDatabaseOverlay'=>1
            ],
        ];
`
Is this something to consider adding to flux? Since this is something an extension should be doing I am not sure if this is the right way.

Thanks,
Timo

**Comment by fnagel** [comment]
Hey guys, just want to let you know that we're using EXT:flux (migrated from EXT:fluidcontent) with EXT:l10nmgr without any issues. We're using l10nmgr successfully in order to export and import the complete site (default language is English, imported English, Spanish, French, Chinese). Note that the project only uses a EXT:flux powered Grid element -- everything else is custom tt_content elements and plugins. 

@mithri @TimoWinkler What exactly does not work for you? I'm a little confused why this works for me but not for you guys...

**Comment by rupasix** [comment]
>  We (Jo Hasenau and i) found out that l10nmgr used a hardcoded check for the CType fluidcontent_content, which is no longer present.

Maybe just that. Are you using ext:fluidcontent and ext:flux<9.0.0 combo? If so, then most likely all your Flux CE have CType="fluidcontent_content".

**Comment by TimoWinkler** [comment]
@fnagel what @rupasix said is correct. Our CType is not fluidcontent_content but instead extensionname_contentname and therefore l10nmgr cannot export these elements, because it only checks for fluidcontent_content and a meta tag for extensions like DCE.

Since I am working only since TYPO3 9.5 we did not migrate flux and therefore I cannot work around it otherwise.

**Comment by fnagel** [comment]
@rupasix No, we're using EXT:flux version 9.2 only. No more EXT:fluid_content. Our grid CEs have Ctype `extensionname_contentname` as @TimoWinkler mentioned. Using TYPO3 8.7.x

**Comment by TimoWinkler** [comment]
> Note that the project only uses a EXT:flux powered Grid element -- everything else is custom tt_content elements and plugins.

@fnagel do you only use EXT:flux to create custom grids? Or also for content elements that need translation. Since you never translate content stored in pi_flexform inside the content elment the first option will not produce errors. 
The second option where you need to translate custom content fields from inside flux elements EXT:l10nmgr 8.4 does not detect EXT:flux version 9.2 content fields defined inside pi_flexform. The elements are still detected and exported.

**Comment by fnagel** [comment]
> do you only use EXT:flux to create custom grids? Or also for content elements that need translation. 

Yes, only for Grid. Not for creating CEs.

> Since you never translate content stored in pi_flexform inside the content elment the first option will not produce errors.

Sounds reasonable.

**Comment by ManjushaC** [comment]
Hi @fnagel
@rupasix No, we're using EXT:flux version 9.2 only. No more EXT:fluid_content. Our grid CEs have Ctype extensionname_contentname as @TimoWinkler mentioned. Using TYPO3 8.7.x
How can you do this?
I am upgraded from Typo3 8.7.10 to Typo3 9.5.5. Typo3 8.7.10 uses Flux and FluidContent for grid CEs. But Typo3 9.5.5 do not support FluidContent. So my front and backend rendering in the page module does not working. Front showing No rendering definition. Could you please help to resolve it? Whether it can be implemented using only Flux?

**Comment by AlexanderKoe** [comment]
Is anybody working at this problem meanwhile?
For a short help, this fix helped me to do the Exports/Import:

Class "Model/Tools/Tools"
if ($dataStructArray['meta']['langDisable'] && $dataStructArray['meta']['langDatabaseOverlay'] == 1 || $table === 'tt_content' && preg_match('/flux_.*/', $row['CType'])/* === 'fluidcontent_content'*/) {

**Comment by Bunnyfield** [comment]
Latest L10nmgr versions have changed the if condition, since both parameters are actually specific to TemplaVoila and should not be considered in another context anymore, because they were deprecated and are not used by the core in version 7 to 9.

```
        $tvInstalled = ExtensionManagementUtility::isLoaded('templavoila');
...
                                    if (!$tvInstalled
                                        ||
                                        $dataStructArray['meta']['langDisable']
                                        && $dataStructArray['meta']['langDatabaseOverlay'] == 1
                                    ) {

```

**Comment by NamelessCoder** [comment]
Closing the issue as solved, albeit solved by l10nmgr and requiring no changes in Flux. Thanks @Bunnyfield for the fix and the information!
