### ISSUE TITLE
option listNestedContent not working since 9.0.x

### ISSUE THREAD

**Issue by kurtwithslc** [FluidTYPO3/flux#1609]
Since Version 9.x in List Module all content Elements are shown every time.
In older Versions, nesting was possible to enable / disable via EM.
Why this function is gone?

**Comment by NamelessCoder** [comment]
Since Flux 9.0 the elements are no longer in virtual columns and sorting them no longer causes the side effects that made it necessary to hide children by default. So this was removed, partly to get rid of an override that conflicted with a similar override from Gridelements.

In short the "feature" was only there to work around a limitation that no longer exists.
