### ISSUE TITLE
flux:content.render does not work with "Insert records" in multi language environment

### ISSUE THREAD

**Issue by fiedomedia** [FluidTYPO3/flux#1621]
My setup:
TYPO3: 8.7.19
flux: dev-development
fluidpages: 4.2.0

I have a default language (EN) and a translation (DE). I added a flux CE with 
`<flux:grid.column colPos="0" name="column" label="Container-Content">` 
and a default header CE. Now I want to insert the content from the default language within my german translation with the default "Insert record" CE.
Backend now looks like this:
![translated-content](https://user-images.githubusercontent.com/2965516/46019663-e7da9480-c0dc-11e8-97c0-3557a59528d8.PNG)

**Problem:** the german page shows the empty container CE but the child record "header" is missing.
Output is handled by
`<flux:content.render area="column" />`

I've debugged some code and found the executed sql query in TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::getQuery:
```sql
SELECT * 
FROM tt_content 
WHERE (tt_content.pid IN (1)) 
    AND (colPos= 7500) 
    AND (tt_content.sys_language_uid = 1) 
    AND ((tt_content.deleted = 0) AND (tt_content.t3ver_state <= 0) AND (tt_content.pid <> -1) AND (tt_content.hidden = 0) AND (tt_content.starttime <= 1537884420) AND ((tt_content.endtime = 0) OR (tt_content.endtime > 1537884420)) AND (((tt_content.fe_group = '') OR (tt_content.fe_group IS NULL) OR (tt_content.fe_group = '0') OR (FIND_IN_SET('0', tt_content.fe_group)) OR (FIND_IN_SET('-1', tt_content.fe_group))))) 
ORDER BY sorting ASC
```
pid and colPos looks good, but the sys_language_uid is the one of the german page, imho it should be sys_language_uid=0 of the original record language.

Any hints on this?

**Comment by NamelessCoder** [comment]
This behavior is controlled by TYPO3, not by Flux. The described behavior also matches what happens if you do this with any non-Flux content element in a page-level content column: while the backend does allow you to select a record that is in a different language than the translation, TYPO3 will internally try to resolve the translated version of the selected record and will not display the differently-languaged version.

It is possible that you can modify this behavior with things like language fallbacks - but this is outside the scope of Flux.
