### ISSUE TITLE
Configuration not overlayed (9.5.0)

### ISSUE THREAD

**Issue by kabaz** [FluidTYPO3/flux#1652]
PHP: 7.2.11 (Ubuntu 16.04)
Typo3: 9.5.0
Flux: 9.1.0
FluidStyledContent: 9.5.0

I want to update my extensions in a old installation (Typo3 7.6.x / Flux 7.4.0 / FluidStyledContent 7.6.0 / FluidContent 4.4.1) to the newest one. I have different extensions where I extend template files and their configuration in other extensions. There it was possible just to overlay the Configuration section e.g. with more fields or just overwrite fields. 

In the new version the Frontend section will be overwritten, but not the Configuration section.

I think the problem is, that the CType was the same in the past and is a different now.

For example I have this Content Template:
`<f:section name="Configuration">
	<flux:form id="simplecontent" label="Simple Content">
		<flux:form.option.group value="Test" />
		<flux:field.input name="additionalClass" label="Additional Classes" />
	</flux:form>
</f:section>`

And in another extension I want to overwrite it with for example a further field:
`<f:section name="Configuration">
	<flux:form id="simplecontent" label="Simple Content Extend">
		<flux:form.option.group value="Test" />
		<flux:field.input name="additionalClass" label="Additional Classes" />
		<flux:field.input name="additionalId" label="Additional Id" />
	</flux:form>
</f:section>`

(The reason I am doing this is because I am extending from extensions that are not from me)

Is this even possible anymore? I don't know if this is a bug or I there is another solution.
Thank you for your help!

**Comment by andigo-west** [comment]
Any Update  on this issue? I have the same problem like kabaz.

**Comment by NamelessCoder** [comment]
Since the original template is third-party code and you cannot use multiple `templateRootPaths` and the original template does not render a partial from within the Configuration section (you can use multiple `partialRootPaths`) you are left with one reasonable option:

Create a hook subscriber for Flux and use the `PROVIDER_EXTRACTED_OBJECT` hook. Create a class that implements the `HookSubscriberInterface` from Flux and implement the `trigger` method. The `trigger` method receives the name of the hook (value of constant in https://github.com/FluidTYPO3/flux/commit/1f76e8a60b99d7b93ee8752345573530d4b81d8e#diff-c83ba51878737bacf58618479e99b55aR43) and an array of parameters which depends on the hook - this particular method receives `['record' => ..., 'name' => ..., 'value' => $formInstance]` and the method must return the input array with exactly the same attributes.

This lets you modify `$hookArguments['value']` and do things like calling `->createField(Input::class, 'newfield', 'New field');`.

But a bug this is not ;) for further support about these hooks or using the PHP API for Flux forms please ask in the Slack channel or on Stackoverflow (tag with `typo3` and `flux`).
