### ISSUE TITLE
Localize Link not visible : Flux : 9.1.0

### ISSUE THREAD

**Issue by robsonrobi** [FluidTYPO3/flux#1655]
Using the Reference (Connected Mode). 
Once a FAL image is localized it exists in the localized language. Thats good.
But if i change the image in the parent language and switch to the localized language no localize record buttons are visible. even if i delete the first localized image, the button is missing:

I tried every setting but without luck.

`<flux:field.inline.fal name="file" allowedExtensions="jpg,jpeg,png,svg" enabledControls="{localize: 'TRUE'}"  localizeChildrenAtParentLocalization="TRUE" showPossibleLocalizationRecords="TRUE" showRemovedLocalizationRecords="TRUE" showAllLocalizationLink="1" showSynchronizationLink="TRUE" label="Choose Image" maxItems="1" localizationMode="select"/>`

Can someone please help ?

**Comment by ikonplant** [comment]
Unfortunately I can confirm this issue. i am also very interested to get a proper solution.
TYPO3 9.5.7, Flux 9.2.0

**Comment by hm-tim** [comment]
Issue is also present when using TYPO3 8.7.27 and Flux 9.2.0.

**Comment by NamelessCoder** [comment]
The localization feature is broken on TYPO3 8.7 due to restrictions in the TYPO3 core API; restrictions that will not be removed since 8.7 is LTS and no longer subject to feature changes.

TYPO3 9.5 and above, however, will show the localize button and Flux 9.2 and above allows translating nested content through this button.
