### ISSUE TITLE
[BUG] Flux could not extract a Flux definition with <f:link.page >

### ISSUE THREAD

**Issue by mmarchand-emagineurs** [FluidTYPO3/flux#1657]
Hello, 

I encounter some problems with flux on a TYPO3 9.5 site.

When I try to access back-end, I get the following error : 
`Flux could not extract a Flux definition from "[myTemplatePath]". Check that the file exists and contains the necessary flux:form in the configured section "Configuration"`

After some search it seems that the `<f:link.page pageUid="{link}">{title}</f:link.page>` I have in my template lead to this error (If I remove it, or just remove the pageUid attribute it works).

Do you have an idea to what happens and how to fix it?

Regards,

**Comment by NamelessCoder** [comment]
@mmarchand-emagineurs If you placed this link outside of the `Main` section that might cause it to execute in backend. The syntax you used looks correct so this has to be because the link renders when it's not supposed to render.

You don't say if this is the case, but your Flux template files should as a rule of thumb always use a Layout and always contain at least `Configuration` and `Main` sections - and should not contain Fluid code outside of the sections (with the exception of namespace declarations and such).

**Comment by mmarchand-emagineurs** [comment]
Hello,

First of all, sorry for the late answer.

I wanna thank you for the solution you gave. Unfortunatly this don't work either.

When trying to see the detail of the exception thrown, it appears that  `Undeclared arguments passed to ViewHelper TYPO3\CMS\Fluid\ViewHelpers\Link\PageViewHelper: pageUid`  , so my problem wasn't because of Flux but because I use an "undeclared" argument.

I found this message very strange, so I made some search in the extensions of the project (It's not a project I made on my own, but one I retrieved from another web agency) and I found a well hide class named PageViewHelper.php with the same namespace than the one from Fluid, and in which most of the arguments was removed.

I deleted this stupid class and, magic, it works!

Sorry for this time loss,
Regards,

**Comment by NamelessCoder** [comment]
> Sorry for this time loss,

No worries - thank *you* for following up with a precise cause.

It can be a bit difficult to debug these things but one way to do it is to debug from inside the Fluid classes like ViewHelperResolver and TemplatePaths. There you can see which class, which file, which arguments etc. that get passed around between the various Fluid components.

In your case though it sounds like this was a replacement on class level using the same class name which makes it even harder to track because neither Fluid nor Flux would be able to tell the difference by looking at the class name. That's of course not your fault but if it is the case, that's a mistake from the agency that did the original override.
