### ISSUE TITLE
plugin.tx_xxx.forms.xxx.enabled = 0 doesn't work anymore with flux 9.1.0 and TYPO3 8.7

### ISSUE THREAD

**Issue by joneppie** [FluidTYPO3/flux#1658]
In a multidomain system with different layouts, it is not possible to hide the page layout and flux content element for other pages, which was previously possible with plugin.tx_xxx.forms.xxx.enabled = 0.

**Comment by joneppie** [comment]
For tt-content elements only ```TCEFORM.tt_content.CType.removeItems := addToList(....)``` seems to be a feasible way.

**Comment by NamelessCoder** [comment]
Multidomain sites are affected by https://github.com/FluidTYPO3/flux/issues/1671 which prevents TYPO3 from correctly reading TS on all but one domain root. This problem cannot be solved in Flux.

Next version of Flux provides a way to toggle individual page and content templates through the "Sites" module or site configuration files. However, this of course requires TYPO3 9.5 or above - since "Sites" are not available in TYPO3 8.7 or earlier.

PageTSconfig can still be used to control content type availability on all supported TYPO3 versions.
