### ISSUE TITLE
[BUG] <flux:form.data ... > Multilanguage

### ISSUE THREAD

**Issue by grimmcreative** [FluidTYPO3/flux#1661]
My
<flux:field.input ... /> 
values dont get rendered via
<flux:form.data table="pages" field="tx_fed_page_flexform" uid="{page.uid}" as="pageConfig">
in my Page Template.

**Comment by NamelessCoder** [comment]
This should be possible to fix using one of these two methods:

* Using `_LOCALIZED_UID` as `uid`: `<flux:form.data table="tt_content" uid="{record._LOCALIZED_UID}" field="pi_flexform" />`
* Or using the full record instead of `uid` as argument: `<flux:form.data table="tt_content" record="{record}" field="pi_flexform" />`
