### ISSUE TITLE
How to translate new tt_content elements of existing flux grid containers?

### ISSUE THREAD

**Issue by derhansen** [FluidTYPO3/flux#1662]
Im using the latest TER version (9.1.0) of ext:flux. In a project, I have a simple flux content element with exactly one `flux.grid.column`. I add the content element using the page module to the default language and insert one content element in the column. So far, so good.

Now I create a new translation of the page and translate the flux content element and its content using the page translate button like shown below

![image](https://user-images.githubusercontent.com/2629896/50834739-20813f80-1355-11e9-83f7-71f6828bc6c1.png)

Now I add a new element to the flux content element on the default language. 

![image](https://user-images.githubusercontent.com/2629896/50834826-5aeadc80-1355-11e9-9c77-340f242d5b74.png)

How is it possible to translate the new element to the 2nd language? I do not see any "translate button" somewhere. The only possibility to translate the new element to other languages seem to be to open the element and use the language field like shown below

![image](https://user-images.githubusercontent.com/2629896/50834929-9ab1c400-1355-11e9-9e8c-08a24ace9c93.png)

Is'nt there a more comfortable way to synchronize translations of new elements in existing grid containers?

**Comment by dschlobohm** [comment]
+1

**Comment by NamelessCoder** [comment]
In next Flux version this will be possible by clicking the "localize" button - however, this feature may not work in 8.7 due to differences in how the "localize" button conditions work.

In TYPO3v9 the "localize" button in the top of the column reads all possible records to check if a translation can be performed. This makes the button appear if a child content record (at any level) is not translated. Clicking the button then shows the child records because of the new override added in https://github.com/FluidTYPO3/flux/commit/ae671cc805f16bf43b90edd72cf367c875aef067.

Whereas in TYPO3v8 the "localize" button is in the bottom of a column and is rendered based on which elements were encountered by the PageLayoutView while rendering. This means v8 most likely will not be able to present such a button - and because of how the internals of PageLayoutView work, even our current override of this class would not be able to fill the required values without causing negative effects (rendering all child columns as actual page columns, not nested).

This may be the best we can do for the time being.
