### ISSUE TITLE
Page configuration is removed by Lowlevel FlexForm Cleaning

### ISSUE THREAD

**Issue by kraemer-igroup** [FluidTYPO3/flux#1666]
Hi,

since we added the cleanup:flexforms scheduler task the page configuration (tx_fed_page_flexform & tx_fed_page_flexform_sub) is resetted on every run. I also could reproduce this on a new installation:
- TYPO3 9.5.3
- Create provider extension with builder from GitHub (flux 9.1.0, fluidpages 4.3.0)
- Add form field to page configuration as described here: https://fluidtypo3.org/documentation/templating-manual/templating/creating-templates/page-template.html
- Set values for one ore more pages
- Run cleanup:flexforms scheduler task or on commandline (./typo3/sysext/core/bin/typo3 cleanup:flexforms)
- Page configuration is removed

This does not happen for configuration options in content elements.

Is anybody having the same issue?

**Comment by NamelessCoder** [comment]
Hi @kraemer-igroup,

Sorry for the very late reply - this problem is almost certainly caused by:

* TYPO3 not implementing the business logic required to resolve a dynamic data structure for FlexForm fields, and/or
* TYPO3 not providing the record to the business logic that resolves dynamic data structures

Unfortunately there is nothing we can do in Flux to prevent this. Only if TYPO3 correctly resolves the dynamic data structure which implies it must both use the business logic that resolves the data structure *and* provide the relevant record will Flux be able to deliver the right data structure, and only if Flux can deliver the right data structure will TYPO3 know which fields to keep and which to discard. So Flux very much depends on TYPO3 to call the necessary methods and provide the full page record - or the data structure is technically unknown (TYPO3 perceives data structure to contain no fields and will therefore clean all values).

If this is still an issue for you please report to forge.typo3.org for further investigation.
