### ISSUE TITLE
flux:grid no collapse button in backend page view

### ISSUE THREAD

**Issue by kevinlieser** [FluidTYPO3/flux#1667]
Since an TYPO3 upgrade and an upgrade from flux 7.4.0 to 9.1.0 the backend collapse button ism missing to collapse the content of grid objects created with flux:grid.

Any possibility to get this collapse button back for better overview?

**Comment by Geddo** [comment]
+1

**Comment by rangerluke** [comment]
This is an Core-Issue, because the cache method to get cached code does not return "null" anymore, rather an empty string or false.
So in the class ContentIcon the method addSubIcon has to be changed in line 108 to
`if ($cachedIconIdentifier && $cachedIconIdentifier !== null) {`
than the collapse icon will be shown

**Comment by NamelessCoder** [comment]
> This is an Core-Issue, because the cache method to get cached code does not return "null" anymore, rather an empty string or false.

Do you have a link to a commit or forge issue where this change was implemented? I'm not sure the return type of cache frontends has actually changed... and please note that caching an empty string in Flux means there's no collapse button to render.

Duplicates https://github.com/FluidTYPO3/flux/issues/1616. Please continue the discussion there :)
