### ISSUE TITLE
Saving Elements in flux columns creates wrong colpos values

### ISSUE THREAD

**Issue by hm-tim** [FluidTYPO3/flux#1669]
Hey everyone

I encountered a problem with flux powered content elements, nested in flux grid elements.

For clarity I created this very simple element

      
    <f:layout name="Content" />  
      
    <f:section name="Configuration">  
	     <flux:form id="hm_gridtest" description="Testing Flux Grid" label="Grid Test">  
		     <flux:grid>  
			     <flux:grid.row>  
				     <flux:grid.column colPos="77" label="Testcontainer" name="testcontainer">  
				      
				     </flux:grid.column>  
			     </flux:grid.row>  
		     </flux:grid>  
	     </flux:form>  
    </f:section>  
      
    <f:section name="Preview"></f:section>  
      
    <f:section name="Main"></f:section>

Now if i create an Element inside this container it does not set the correct colpos (instead, the colpos value is `1`). 

If i use drag&drop to place it into the container, the colpos is set correctly (but it gets overwritten with `1` if i ever save the nested element)

Also, when editing the element placed inside the container the value in the colpos field is already wrong (while the value in the tt_content is still correct)

![image](https://user-images.githubusercontent.com/8760110/52422166-d3c88a00-2af5-11e9-96d9-e360330b1d7a.png)

I'm using the following TYPO3 and Extension versions:
TYPO3 9.5.4
fluidpages 4.3.0 (latest from github)
flux 9.1.0 (latest from github)
vhs 5.1.1 

Any ideas on why that happens?

**Comment by NamelessCoder** [comment]
Hi @hm-tim - do you have other special content rendering extensions installed? It sounds like there may be a hook that writes the colPos value incorrectly - possibly because it matches some magic value.

Some hints to perhaps work around:

* If you have other extensions installed try temporarily disabling
* If you wrote any hooks for processing content, make sure they don't touch colPos
* Use a different colPos value (within range 0 to 99)
* Check to see if any other extensions are perhaps setting `itemsProcFunc` for `tt_content.colPos` in TCA.
* Check if any other extensions are XCLASS'ing PageLayoutView

Then there is a single thing that's semantically incorrect but in normal cases don't cause problems. Your form ID contains an underscore which may cause TYPO3 to reference it as `hmgridtest` instead which could cause a disconnect that makes parent's colPos values unavailable to the child. But I think the cause can be found in an incompatible extension or hook that messes with the logic Flux depends on.

**Comment by hm-tim** [comment]
Hi @NamelessCoder 

Sorry for bothering you - the error was indeed not really flux related. I found the problem in my PageTS. 
I had `TCEFORM.tt_content.colPos.keepItems = ` set with some values, obviously the colpos values generated by flux were not "allowed". 

I do not really need that setting, so I removed it and my Elements are working again. 
Thank you!

**Comment by NamelessCoder** [comment]
Thanks a lot for updating and reporting precisely what caused the issue! This will help other users that may run into the same problem. Good to hear you solved it :)

**Comment by manikandankasi** [comment]
Oops, an error occurred!
An exception occurred while executing 'SELECT * FROM `tt_content` WHERE (`sys_language_uid` IN (0, -1) AND colPos IN () ) AND (`tt_content`.`pid` = ?) AND ((`tt_content`.`deleted` = 0) AND ((`tt_content`.`t3ver_wsid` = 0) OR (`tt_content`.`t3ver_state` <= 0))) ORDER BY `sorting` ASC LIMIT 100' with params [1]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') ) AND (`tt_content`.`pid` = ?) AND ((`tt_content`.`deleted` = 0) AND ((`tt_con' at line 1




I was trying to create content element with typo3 and created grid but the backend shows this error

**Comment by muh-nr** [comment]
The same form me.
