### ISSUE TITLE
[FEATURE] Recursion protection in backend and frontend

### ISSUE THREAD

**Issue by svewap** [FluidTYPO3/flux#1673]
Hi! I sometimes have projects where editors have created incorrect references with drag and drop on nested multi column objects. A general danger with nested objects. This results in both the backend and in the frontend infinite recursion that must be intercepted. Then you have the chance to correct it in the database. This therefore serves for "system hardening".

Here's a simple suggestion on how to catch it in the backend:
https://github.com/svewap/flux/commit/aa7902d688cdad05825efe82dbd1905f55acefd8

What do you think?

**Comment by NamelessCoder** [comment]
Hi @svewap - `renderGrid` triggers in the backend and shouldn't use TSFE but I think your explanation points to another issue. There should be guards in Flux that prevent editors from drag-n-dropping an element into itself (with a FlashMessage warning actually saying you can't copy self into self). It also shouldn't be possible in terms of DOM to drag-n-drop a parent into a dropzone it itself contains, since you're grabbing the entire DOM node collection including the child dropzones.

We shouldn't error out if something an editor did causes recursion - instead we want to prevent that case from happening. So I'm interested in finding out exactly how it's possible via BE (drag-n-drop *or* cut-and-paste, both should be guarded) to create a recursive structure?

**Comment by NamelessCoder** [comment]
Recursion prevented via https://github.com/FluidTYPO3/flux/commit/7682f8024df908cb0cd0eff66cc32ae8dee5ebf2
