### ISSUE TITLE
Problem with duplicate content after migrating from flux 7.4.0 to 9.1.0

### ISSUE THREAD

**Issue by dkm-bb** [FluidTYPO3/flux#1686]
Hi

I have upgraded a site from TYPO3 7 to 9 and thereby also flux from 7.4.0 to 9.1.0. I changed the CType of all fluidcontent elements from fluidcontent to something like sitetemplates_name. This worked out fine. I do have a problem with a special multicolumn container element though.

```
<f:layout name="Content" />

<f:section name="Configuration">
    <flux:form id="grid" options="{group: 'FCE'}">

            <flux:field.input name="wrapper.class" label="Wrapper classes (container)" />
            <flux:field.input name="row.class" label="Wrapper classes (række)" />
            <flux:field.input name="headline" />
            <flux:field.select name="margin" items="{0:0, 5:5, 10:10, 20:20}" />

            <flux:form.section name="columns">
                <flux:form.object name="column" label="Kolonne">
                    <flux:field.select name="class" items="span1, span2, span3, span4, span5, span6, span7, span8, span9, span10, span11, span12" />
                    <flux:field.input name="additionalClass" label="Ekstra kolonne class" />
                </flux:form.object>
            </flux:form.section>
    </flux:form>

    <flux:grid>
        <flux:grid.row>
            <f:for each="{columns}" as="sectionObject" iteration="iteration">
                <v:variable.set name="width" value="{sectionObject.column.class -> v:format.substring(start: 4)}" />
                <v:variable.set name="percent" value="{width  -> v:math.division(b: 12) -> v:math.product(b: 100) -> v:math.round(decimals: 2)}" />
                <flux:grid.column style="width: {percent}%;" name="column{iteration.cycle}" label="{percent}%" colPos="" />
            </f:for>
        </flux:grid.row>
    </flux:grid>

</f:section>

<f:section name="Main">
    <div class="container {wrapper.class}">
        <div class="row {row.class}">
            <f:if condition="{headline}">
                <div class="col-md-12"><h2 style="margin-bottom: {margin}px">{headline}</h2></div>
            </f:if>
            <f:for each="{columns}" as="sectionObject" iteration="iteration">
                <div class="col-md-{sectionObject.column.class -> v:format.substring(start: 4)}{f:if(condition: sectionObject.column.additionalClass, then: ' {sectionObject.column.additionalClass}')}">
                        <flux:content.render area="column{iteration.cycle}" />
                </div>
            </f:for>
        </div>
    </div>
</f:section>

<f:section name="Preview">
    <f:if condition="{headline}"><h2>{headline}</h2></f:if>
</f:section>
```
First of all, I added the colPos="" to the flux:grid.column, since it is now needed. All the columns in the backend appeared empty, so I ran the update script from EM. It almost worked, but for some reason, the elements appear in all columns. If I have an element with 2 columns and one item in each, these items are present i both columns. This is also the case in the frontend.

The tx_flux_column and tx_flux_parent records in the db seems to be alright. The colPos is set to the uid of the parent element appended with 2 zeros.

Any idea how I solve this?

**Comment by NamelessCoder** [comment]
Hi Brian,

> colPos="" 

There has to be a valid integer value in this attribute, between `0` and `99`.

> style="width: {percent}%;" 

This one is no longer supported (but not removed) - the overrides that rendered this attribute are no longer in Flux and we use a more core-appropriate method. You can however use the `rowspan` and `colspan` attributes to create a virtual total column count of 12 and make each column use a portion of those 12 virtual columns, e.g. `colspan="3"` when you have 4 columns.

There is an improved solution now for section-objects-as-grid which you can probably use:

```
        $this->registerArgument(
            'gridMode',
            'string',
            'Defines how section objects which are marked as content containers, get rendered as a grid. Valid ' .
            'values are either "rows" or "columns". Default is to render as rows.',
            false,
            Section::GRID_MODE_ROWS
        );
```

If you use this argument on your `flux:form.section` you can automatically represent each section object as a grid column or row. The object will then also have a proper ID and colPos value that you can use when you render the content elements based on the section objects. When you use this feature you do not have to define the `flux:grid` at all (but if you do, any rows/columns you put there, will be _appended_ to the ones from the section objects).

> The tx_flux_column and tx_flux_parent records

These fields are no longer being used (except for migrating to the new strategy). The new strategy is to use `colPos` and calculate parent record UID and local column number based on a value like `12303` meaning `colPos="3"` inside parent UID `123`. The virtual colPos is generated by `($parentUid * 100) + $localColPos` which is then reversible when you need to select all children of a given parent (then you select a colPos range), or all children in a specific column in a parent (specific colPos value). So all of your records were migrated to a single column and all of your columns have the same colPos and will render all elements.

You may need to null the `tx_flux_migrated_version` field in DB and re-run the upgrade script after you've either switched to section-as-grid or put a proper `colPos` value on all columns that's unique. I'd recommend the section-as-grid feature because it gets around some limitations like column numbers not being unique when you move a section object up/down. Using the feature, the child content follows the section object when moved.

**Comment by dkm-bb** [comment]
Thanks for your input. I have sorted out my problems :)
