### ISSUE TITLE
Creating a simple Flux content element leads to "Could not analyse class: "Fmd\MyExt\Controller\ContentController" Exception in Flux 9.2.0

### ISSUE THREAD

**Issue by AlexanderKoe** [FluidTYPO3/flux#1688]
Created a simple Flux Content Element (just 1 test field), leads to Exception
"Could not analyse class: "Fmd\MyExtensoin\Controller\ContentController" in the Frontend.
However there is no "ContentController" in my extension and never has been in any Flux provider extension I made before (never used flux > 9) - is ist obligational now? Creating an empty ContentController with that namespace does not help either.

Using TYPO3 8.7.24 with

fluidpages | 5.0.0
flux | 9.2.0
vhs | 5.2.0

**Comment by NamelessCoder** [comment]
If this concerns the record-based content types then the following applies:

* If you have your own provider extension to give Layouts etc. then use the Vendor.ExtensionName identifier of your extension.
* If you do not have your own extension, use FluidTYPO3.Flux but then you don't have access to Layouts and Partials.
* Having a provider extension for this is *extremely* recommended even if you use record-based content types.
* When you use record-based content types the controller is indeed mandatory (but you can use the Flux ContentController by using that extension identity if you don't have your provider extension and can't create a class there).

**Comment by NamelessCoder** [comment]
Leaving the issue open to consider if controller can be made optional / feedback should be improved to report inability to resolve controller class.

**Comment by AlexanderKoe** [comment]
thanks for your fast answer. Yes I have provider extension for this and I (think I) use record-based content types (are there non-record-based content types? never heard of it before).  In detail my content types are stored in tt_content with CType "ExtensionName_ContentElementID" if that helps to answer the question. At the moment my own ContentController now found by class autoloader because I made a typo with namespace vendor, but is still obligational not mandatory.
Question: where to use the Vendor.ExtensionName? Here I did:
\FluidTYPO3\Flux\Core::registerProviderExtensionKey('FMD.Bootstrap4_template', 'Page');
\FluidTYPO3\Flux\Core::registerProviderExtensionKey('FMD.Bootstrap4_template', 'Content');

**Comment by NamelessCoder** [comment]
Record-based content types are system records you define in pid zero (like site languages) and allow you to configure a Flux-based CType that can be used when creating content elements.

So it appears you are perhaps not using that but rather use template files. This should mean that the controller is *not mandatory*.

If your extension key (the folder name) is `bootstrap4_template` and you chose `FMD` as vendor name, then your complete extension identity is `FMD.Bootstrap4Template` but it is historically a problem if you use this naming (something123) as extension name. Internally, your extension key *should* then be `bootstrap_4_theme` but because of how conversion happens, `4` cannot be uppercased which means that in terms of Extbase classes, `boostrap4_theme` and `bootstrap_4_theme` as extension keys actually cause the same class names.

I'd highly recommend:

1. Choosing a different extension key that does not include numbers, for example `bootstrap_template`.
2. Changing your `FMD.Bootstrap4_template` afterwards to something like `FMD.BootstrapTemplate`.
3. Ideally, pick an extension key that has neither numbers nor underscores in it (or know how to handle this and when to pass `UpperCamelCase` or `lowercase_underscored` formats).

Flux will always need the `Vendor.UpperCamelCase` format in anything named "extension name" and the `lowercase_underscored` format in anything named "extension key". So the name is the full identity and the key is the extension's folder name.

**Comment by AlexanderKoe** [comment]
thanks. this helped for me.
