### ISSUE TITLE
The default controller for extension X and plugin Y can not be determined.

### ISSUE THREAD

**Issue by apiening** [FluidTYPO3/flux#1694]
I'm using an extension with flux content elements (based on https://github.com/bootstraptheme-for-typo3/fluidbootstraptheme with some modifications on the CE definitions so that they work on T3 9.5).

Every now and then I get errors like

> The default controller for extension "Fluidbootstraptheme" and plugin "Twocolumn" can not be determined.

When I clear the cache in the T3 backend and reload the frontend, the error disappears. But after a day or two the error happens again for every CE rendered by this extension which shuts down the website entirely until I clear the cache again.

Any idea why this is?
If this is a configuration issue I wonder why it works in the first place and then all the sudden stops working without anything being touched.

**Comment by NamelessCoder** [comment]
@apiening I don't think this is Flux-related; when Flux is used you don't see the provider extension identity as context for the plugin - the plugin is Flux context, but the plugin renders a sub-context that then has the right identity.

In your case the warning looks like it is about a custom registered plugin which *should* be registered in `ext_localconf.php` and `ext_tables.php`. The deeper cause of the problem is probably that the plugin is registered in a file that isn't always included, and one of the caches involved in storing the registration expires before the other which doesn't cause the file to be re-included.

**Comment by apiening** [comment]
Thank you @NamelessCoder,
your explanation does make sense to me.
There is a line in `ext_tables.php` to register the plugin:

> \FluidTYPO3\Flux\Core::registerProviderExtensionKey('FluidBT.Fluidbootstraptheme', 'Content');

however there was no `ext_localconf.php` shipped with the initial extension.
I have created this file and added the same registration code in there.

I'll monitor if the problem pops up again and provide feedback.

Thank you!

**Comment by NamelessCoder** [comment]
That's exactly the reason, @apiening - good find. This line goes in `ext_localconf.php` always - the instruction to put it in the other file will no longer work, since the registration generates more than TCA and must not expire along with the TCA cache. I expect you won't see the problem again :)
