### ISSUE TITLE
Multiple page template locations with a provider extesion

### ISSUE THREAD

**Issue by fikretyayla** [FluidTYPO3/flux#1695]
how can I specify multiple page template locations with a provider extesion?

TYPO3 9.5.x LTS
flux 9.2.0
fluidpages 5.2.0

I have a provider extension "my_provider" and another "my_provider_extended". 
I register my provider extension in "my_provider", where I save the page templates.

```
\FluidTYPO3\Flux\Core::registerProviderExtensionKey('Vendor.MyProvider', 'Page');
\FluidTYPO3\Flux\Core::registerProviderExtensionKey('Vendor.MyProvider', 'Content');
```

Now I want to extend my page templates but not in the "my_provider" extension but in "my_provider_extended". 
The TypoScript configuration looks like this:

```
plugin.tx_myprovider.view {
    templateRootPath {
        0 = EXT:my_provider/Resources/Private/Templates/
	1 = EXT:my_provider_extended/Resources/Private/Templates/
    }
    partialRootPath {
        0 = EXT:my_provider/Resources/Private/Partials/
	1 = EXT:my_provider_extended/Resources/Private/Partials/
    }
    layoutRootPath {
	0 = EXT:my_provider/Resources/Private/Layouts/
	1 = EXT:my_provider_extended/Resources/Private/Layouts/
    }
}
```

If I override an existing page template from "my_provider" in the "my_provider_extended" everything is fine.

But if I add a new page template in "my_provider_extended", it will not be recognized.

The background is that I use "my_provider" extension in several projects and update it regularly. 
It is the basis in all my projects, which is why the extension has to be the same everywhere. Imagine it like EXT:news. 
The "my_provider_extended" extension is intended for project specific changes and overwrites, if necessary, page templates.

Now I need a special page template that I do not need anywhere else.

is it possible to save more pages templates in other locations and use it with a Provier Extension? What needs to be done.

**Comment by MediKathi** [comment]
Hello there,

I have the same setup as you and have very similar issues with this behavior of Flux and Fluidpages see https://github.com/FluidTYPO3/fluidpages/issues/389
Everthing worked as expectes with Typo3 8.7 and Flux 8.2

But for Typo3 9.5 and Flux 9.2 I needed to modify the code of `FluidTYPO3\Flux\Controller\ContentController` (Yes the flux extension)
 and `FluidTYPO3\Fluidpages\Controller\PageController` (Yes the fluidpages extension)

I just added this to both extensions
```php
    protected function initializeView(\TYPO3\CMS\Extbase\Mvc\View\ViewInterface $view)
    {
    	parent::initializeView($view);
        $record = $this->getRecord();
        $extensionKey = \FluidTYPO3\Flux\Utility\ExtensionNamingUtility::getExtensionKey($this->provider->getControllerExtensionKeyFromRecord($record));
        /** @var RenderingContextInterface $renderingContext */
        $renderingContext = $view->getRenderingContext();
        $renderingContext->getTemplatePaths()->fillDefaultsByPackageName($extensionKey);
        $renderingContext->getTemplatePaths()->setPartialRootPaths(
        	[
        		\TYPO3\CMS\Core\Utility\GeneralUtility::getFileAbsFileName('typo3conf/ext/myExt/Resources/Private/Partials/'),
        		\TYPO3\CMS\Core\Utility\GeneralUtility::getFileAbsFileName('typo3conf/ext/'.$extensionKey.'/Resources/Private/Partials/')
        	]
        );
    }
```
and the behavior is like expected again.

But I don't think this is how it should work.

**Comment by NamelessCoder** [comment]
@fikretyayla There's a very long explanation but what it boils down to, is that in some contexts (e.g. most backend contexts) TYPO3 is unable to correctly determine the current page UID and therefore unable to resolve the correct TypoScript from Extbase's ConfigurationManager. In some contexts (e.g. initialisation) the page UID also has to be assumed, or a page record has to be emulated.

This in turn means that, based on the order of your root TS templates, you may not get the TS you expect (TYPO3 may use a different root TS template that's outside the current page tree location; if that TS template was created first).

Until TYPO3 corrects this unfortunate behavior (especially in BE - FE is pretty much unaffected since it has only one way to determine the page UID) Flux cannot support the multiple template paths.

There is therefore only one way to achieve your goal:

* Make your extended extension a provider extension just like the base one.
* When you need the overridden template, select it instead of the original in page properties.
* Avoid rendering partials in the Configuration section (using a Layout should work).
* Use the normal TS to add additional partial etc. root paths - but set the TS for your extended extension, not the base one.

This should make the BE operable and read Flux forms from the right template, and should configure FE to use the base extension's paths as defaults. Basically: your extended provided needs to be the entry point for that single page template.

I know this isn't ideal but it's the best we can currently get.

**Comment by NamelessCoder** [comment]
Side note: for your TS to work correctly in BE you should duplicate the "plugin.tx_xyz" configuration to "module.tx_xyz".
