### ISSUE TITLE
PageController in own provider extension does not work

### ISSUE THREAD

**Issue by tsurfer84** [FluidTYPO3/flux#1702]
Hey Folks,

I have a problem with a provider EXT and flux.
I use in my provider EXT ContentController and PageController classes. But only PageController works fine. When I use an own flux-generated Content Element, I get in the frontend the error 

> Content Element with uid "1352" and type "nh3provider_xyz" has no rendering definition!

Strange thing is, I only get this error when I am not logged in the backend. When I am logged into the backend, I don't get the error und the content elemens shows correctly.

I guess, flux takes control over ContentController anyway I registered it in ey provider EXT in ext_tables.php:

```
\FluidTYPO3\Flux\Core::registerProviderExtensionKey('NH3.' .$_EXTKEY, 'Page');
\FluidTYPO3\Flux\Core::registerProviderExtensionKey('NH3.' .$_EXTKEY, 'Content');
```

ContentController looks like:
```
namespace NH3\Nh3provider\Controller;
use FluidTYPO3\Flux\Controller\AbstractFluxController;
class ContentController extends AbstractFluxController
{
}

```
typo3 autoload classmapping also points to correct folders:

```
    'NH3\\Nh3provider\\Controller\\ContentController' => $typo3InstallDir . 'typo3conf/ext/nh3provider/Classes/Controller/ContentController.php',
    'NH3\\Nh3provider\\Controller\\PageController' => $typo3InstallDir . 'typo3conf/ext/nh3provider/Classes/Controller/PageController.php',
```

I use:
- typo3 9.5.7
- flux 9.2.0
- fluidpages 5.0
- vhs 5.2.0

**Comment by NamelessCoder** [comment]
Hi @tsurfer84,

`\FluidTYPO3\Flux\Core::registerProviderExtensionKey('NH3.' .$_EXTKEY, 'Page');`

This is a very common pitfall. The short version is: never use `$_EXTKEY`, not even if combined with vendor name. The reason is that `$_EXTKEY` contains the `lowercase_underscored` extension key and the method you are calling requires the `Vendor.ExtensionName` format.

Generally speaking it's wise to avoid `$_EXTKEY` completely. Your extension key doesn't change so you do not need a variable - just use the hardcoded extension name/key in the correct format, also for other non-Flux methods or configuration you call/set in your `ext_*` files.
