### ISSUE TITLE
Item object structure changed for flexform.field.select using PHP 7.3.9

### ISSUE THREAD

**Issue by muh-nr** [FluidTYPO3/flux#1717]
Using PHP 7.3.9, TYPO3 9.5.9 and Flux 9.2 the object structure for flexform.field.select items seems to be changed.

Instead of:
`0:{0:'LLL:EXT:my_ext/Resources/Private/Language/locallang.xlf:flux.foo',1:'foo'}`

it's changed to simply key:value (or better value:label):
`'foo':'LLL:EXT:my_ext/Resources/Private/Language/locallang.xlf:flux.foo'`

If you can confirm that, please update the documentation.

Thanks

**Comment by NamelessCoder** [comment]
Both notations can be used - the one documented is the explicit one that also works as pure TCA, and which supports an icon name as third array position.

**Comment by NamelessCoder** [comment]
Hmm - did you update anything other than just PHP? To my knowledge there should be no changes in PHP that would cause an array to be flipped (it'd be pretty nasty if that's the case).

**Comment by aseemann** [comment]
Maybe this is related to https://github.com/TYPO3/Fluid/issues/449. 

We have noticed some more issues after updating to PHP 7.3.9. The BackenUriViewHelper don't works in inline style, the pagination was also broken and some other ViewHelpers got strings instead of arrays as arguments and throws exceptions. 

So I'm not sure if this should be investigated further. If there is a Solution for #449 maybe this behaviour will be fixed too.

**Comment by NamelessCoder** [comment]
The PCRE issue (thanks @aseemann for relating it) should, if anything, cause items to not be included (you might get a PHP warning and NULL or a string instead of array). But it is worth checking your PCRE version against the affected ones mentioned in that issue!

**Comment by NamelessCoder** [comment]
Closing this issue since if there are problems with PCRE this is not related to Flux as such.

Please note that `'foo':'LLL:EXT:my_ext/Resources/Private/Language/locallang.xlf:flux.foo'` should be written as `foo:'LLL:EXT:my_ext/Resources/Private/Language/locallang.xlf:flux.foo'` (unquoted array key name).
