### ISSUE TITLE
RTE CKEditor additional allowed attributes

### ISSUE THREAD

**Issue by dkd-thoma** [FluidTYPO3/flux#1728]
Hi,

Flux v9.2.0/stable
TYPO3 v8.7

i use instead of the default rte YAML an own configuration. My changes are considered in RTE but additional attributes (configured in Processing.yaml) are not considered. The Default attributes 
`class, id, title, dir, lang, xml:lang, itemscope, itemtype, itemprop` are considered and are in the source code of RTE in TYPO3 BackEnd. My additional attributes `data-placement, data-toggle, data-trigger, data-content` are considered in RTE in BE but after saving the attributes within the tag, the complete tag is deleted.

**Comment by NamelessCoder** [comment]
Hi @dkd-thoma,

I'm pretty sure this isn't related to Flux - Flux will only take the name of the RTE configuration, everything else is handled by the TYPO3 core itself.

Flux also does not post-process RTE fields neither when saving nor when displaying them.

**Comment by dkd-thoma** [comment]
Hi @NamelessCoder,

thank you for your fast answer!
But this issue only occurs on a Content Element with RTE defined in Flux.
Content Elements where RTE is not defined in Flux, my configuration works and is considered.

best regards
Fabio Thoma

**Comment by NamelessCoder** [comment]
I suspect you will find that the other field is not within a FlexForm - and that this is the determining factor in whether your RTE works or not ;)

**Comment by grischpel** [comment]
I dont think so @NamelessCoder because i did it all time in typo3 9.x.x but in typo3 10 it stops working see #1808

**Comment by NamelessCoder** [comment]
@grischpel The issue you linked to describes precisely what I mentioned; that the difference is that the field that doesn't work is inside a FlexForm (which is also what Flux generates). I think the problem isn't related to Flux but instead is related to the context in which the field appears - since TYPO3 handles fields differently when they're in a FlexForm vs. when they're in root-level TCA fields. Yes, this may have changed in TYPO3v9 to v10 - but if the same config worked in v9 and the config approach wasn't changed, then I have to suspect that the cause is this difference in context and not a problem caused by Flux.

**Comment by grischpel** [comment]
@NamelessCoder but what is the woraround for this then? :-(

**Comment by stosef** [comment]
Maybe it is related to https://forge.typo3.org/issues/88858

**Comment by grischpel** [comment]
> Maybe it is related to https://forge.typo3.org/issues/88858

No, sorry, i already tried this
