### ISSUE TITLE
flux 9.3.0 installation error _construct

### ISSUE THREAD

**Issue by kurtwithslc** [FluidTYPO3/flux#1736]
after updating flux from 9.2.0 to 9.3.0 backend crashes with this error:
(1/1) TypeError
Argument 3 passed to FluidTYPO3\Flux\Content\TypeDefinition\FluidFileBased\DropInContentTypeDefinition::__construct() must be of the type string, boolean given, called in /html/typo3/typo3conf/ext/flux/Classes/Content/TypeDefinition/FluidFileBased/DropInContentTypeDefinition.php on line 89

**Comment by NamelessCoder** [comment]
Solved by 9.3.1 release that was created today.

**Comment by kurtwithslc** [comment]
sorry, same error with 9.3.1 except that calling line is now 95 (was 89)

TypeError
Argument 3 passed to FluidTYPO3\Flux\Content\TypeDefinition\FluidFileBased\DropInContentTypeDefinition::__construct() must be of the type string, boolean given, called in /html/typo3/typo3conf/ext/flux/Classes/Content/TypeDefinition/FluidFileBased/DropInContentTypeDefinition.php on line 95

**Comment by NamelessCoder** [comment]
Are you using some symlink setup for your "public" folder, or can you infer any other reason why the base path (public folder) might be shorter than the template file path?

**Comment by kurtwithslc** [comment]
flux 9.3.x creates the public folder during update from 9.2.0. I have no symlink.
I disabled using plug and play (cause i have my templates in my own extension), then error is gone

**Comment by NamelessCoder** [comment]
Could you do me a favor and dump in https://github.com/FluidTYPO3/flux/blob/development/Classes/Content/TypeDefinition/FluidFileBased/DropInContentTypeDefinition.php#L91 what `$basePath` is set to, and which value of `$templateFile` you get when the error happens?

**Comment by kurtwithslc** [comment]
if i switch on Plug & Play i got:
$basePath = /home/www/pxxxxxx/html/typo3/design/
$templateFile = /html/typo3/design/Templates/Content/Standard.html
and error is thrown

**Comment by NamelessCoder** [comment]
@kurtwithslc I've set Flux to ignore drop-in templates in case the public folder path resolves to an unexpected value - I'm still not sure why it does that on your setup, but in any case, these unexpected paths would not be compatible with the drop-in template logic.

The problem is ignored silently; keep this in mind if at some point you wish to start using drop-in templates. If and when that time comes you'll have to figure out why the public path of your site has one prefix and the "real" path of template files has another prefix (symlinks or ENV configuration that sets the public folder path to an unexpected value would be my best guesses).
