### ISSUE TITLE
Upgrade from 9.2 to 9.3.2 -> DB errors

### ISSUE THREAD

**Issue by rupasix** [FluidTYPO3/flux#1740]
I wanted to upgrade Flux. Failed due to non-existent db columns. Ext: fluidpages is not used in this installation.

![image](https://user-images.githubusercontent.com/9860558/74147487-9f554580-4c03-11ea-88b9-25e40ee94caf.png)

![image](https://user-images.githubusercontent.com/9860558/74147665-ffe48280-4c03-11ea-96fe-935824f46099.png)

I had to go to installtool and update the database structure. After that everything seems to work fine.

**Comment by fnagel** [comment]
Same issue here using an TYPO3 8.7.30. Needed to downgrade using `"fluidtypo3/flux": "9.2.*"` to make my instance work again.

**Comment by NamelessCoder** [comment]
If you can use CLI, dispatch `typo3 database:updateschema`, or use the install tool's "Maintenance -> Compare Database" function to perform the schema updates. I think if you do `composer update` this doesn't happen automatically (which is unfortunate).

**Comment by rupasix** [comment]
We are using ext manager for that project and yes, compare database from installtool helped me with this issue.

**Comment by mkrappitz** [comment]
We have the same, when upgrading flux 9.2 to 9.3.2 in Extension Manager in no composer mode, crashing the TYPO3 installation. Normally the Extension Manager always creates new columns and tables on the fly when upgrading an extension so this error normally never happens and it should not be necessary to manually do a db compare after and extension upgrade to bring a TYPO3 installation back to life.

**Comment by NamelessCoder** [comment]
I realise this can be quite annoying, but there is currently no way around *sometimes* needing to use the install tool to update database schemas after an extension update. Main problem is that a plain composer update doesn't trigger any database schema updates and they do not happen on the fly in the backend. True, the extension manager can perform them, but this only happens when you deactivate/reactivate the extension - it does not trigger when you do a composer update.

The problem is further expressed when the missing fields are intended to be part of the site rootline - here, TYPO3 will assume that the schema is updated and does not catch any errors about missing columns in the database. Therefore an error gets thrown outside of Flux's context, making it impossible to catch and report as a more friendly error (e.g. FlashMessage). One of the cases which will do that is when TYPO3 attempts to resolve a Site, which causes a lookup of the page root line, which then fails if the database schema is not up-to-date.

The same would happen for other extensions which add fields to the root line.

One way to work around this is to deactivate the extension in Extension Manager before doing the composer update, then activating it after the update is done. This causes Extension Manager to perform the database comparison and update the schema if required. Yes, this is fairly annoying - but it is outside our control.

> it should not be necessary to manually do a db compare after and extension upgrade to bring a TYPO3 installation back to life.

In general I'd agree but in this case you will have to request this from the TYPO3 core itself, for example in the form of a composer hook which triggers after doing an update, causing a re-validation of the database schema. Another thing that could mitigate this would be for TYPO3 to try/catch in the SiteResolver, catching any errors that happen when attempting to resolve a site and display said error as a FlashMessage, and return a NullSite instance.

This *is* a particularly nasty issue since it affects any TYPO3 component which attempts to resolve a site, which includes anything from toolbar items to translation logic - which means it happens at a very early stage while building the TYPO3 backend and happens in a lot of different places. I strongly suggest you report this to the TYPO3 core since any misconfiguration of or reference to missing field in `$GLOBALS['TYPO3_CONF_VARS']['FE']['addRootLineFields']` may leave you with an inoperable site until you go directly to the install tool to perform the database schema updates and/or flush caches after fixing things like typos in this setting.

(issue pinned to inform anyone running into these problems about what to do to solve it)
