### ISSUE TITLE
conflict with EXT:gridelements in colPos itemsProcFunc

### ISSUE THREAD

**Issue by TrueType** [FluidTYPO3/flux#1743]
TYPO3 v9.5.13
EXT:gridelements v9.4.2
EXT:flux v9.3.1

Both extensions set a value for
`$GLOBALS['TCA']['tt_content']['columns']['colPos']['config']['itemsProcFunc']`
in 
`\Configuration\TCA\Overrides\tt_content.php`

If EXT:flux is loaded after EXT:gridelements the -1 value for e.g. collapsible elements is not available and the colPos cannot be set correctly / an error is shown in the backend CE form.

Wondering, what the solution is here? 
- Enforcing the order of extension loading - https://forge.typo3.org/issues/57825 ? That would then be a matter for EXT:gridelements.
- changing the key for itemsProcFunc possibly to take an array?
- change logic of itemsProcFunc function in EXT:flux to just additionally set the keys coming from the layout? That would leave the colPos selection box preselected with the correct -1 value besides having the layout colPos values. Of course, it would be better to have the single allowed -1 value for selection only. But it would still be much better than the current situation.

https://gitlab.com/coderscare/gridelements/issues/100

**Comment by TrueType** [comment]
workaround: put the EXT:gridelements itemsProcFunc definition in your EXT:mysitepackage and rely on dependencies set in EXT:mysitepackage/ext_emconf.php (composer.json) to such as latest.

**Comment by buepro** [comment]
Alternatively the `colPosListItemProcFunc` method in ` \FluidTYPO3\Flux\Integration\Overrides\BackendLayoutView` might as well be changed to:
```
public function colPosListItemProcFunc(array $parameters, $ref = null)
    {
        // Gets entries from gridelements
        if (ExtensionManagementUtility::isLoaded('gridelements')) {
            GeneralUtility::callUserFunction(
                'GridElementsTeam\Gridelements\Backend\ItemsProcFuncs\ColPosList->itemsProcFunc',
                $parameters,
                $ref
            );
        }
        // Gets entries from flux
        $this->record = $parameters['row'];
        $this->addingItemsForContent = true;
        parent::colPosListItemProcFunc($parameters);
        $this->addingItemsForContent = false;
    }
```

**Comment by NamelessCoder** [comment]
The main problem is two things:

* itemsProcFunc is singular and exclusive; you cannot use multiple proc functions.
* The core itself uses itemsProcFunc to add colPos selection values.

Flux will not introduce a condition to check for presence of GridElements, nor will it call GridElements functions. The GridElements function is incapable of adding the selection values from Flux parent containers (since GridElements will *also* not check for Flux and consult the itemsProcFunc Flux provides).

This is unlikely to be solved in code. Your only option is to ensure that whichever provider you wish to use, is added *after* the provider you do not wish to use.

**Comment by buepro** [comment]
Thank you for this information. For the provider extension [flux_elements](https://github.com/buepro/typo3-flux_elements) I ended up adding a [suggests entry to `ext_emconf.php`](https://github.com/buepro/typo3-flux_elements/blob/e9c76160c50c94f7316da1960e11e8f0cafd9549/ext_emconf.php) and overriding [`\FluidTYPO3\Flux\Integration\Overrides\BackendLayoutView`](https://github.com/buepro/typo3-flux_elements/blob/master/Classes/Integration/Overrides/BackendLayoutView.php).

**Comment by NamelessCoder** [comment]
Won't/can't be solved in Flux. See proposed TYPO3 core change https://review.typo3.org/c/Packages/TYPO3.CMS/+/64068 which would allow multiple itemsProcFuncs to coexist.

**Comment by DavidBruchmann** [comment]
IDEA:  
choose a random key like  
```
$GLOBALS['TCA']['tt_content']['columns']['colPos']['config']['itemsProcFuncArray']
```
write an extension that is reading the values of it and defining itself a class for `$GLOBALS['TCA']['tt_content']['columns']['colPos']['config']['itemsProcFunc`]. Then this class can handle the requests and the core never has to know anything about it.

**Comment by DavidBruchmann** [comment]
About the "design" of the values for the proposed key it could be just a class as array value but it could be more too:  
Simplest improvement would be to allow numbers as key where lower numbers are proceeded earlier, (like in COAs in TypoScript):
```
$GLOBALS['TCA']['tt_content']['columns']['colPos']['config']['itemsProcFuncArray'][10] = class_1;
$GLOBALS['TCA']['tt_content']['columns']['colPos']['config']['itemsProcFuncArray'][20] = class_3;
$GLOBALS['TCA']['tt_content']['columns']['colPos']['config']['itemsProcFuncArray'][30] = class_2;
```
An advanced option to configure whole arrays like this:
```
$GLOBALS['TCA']['tt_content']['columns']['colPos']['config']['itemsProcFuncArray'][] = [
    'class' => \Vendor\Extension\Class::class,
    'config' => [
        'priority' => 50    // you know priority I guess from services
    ]
];
```
Usage of priority might not be recommended but its an option. Perhaps there are better options to solve problems like mentioned in the issue, also respecting special cases. Keep in mind, that it's here only about the configuration for the potential extension and it's not directly about the extension itself.

**Comment by NamelessCoder** [comment]
@DavidBruchmann Even if you added an extension to process this, the final TCA property that would need to be used, is still mutually exclusive. Any extension which uses that property instead of the virtual property added by such an extension, would then remove the extension's ability to process multiple items processing functions. Even the core itself defines items processing functions as strings which would be overwritten if a third party also sets the property.

This is one feature that must be provided by the TYPO3 core, and it still requires all third party extensions to add their processing functions as arrays or cause fallback to the legacy behavior.

**Comment by DavidBruchmann** [comment]
@NamelessCoder probably the easiest was would be to convince Georg of the need.  
An alternative would be possible IMHO but cumbersome.

**Comment by NamelessCoder** [comment]
@DavidBruchmann You mean Jo, right? Georg Ringer is afaik not involved with GridElements. I appreciate the suggestions but it's not that easy - it shouldn't be the responsibility of extension A to add compatibility with extension B because they also have to maintain this solution. And as mentioned, even the core itself uses an itemsProcFunc for this particular field. The right solution is to change the core to allow multiple itemsProcFunc entries so any number of extensions can add their own functions without introducing any conflicts - instead of putting it on extension authors that their extensions need to coordinate compatibility with every other extension that might potentially need to use the same fields. It's an architecture issue, not an implementation issue.

**Comment by DavidBruchmann** [comment]
I meant Georg Ringer, because he's blocking your request:
![image](https://user-images.githubusercontent.com/999146/79688546-2d3f5380-8279-11ea-875d-9ad5d455bdfd.png)

**Comment by NamelessCoder** [comment]
Ah okay, not I got you :) let's see what happens, Benni Mack is aware of the reason and necessity behind the patch.

**Comment by DavidBruchmann** [comment]
All right :)
