### ISSUE TITLE
grird preview of content-elements

### ISSUE THREAD

**Issue by MediKathi** [FluidTYPO3/flux#1748]
Hello,

while migrating from flux 9.2 to 9.3.2 I found this:

If a content-element on a Page uses a `<flux:grid>` then I got this error in the backend:
```
Call to undefined method FluidTYPO3\Flux\Integration\Overrides\PageLayoutView::start()
in /srv/www/partner/testv10/typo3conf/ext/flux/Classes/Integration/PreviewView.php line 256
...
```
If I comment this line of code, the backend seams working fine again. But all childelements of the Content-Element now apperaing in the `unused` section

**Comment by masonen** [comment]
Same Here. Working on a local fix that don't breaks compatibility. Not sure about an ETA right now.

**Comment by masonen** [comment]
Dove into Code a bit here: 

FluidTYPO3\Flux\Integration\Overrides\PageLayoutView extends TYPO3\CMS\Backend\View\PageLayoutView (wich is marked as deprecated in will be removed in typo3 v11, so no problem right now) 

Some heavy refactoring happened inside this class and the TYPO3\CMS\Backend\View\PageLayoutView:start() was removed in the process because it was not needed anymore.

Also NamelessCoder provided a fluid replacement for PageLayoutView in recent past, so there might me some plans refactoring the Flux backend rendering. I'll wait for some feedback here.
