### ISSUE TITLE
Flux Content under windows / wamp

### ISSUE THREAD

**Issue by supercaccia** [FluidTYPO3/flux#1752]
Under windows FCE flux content on folder example C:\wamp\www\base95\typo3conf\ext\theme\Resources\Private\Templates\Content are not found.

Page templates works correctly.

Same identically TYPO3 install works under linux OS.

In flux 9.2 all works correctly, error start on flux 9.3.

```
Oops, an error occurred!
Tried resolving a template file for controller action "Content->fce1colonna" in format ".html", but none of the paths contained the expected template file (). The following paths were checked: C:/wamp/www/base95/typo3conf/ext/theme/Resources/Private/Templates/
```

**Comment by Geddo** [comment]
same for me. Files are there

**Comment by ajikmi** [comment]
Same Problem on Windows 10.
on Mac and FreeBSD working correctly

**Comment by NamelessCoder** [comment]
@supercaccia @Geddo @ajikmi - can one of you provide me with a complete stack trace? I don't have a Windows environment to reproduce this.

**Comment by supercaccia** [comment]
[StackTrace.pdf](https://github.com/FluidTYPO3/flux/files/4604310/StackTrace.pdf)

Dear Claus,
thanks for taking this report seriously.
The required stack trace is attached in pdf format.
If you start with a clean installation there are no errors, but it is not possible to insert the FCEs because they do not appear in the list.
If you use a platform with content already inserted you can see the error if you open a page that contains the FCE.
I will be available if you need to test.
Thanks

**Comment by NamelessCoder** [comment]
@supercaccia Thanks for the stack trace - this looks like it could be an issue with Fluid's TemplatePaths API, it appears your template root path is set correctly but the expected relative filename inside the template path is, for some reason, empty.

It seems to happen in https://github.com/TYPO3/Fluid/blob/master/src/View/TemplatePaths.php#L718 but since paths are not empty, I would expect to see at least one entry in the $tried variable which would then be reported as part of the exception message.

I'm not sure if you are familiar with xdebug but if you have that option, please what happens inside this loop on your system:

* The $relativePathAndFilename should definitely not be empty (the value should be something like `Content/Myfile`). The value of this variable is defined by this hardcoded array of possible relative file locations: https://github.com/TYPO3/Fluid/blob/master/src/View/TemplatePaths.php#L263
* The $paths variable shouldn't be empty before entering the loop; we expect $paths contains the same values as $this->templateRootPaths.
* The condition `if (is_file($pathAndFilename)) {` should only be entered if $pathAndFilename is actually a physical file.

I suspect that $pathAndFilename is somehow not a valid path, yet the `is_file` condition is entered because Windows treats this filesystem check differently than *NIX does. The reason could be that Windows doesn't allow mixing directory separators `/` and `\\` in this function but I can't spot if this is the case in your system (it shouldn't be, based on your template root paths). So watch out for the $pathAndFilename value possibly containing one or more `\\`.

Another thing you can try is to change the `is_file()` condition(s) to `file_exists() && !is_dir()` if the problem is that `is_file` unexpectedly returns true for an input variable that isn't a file but "something else", e.g. a directory.

If you're able to confirm that the problem lies in TemplatePaths we will need to move this issue to the Fluid repository.

**Comment by supercaccia** [comment]
I'm sorry but my familiarity with xdebug is not good, I tried to put "var_dump ()" in the code and if I did everything perfectly I confirm that "relativePathAndFilename" is kept empty; the var_dump () describes only paths of the "Page" but never of the "Contents".

If it is possible for someone to send me the file "\vendor\typo3fluid\fluid\src\View\TemplatePaths.php“ with “var_dump” In the right place inside it I can then show the result.

How do we go on?
Thanks
