### ISSUE TITLE
Error finding Template "Content->atesContentStandard" / Symlink Issue (DropInContentTypeDefinition) because $basePath is not done via "realpath"

### ISSUE THREAD

**Issue by woodyc79** [FluidTYPO3/flux#1757]
Hello! 

I work with symlinks, so the $relativeTemplatePath in Line 98 (DropInContentTypeDefinition) is done wrong (strlen of $basepath is longer than $templateFile, which is done with "realpath", so i got an error: 
"Tried resolving a template file for controller action "Content->atesContentStandard" in format ".html", but none of the paths contained the expected template"....
Thats because the $basepath is longer (symlink to another directory), so the $templateFile Path is cut off...

Solution seems to get the $basePath also via "realpath" in line 77 of DropInContentTypeDefinition:
https://github.com/FluidTYPO3/flux/blob/de989b5fc10ce305f208c55ce4ee2293c85a223c/Classes/Content/TypeDefinition/FluidFileBased/DropInContentTypeDefinition.php#L77
`$basePath = realpath(GeneralUtility::getFileAbsFileName($basePath));`

The error is gone then.

Regards,
Christian Holzmann

**Comment by NamelessCoder** [comment]
Hi Christian,

This should be fixed in `dev-development` - can you check and report back? If it is the same issue the fix was implemented by checking the length of paths before truncating the path to relative. https://github.com/FluidTYPO3/flux/blob/de989b5fc10ce305f208c55ce4ee2293c85a223c/Classes/Content/TypeDefinition/FluidFileBased/DropInContentTypeDefinition.php#L97
