### ISSUE TITLE
[Ask] MultiRelationViewHelper and frontend

### ISSUE THREAD

**Issue by UNI49** [FluidTYPO3/flux#1765]
Hello,

I've tried to use **MultiRelationViewHelper**, in a FCE, and I've no problem (backend). But I don't understand how to retrieve that on frontend. I've find `v:resource.record` but it's limited to just one field, not the entire record.

Is there any solution for doing that ?

Thanks for help.

**Comment by NamelessCoder** [comment]
Depending on your exact use case you've got a couple of options:

* If your records have an associated domain model you can use the `transform` property to declare the data type. The value of `transform` must then be the same syntax as when annotating a 1:n or m:n relation in an Extbase domain model class.
* If you don't have a model class for the records you will have to use either a controller class for the content type, or create a custom ViewHelper which will load the records. Standard practice is to do so in a controller class.

Hope this helps - if you need further information you are welcome to ask your question in TYPO3's slack, channel #ext-flux, or on StackOverflow (https://stackoverflow.com/questions/tagged/typo3, don't forget to add the "typo3" tag to make it visible). Other users may be able to provide you with more precise examples or share code of their implementations!

**Comment by UNI49** [comment]
Hi,

Thanks for answer.

But I've a specific question here : when it's a "transform: array" it's in fact a CSV one, it's okay we have all the selected Items, but when I choose the "model" transform, I can only have the first one? (I've tried with "News" for example)

It's a multi-relation, but only one is return when in model transform… really weird.

**Comment by NamelessCoder** [comment]
Make sure your `transform` property has a value of `\TYPO3\CMS\Extbase\Persistence\ObjectStorage<DomainClassName>` if the target value should be a list of objects instead of a single object. This follows the practice from domain model class construction - see for example https://docs.typo3.org/m/typo3/book-extbasefluid/master/en-us/5-Domain/2-implementing-the-domain-model.html which explains how to annotate properties with the "ObjectStorage containing XYZ instances" syntax.
