### ISSUE TITLE
registerConfigurationProvider not working

### ISSUE THREAD

**Issue by alexdpunkt** [FluidTYPO3/flux#1767]
I want to use flux to register a dynamic flux/form in a Plugin.

Configuration provider: 
```php
<?php

namespace Vendor\Foo\Provider;

use FluidTYPO3\Flux\Provider\AbstractProvider;
use FluidTYPO3\Flux\Provider\ProviderInterface;

class ArticlesConfigurationProvider extends AbstractProvider implements ProviderInterface
{
    /**
     * @var string
     */
    protected $tableName = 'tt_content';

    /**
     * @var string
     */
    protected $fieldName = 'pi_flexform';

    /**
     * @var string
     */
    protected $listType = 'foo_articles';

    /**
     * @param array $row
     * @return \FluidTYPO3\Flux\Form|\FluidTYPO3\Flux\Form\FormInterface|null
     */
    public function getForm(array $row)
    {

        $form = \FluidTYPO3\Flux\Form::create();
        $form->setName('settings');
        $form->createField('input', 'test', 'My test field');

        return $form;

    }
}
```
Registering it in ext_localconf.php:
```php
\FluidTYPO3\Flux\Core::registerConfigurationProvider(\Vendor\Foo\Provider\ArticlesConfigurationProvider::class);
```

Unfortunately all I get is the following error when I go to any page in the backend with this Plugin: 

> (1/1) #1257246929 TYPO3Fluid\Fluid\View\Exception\InvalidTemplateResourceException
> Tried resolving a template file for controller action "ArticlesConfiguration->default" in format ".html", but none of the paths contained the expected template file (). No paths configured.

Why is it trying to resolve a view? I don't want to use a fluid template, I simply want to generate the form  dynamically in `getForm()`

I also found an [article](https://www.medienreaktor.de/blog/dynamic-backend-forms-in-typo3-using-flux) where this was done exactly the same, so this was working some time ago.

What am I doing wrong? 

**Environment:** 
typo3 9.5.15
flux 9.3.2

**Comment by NamelessCoder** [comment]
This is probably because of the interface `ProviderInterface` which implies that you want to use every one of the possible Provider functionalities, which includes preview rendering and Fluid template rendering. The `ProviderInterface` covers a collection of individual responsibility signaling interfaces - the solution in your use case may be one of the following:

* Implement instead `\FluidTYPO3\Flux\Provider\Interfaces\FormProviderInterface` which signals that the only responsibility of your Provider is to return a Form instance.
* Or override the functions from `\FluidTYPO3\Flux\Provider\Interfaces\FluidProviderInterface` to force use of a different template file.
* Or override the `getPreview` method (which is only called in the page module, not when editing the record).

I'm guessing the first solution is more appropriate if your use case is strictly to return a Form that then becomes the DataStructure for your content type.

Your use case description also implies that you want to use this with a plugin that uses the `list` content type and `list_type` sub-type - if this is the case you may also need to implement the `\FluidTYPO3\Flux\Provider\Interfaces\PluginProviderInterface` and `\FluidTYPO3\Flux\Provider\Interfaces\ContentTypeProviderInterface` interfaces (but your Provider should be able to work without them since the `trigger()` method would return true given the properties you set in the Provider). In any case, for clarity, you might want to implement those interfaces.

**Comment by NamelessCoder** [comment]
I assume the answer above allows you to fix your implementation to work without involving Fluid templates. If not, feel free to ping me and I'll reopen and/or provide further suggestions.
