### ISSUE TITLE
Flux Core::registerTemplateAsContentType for Content-Element breaks whole prduction website!

### ISSUE THREAD

**Issue by typoworx-de** [FluidTYPO3/flux#1775]
We just had a total break-down on a production website. This was simply caused by an accidently missing Flux CE Template file which was being registered in ext_localconf.php of site-package extension using:
```php
        \FluidTYPO3\Flux\Core::registerTemplateAsContentType(
            $providerExtensionName,
            $providerTemplatePath . 'SliderContent.html'
        );
```
The whole website (not even only pages directly affected) was down completly!

This is okay if working in Development, but such things should NEVER EVER happen in Production-Context! The only reason I could think of it could be okay is, if the missing file really would break the whole page rendering. But this was definitely not the case here!

Core::registerTemplateAsContentType should definetly use try/catch and check for Development-Context before even thinking about throwing an exception!

If on Production Context there should be NO-Exception, but silent logging.

**Comment by NamelessCoder** [comment]
Sorry to hear about your issues in production - but I'm not sure the right choice is to implement silent logging. If you register a template as content type, but the file doesn't exist, that's definitely a consistency issue that should cause an error (also in production). It means the site, as configured by you, cannot be operated correctly. If your setup isn't sure if the file exists (for example, extension A registers it but extension B provides it and extension B isn't loaded) you should have `file_exists` or other checks before attempting to use the template; rather than indiscriminately calling registration methods and expecting the call to not result in an error in one context but result in an error in another.

Such a problem would prevent the CType from being used at all and would invalidate all existing instances of the content type. It corresponds to manually defining a CType which also would cause an exception in the frontend (except it wouldn't cause it until you add an instance of the CType, the difference being that if you manually created all registration, TYPO3 would actually allow you to use an invalid CType - Flux will not allow that).

On the topic of throwing exceptions in production: this is actually standard practice. However, how the exception is handled can be made sensitive to application context (and exceptions can either be thrown, logged, or converted to inline error messages).

Despite the above, if you prefer that your site doesn't warn about this type of consistency issue (depending on context if you wish) I would say the right choice is to catch this exception in your ext_localconf.php file and either ignore, log or re-throw the error. But of course I would recommend letting CI or pre-deployment testing catch this type of issue since deploying an inconsistent state would inevitably cause problems; whether you see them right away or hear about them when a page that attempts to use the inconsistent state is rendered.

While I am sorry to hear about your incident, I don't believe that swallowing exceptions depending on application context is the right solution - neither in Flux or in your own code. If you disagree you can use the above suggestions to allow inconsistent states in production - but I would not recommend doing that.

**Comment by typoworx-de** [comment]
> Sorry to hear about your issues in production - but I'm not sure the right choice is to implement silent logging. If you register a template as content type, but the file doesn't exist, that's definitely a consistency issue that should cause an error (also in production). 

It may be should create an error... but not for the whole backend & frontend and even views that not even actually try to use the missing template! This was the issue in my case. This is just blowing up everything. It's actually the same as your car would be completly damaged just because one of your blinker lights are blown up. ;-)

**Comment by NamelessCoder** [comment]
Closing the issue - if this exception is hidden or even just moved to logs it makes tracking down any mistakes you may have made, very difficult. Also this does not appear to be a widespread problem and it is one that would be caught by any level of functional, integration or pre-deployment test that involves bootstrapping the TYPO3 instance (and I strongly recommend such steps for the deployment process!). There are *many* core functions that would produce similar exceptions if files or configuration is missing even if the file/configuration wouldn't prevent partial operability - so this is far from an uncommon or excessive behavior.

While it isn't in itself unreasonable to have a try/catch with silent logging as a feature, there does not seem to be enough demand to merit both implementing and documenting, and then maintaining it.
