### ISSUE TITLE
Flux 9.3.2 > 9.4.0 Error in Frontend

### ISSUE THREAD

**Issue by MartinH0** [FluidTYPO3/flux#1791]
Ater updating to FLUX 9.4.0 I get the error
"Please select a page template in page properties."

I think it must be a simple error as this never ever happend before.
I had to restore a Backup to make it go away.
If additional Infos (like trace) is needed just tell me

**Comment by MatthiasPeltzer** [comment]
Hi... same behaviour here. It´s in:
flux\Resources\Private\Templates\Page\Default.html

{namespace flux=FluidTYPO3\Flux\ViewHelpers}
Please select a page template in page properties. <-- That´s the problem
<f:section name="Configuration">
	<flux:form id="default" />
</f:section>

**Comment by fnagel** [comment]
See here how to workaround: https://github.com/FluidTYPO3/flux/issues/1733

**Comment by MartinH0** [comment]
@NamelessCoder do you think you can fiy that permanently so this does not come again?
As with teh next update this automatically will again show up.

`page.5 >`

This did the trick but I think as soon as someone installs the extension there should not be any notice like this.

**Comment by NamelessCoder** [comment]
@MartinH0 Sounds like you need to implement that line of TS in a TS file/record that's not part of Flux. The line unsets the object added by Flux so you can add it literally anywhere that loads after Flux is loaded - in another extension's ext_localconf.php or in a TS record, for example in the place where you define your own `PAGE` object. You're not supposed to put that line in the TS templates delivered by Flux.

Alternatively you can disable the "autload" Flux option in EM or "Settings" admin module, depending on version. Disabling the option converts the automatically loaded TS to a static include that you would have to manually include to add the `page.5` object.

To be clear: `page.5`  is defined by Flux to allow page templating to work without the need to write any TS - if you don't wish to use Flux page templates, you can unset that object and define your own. And since you don't wish to use Flux's page template system you almost certainly have a TS template that already contains a `page = PAGE` definition which would be the perfect place to add that line.

**Comment by MartinH0** [comment]
Yes I just thought it would make more sense to just activate this in "Debug-Mode" as this is just a Debug thing as far as I understand it. Like you wanna know if your Template gets rendered. But just having the optinon to disable it via TS is kinds strange fore me. Normally nothing should ever get rendered unles you activate it.

Also I tried to deactivate the autload Flux option but this did not work... seems like its hardcoded

**Comment by NamelessCoder** [comment]
The TS inclusion is not a debug-only thing, not just for determining if your template is rendered - but to automatically create the necessary `PAGE` TS object that is capable of rendering Flux page templates.

> Normally nothing should ever get rendered unles you activate it.

Part of the purpose of Flux is to prevent the need for extensive manual configuration and deep knowledge of TYPO3 configuration before you can get started. So in this case it actually should be rendered without you activating it. That said, the option to disable it is included, either through TS or disabling `autoload`.

> Also I tried to deactivate the autload Flux option but this did not work... seems like its hardcoded

I found a bug in that regard, see linked commit. Will be fixed in 9.4.1.

**Comment by MartinH0** [comment]
> I found a bug in that regard, see linked commit. Will be fixed in 9.4.1.

Aaaah thank you! Thats the only thing I wanted. A simple method to deactivate this via options/setting and not having to do it via TS. 

Thank you!

**Comment by fabarea** [comment]
I think there is still an issue with the plug-and-play feature which will soon pop up. 
Using the built-in PHP function `realpath` does not work on non existing files and can not be used to "resolve a path" as in:

https://github.com/FluidTYPO3/flux/blob/development/Classes/Content/TypeDefinition/FluidFileBased/DropInContentTypeDefinition.php#L78

Some people have written custom function for that:

https://stackoverflow.com/questions/20522605/what-is-the-best-way-to-resolve-a-relative-path-like-realpath-for-non-existing
