### ISSUE TITLE
TYPO3 10, FLUX 9.4.0 flux:field.file not working

### ISSUE THREAD

**Issue by robsonrobi** [FluidTYPO3/flux#1803]
I have an old web, that  has some old non fal content elements, that are using 

`
<flux:field.file name="image" allowed="jpg,png,svg" showThumbnails="1" />
`

inside an object to realize a custom slider.

The element produces an error, that internal_type must be set to folder or db.
Setting it for example to db, the error disappers, but the field is not getting rendered.
Setting useFalRelation="1" shows up the field and an image can be chosen, but saving it produces an error in 
FluidTYPO3\Flux\Integration\HookSubscribers\DataHandlerSubscriber 

$originalParentUid = ColumnNumberUtility::calculateParentUid($originalRecord['colPos'])

The function expected an int, but null is given.

Is there any chance to get the old flux:field.file keep alive ?

**Comment by grischpel** [comment]
I also have this error:

![Anmerkung 2020-06-27 194707](https://user-images.githubusercontent.com/35844133/85928672-150a3700-b8af-11ea-8366-0d175a573f02.png)

I hope this screenshoot helps

**Comment by NamelessCoder** [comment]
The linked commit prevents the issue reported in the issue where saving the record produces an error.

However, the problem with `internal_type` is caused by a change in TYPO3 core which prevents a `group` type field from having `file` or `folder` as internal type - this is outside of Flux's control and cannot be fixed. Your only option on v10 is to change to a FAL-based field.

**Comment by FailXSiegen** [comment]
@NamelessCoder 
Well... if you used the type field.file in a section -> object construction you don't have the option to change it to inline.fal in a repeating element... what are my options now?

**Comment by NamelessCoder** [comment]
Since TYPO3 no longer supports file relations inside section objects there is no alternative suggestion that I can give. Simply put, TYPO3 no longer supports your use case and Flux can't change that.

**Comment by FailXSiegen** [comment]
hm... this sucks a little bit. But thx a lot 👍

**Comment by robsonrobi** [comment]
@FailXSiegen you can extend sys_file_reference with your needed fields in order to get your options to work.

**Comment by FailXSiegen** [comment]
@robsonrobi thx, i considered that option. I just finished the migration in own records and changed the whole element to a custom extension.

**Comment by kledo-34** [comment]
Hey there, I just found this issue, which is exactly my one at the moment. I'm currently considering to replace all the flux:field.file fields with link fields, as I think this solution could last longer because links are probably a feature that will be remained as it is so fundamental.
If I would be able to reach those field control options, I could only allow certain file types, etc. and combined with uri.typolink for the frontend it could sompletely replace the field.file problem.

Frontend rendering of the links: <f:uri.typolink absolute="true" parameter="{fieldname}"></f:uri.typolink>
Field Control Documentation: https://docs.typo3.org/m/typo3/reference-tca/10.4/en-us/ColumnsConfig/Type/inputLink.html#fieldcontrol
Field Control Sytleguide: https://github.com/TYPO3/styleguide/commit/c3cc88c6841a1f832778702f306d32e597d5f7c7

I tried the following which doesn't throw an error, but also doesn't change anything :(
<flux:field name="somename" label="somelabel" type="input" config="{renderType: 'inputLink', fieldControl=\"{linkPopup = '{options = \'{allowedExtensions = \\'mp4\\', blindLinkOptions = \\'file\\'}\'}'}\"}"/>

If someone knows how to access the fieldControl options I would be really happy ;)

**Comment by kledo-34** [comment]
I found the correct Syntax
Nesting can be kind of hard
`config="{renderType: 'inputLink', fieldControl: {linkPopup: {options: {allowedExtensions: 'jpg,png,gif', blindLinkFields: 'class,params,target,title', blindLinkOptions: 'folder,mail,page,spec,telephone,url'}}}}"`

I changed all of my fields to this new flux.field type with the config attribute, hopefully this structure will be maintained. By the way is there a new version for sections and objects or do they stay the way they are?

**Comment by NamelessCoder** [comment]
Nesting can be a bit cumbersome but adding line breaks helps with readability and is tolerated by Fluid.

> By the way is there a new version for sections and objects or do they stay the way they are?

These will stay the same, they are not expected in any way to receive new properties by the core. The reason why the fields are migrated to a more generic structure is that there have been (major) TCA changes from 8.7 to 9.5 and again to 10.4 which made it unfeasible to maintain the more specific wrappers. So instead you get the generic version and have to fine-tune the properties to match the target TYPO3 version.

**Comment by yol** [comment]
Maybe this might be interesting to some people here:

https://stackoverflow.com/questions/66733918/how-to-have-multiple-sections-with-images-in-a-fluidtypo3-flux-form-with-typo3-1/

`useFalRelation="1"` does work for me and I do not get the exception you describe.
