### ISSUE TITLE
flux:field renderType inputLink not visible for editors

### ISSUE THREAD

**Issue by slowhand11** [FluidTYPO3/flux#1812]
Link field is not visible for other BE-user than the admin.
![screenshot-www ck-akademie de-2020 07 23-10_24_31](https://user-images.githubusercontent.com/5380418/88266157-fc831600-ccce-11ea-8d7a-203962ce6231.png)

**Comment by KevinMcLean** [comment]
I had the same Problem, but i fixed that.
1. The Problem with Editor: <flux:field type="input" name="link" label="Verlinkung" config="{renderType: 'inputLink'}" />
**Fixed Variant:  <flux:field.input name="link2" label="Verlinkung 2" config="{renderType: 'inputLink'}" />**

It is necessary that you define the **_flux.field.input_** -Tag not the _type="input"_

**Comment by slowhand11** [comment]
Thanks a lot !

**Comment by NamelessCoder** [comment]
It is not advisable to use `flux:field.*` since these type-specific ViewHelpers are deprecated. The reason your field is inaccessible is that `exclude="1"` is set by default - adding `exclude="0"` changes the exclude setting to the same value as the type-specific ViewHelpers. I will consider changing the default value of this flag to "disabled".
