### ISSUE TITLE
Content elements with nested content (grid) are not showing their child content in the page module anymore after upgrading TYPO3 from latest 9.5 to latest 10.4

### ISSUE THREAD

**Issue by geldmacher** [FluidTYPO3/flux#1815]
I am using the latest Flux version (9.4.1).

**With the feature toggle for "Fluid based page module" activated:**
The element is just just showing the placeholder (This column has no "colPos". This is only for display Purposes.). 

![Fluid_based_page_module_on](https://user-images.githubusercontent.com/1763101/89874427-1ae87d00-dbbc-11ea-8ed6-b5c1daec200c.png)

**With the feature toggle for "Fluid based page module" deactivated:**
The columns are not showing their contents and to the column name the string " (No edit access)" is appended. (Admin user used)

![Fluid_based_page_module_off](https://user-images.githubusercontent.com/1763101/89874437-1fad3100-dbbc-11ea-908f-10daa8702a30.png)

---

Before upgrading to 10.4 this content elements worked as expected.

The grid definition of this elements looks like:

```
<flux:grid>
    <flux:grid.row>
        <f:for as="column" each="{columns}" iteration="iteration">
            <flux:grid.column colPos="{iteration.cycle}" colspan="{column.column.columnSize -> v:math.round(decimals: 0) -> v:math.division(b: 12) -> v:math.product(b: 100) -> v:math.round(decimals: 2)}" label="Column {column.column.columnSize}" name="column{record.uid}-{iteration.cycle}"/>
        </f:for>
    </flux:grid.row>
</flux:grid>
```

**Comment by NamelessCoder** [comment]
Unfortunately I'm not able to reproduce this problem - perhaps I can assist more if you can provide a bit of information about the child records (columns `colPos` and `sys_language_uid` in particular) and a bit of context about the use case; I assume you're in a translated language but is the translation done in "connected" or "free" mode?

I also have a more general tip for you which may or may not help. Generating your columns with a foreach this way, implies that you've defined the columns in a `section` as section objects - if this is true then there is a better way to achieve this, which makes the `colPos` values assign themselves to the actual column object instead of being based on the position of the column (basically meaning if you move a column up/down or delete a column that comes before another, you won't see the child content "jumping" to an unexpected column).

You'll need to:

* Remove the `flux:grid` definition
* Declare `contentContainer="1"` on the `flux:form.object` that constitutes a column
* If necessary, declare `gridMode="columns"` on the `flux:form.section` container (default mode is "rows)

This causes the section objects to automatically become columns in the grid and assigns a `colPos` to each of them, which does not change if you move the column or delete other columns in the section.

Alternatively you can manually insert a "column position" field in your section object which serves the same purpose and allows you to keep the manual loop-based creation of your grid columns: https://github.com/FluidTYPO3/flux/commit/240cd68d7417cdd06ef7c91aeafa1ca70678ddb4

**Comment by geldmacher** [comment]
First of all: Your advice with `contentContainer="1"` and `gridMode="columns"` works as expected and i really like this approach (This specifically: https://github.com/FluidTYPO3/flux/commit/240cd68d7417cdd06ef7c91aeafa1ca70678ddb4). =) Is there a good migration path to this approach?

The `sys_language_uid` is 0 because i am having this problem in the default language. 
The `colPos` from one of the elements are for example 1501, 1502 and 1503 in a 3 column row with the `uid` 15.

Because you were not able to reproduce it i played around a bit more. My grid element has a lot of configuration possibilities. I reduced them a lot and figured out that there is one specific constellation which produces my problem. I am using a very descriptive label and figured out that emptying it solved my problem. This is a case which produces my problem (lol):

```
<flux:grid.column colPos="{iteration.cycle}" colspan="{column.column.columnSize_lg -> v:math.round(decimals: 0) -> v:math.division(b: 12) -> v:math.product(b: 100) -> v:math.round(decimals: 2)}" label="
                    D (" name="column{record.uid}-{iteration.cycle}"/>
```

**Comment by NamelessCoder** [comment]
> Is there a good migration path to this approach?

Sorry, no. Had you used `colPos="{iteration.index}"` instaed of `colPos="{iteration.cycle}"` it would have pretty much worked without the need for any adjustments, but because your colPos values start at `1` because `.cycle` starts at one, you'll need to adjust the colPos values of all child elements, e.g. `UPDATE tt_content SET colPos = 1500 WHERE colPos = 1501` and so on until you've updated all child elements. You may be able to come up with a better query for this - the key is to subtract `1` from all colPos values of elements stored within a container that starts the colPos indexes at `1` and now start at `0`.

I'm afraid I have no idea whatsoever why a particular label would cause the elements to not be shown... but perhaps you can either clean up the complexity of the label, or use a custom VH to create it, to avoid using complex syntax in that property?

**Comment by geldmacher** [comment]
I will find a good solution for my label. Now that i know what the problem is. You really helped a lot, THX! =)
