### ISSUE TITLE
Child Content Element's Colpos is not Updated on Copy

### ISSUE THREAD

**Issue by simare** [FluidTYPO3/flux#1824]
The colpos of a chid element  is not updated when copying a page if the field sorting of the child is greater than sorting of the parent.
This is because the child record is processed before the parent and thus ```DataHandlerSubscriber::$copiedRecords``` does not contain the uid of the parent record, so no colpos calculation is triggered.

**Comment by KevinMcLean** [comment]
I have the same problem with a three-column container when I insert child elements there.

If you copy the whole container, it will only insert the container and no child elements.

Could someone adjust this?

**Comment by baschny** [comment]
We also struggled with exact this same problem. This makes the whole system unusable to the customer where the workflows requires to constantly copy pages with nested content elements. "Sometimes it works" is the feedback from the customer and my debugging came to the same conclusion here: it depends on the order that the DataHandler processed the input if it "works or not". 

Is there any better solution in sight, or is this problem known already, @NamelessCoder?

**Comment by baschny** [comment]
The DataHandler.php copies the content elements in reverse "sortby" order, this is why this happens:
https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Classes/DataHandling/DataHandler.php#L3320-L3322

**Comment by simare** [comment]
As far as I recall the problem occurs with container elements that were created before the colpos handling for child records changed.
You just need to move the container around on the same page so the sorting fixes itself. After that you can copy containers at will.

**Comment by baschny** [comment]
@simare good comment! That could be a potential reason! Maybe then we could create a "migration" for this situation? have you managed to achieve such a thing?

**Comment by simare** [comment]
@baschny I thought about creating a migration but it is a bit tricky to figure out the correct sorting value. The container should not change its relative position but the sorting value has to be greater than that of the child records. So you might have to update sorting for all content elements on the page.

Maybe some kind of brute force approach like adding 1000 to all content elements one a page, except for the children, would work.
We only had a couple of elements and fixed it manually.

**Comment by NamelessCoder** [comment]
@baschny I don't have a concrete suggestion how to avoid this case, yet. I suspect it would be possible to sort the command map before the copy happens, to make sure that parents are copied before children, but that's as far as I've thought about it at this point. I'm hoping it is possible to do this without performing additional queries and without modifying the sorting value in DB but that all depends on how much data is available in the command map before it starts to process.

If we're lucky then it can be done with one of the pre-functions in the DataHandler hook using a relatively simple `usort`...

**Comment by baschny** [comment]
@NamelessCoder thanks for the input. Is that something that the "migration tool" could consider? As far as I understood this problem will only happen for "migrated content" and does not happen for "new content". Is that true, anyway? Does flux also update the "sorting" field accordingly on creating new content to avoid this problem from happening?

**Comment by nitori** [comment]
When I manually update the sorting of a child element to be greater than the sorting of it's parent, then all hell breaks loose.

Though this seems to only happen if I copy a page, not if the sorting is "wrong" in nested grids and I only copy the container. Probably because the page copying mechanism already tries to copy all it's content elements.

Anyway, the result is usually I end up with either of the two

1. There will be "Ghost Records".

Meaning Elements that have been copied to the new page (pid is correct), but their colPos still points to the original Container. The effect is, they only appear in the List module of the new page, They _do not_ appear in the Page module in the old or the new Grid Element.

_However_, if I then try to copy the original Grid from the source page, to some other location (doesn't seem to matter where), those Ghost Records that still reference the Grid I'm trying to copy will be copied _as well_, despite them not being on the same page as the Grid.

This seems to reliably happen to "first level" nested elements, that have a higher sorting than their parent, where the parent has a regular colPos (not in a container itself).

2. We end up with "unused" Elements.

If the Element with the wrong sorting is not a "first level" nested element, but deeper nested, then it can happen that it's somehow copied to the correct page, but ends in the "unused" area.

I also noticed cases where those "Ghost Records" were created. But I think that depends on the containers columns and if those columns exist on the root level as well, e. g. root level has colPos 0, and the container has colPos 0 as well. If the containers colPos do not exist on root level, it seems to happen more frequently, that those nested Elements end up in the "unused" area.

---

All of this seems to be related to the "sorting" field of the content elements. All the children should always have a lower sorting value than their parent.

Like stated, to reproduce these issues I modified the sorting column by hand, though our Customer seems to be able to achieve it by themselves somehow, on completely newly created pages. Though since this was an update, it's possible they might've copied some older stuff. Not sure.
