### ISSUE TITLE
Error: Invalid configuration: "vendorName" is not set after upgrade to Flux 9.4 and Typo3 9.5

### ISSUE THREAD

**Issue by rehoehle** [FluidTYPO3/flux#1847]
I have to upgrade a page to Typo3 and i search not for hours some very annoying problems. 

So i have read a lot and saw that after updating the package you have to make some database changes and migrate the tt_content (CType) to a new format **"myextension_slider"** for example. I have done that and the system try to load the fields. I have disabled the automatic plug and play configuration and i have added the colpos which is now the iterator for my dynamic columns. 

**But in the backend i get the following error:** 

![Screenshot at Oct 25 19-58-29](https://user-images.githubusercontent.com/223007/97116412-36fcb480-16fd-11eb-9a66-2955a67d9ce9.png)

**And in the frontend the following error:**

![Screenshot at Oct 25 19-59-15](https://user-images.githubusercontent.com/223007/97116423-47ad2a80-16fd-11eb-984f-9de411baa19e.png)

I have tested a lot now and can't find the problem. It's not my code and thats the problem to find the problem in the configuration. 

https://sigalambigha.home.blog/2020/04/29/how-to-migrate-fluidcontent-to-flux/

I have tested all of that points from this tutorial aswell. So perhaps someone has a hint or can help me. 

What i have found is that when i go to my main page to "Page Layouts" the dropdowns with "Page Layout - this page[tx_fed_page_controller_action]" are empty. 

**Edit and more informations**

I have made some tests. On the line in the PreviewView.php on line 363. There is a feature called. But in Typo3 9.5 there is no feature. If i disable that section the backend is rendered. Everything inside the code block is for Typo3 10.3+ is there something wrong in the code?

I have used Version 9.3.2 which has the "vendorName" problem but i have found a blog article with the notice "To notice another bug"... you have to set the vendorName for every element. Could you please fix this problem? After that i got the error that the "ContentController" is not available and i had to insert an empty class in the plugin. 

```# Bugfix flux
tt_content {
    myplugin_slider.20.vendorName = Test
    myplugin_2colimagetextbox.20.vendorName = Test
    myplugin_imagewithcontent.20.vendorName = Test
}
```

**Comment by NamelessCoder** [comment]
This one should be solved, over multiple iterations. Flux had a bit of problems with the differences between plugin registrations on TYPO3 8/9 and 10.4+ where some versions demand a vendorName and others don't, some versions demand an FQN of the controller class and others don't. The registration business logic now accommodates for these differences and registers the plugins with the appropriate method depending on TYPO3 version.

Don't forget though: your extension key when calling `Core::register*` methods must be in the format `Vendor.ExtensionName`. The controller class / plugin registration properties are deduced from this value so it is vital that the extension identity conforms to this format - otherwise, the expected FQN of involved controller class names cannot be determined.
