### ISSUE TITLE
Call to undefined method TYPO3\CMS\Backend\View\BackendLayout\BackendLayout::getDrawingConfiguration()

### ISSUE THREAD

**Issue by dennismetz** [FluidTYPO3/flux#1892]
TYPO3 9.5.27
Flux 9.5 (9.4.2 working well)
Apache/2.4.41 (Ubuntu), PHP 7.3.28

If i update to latest flux version and try to open any page in the pagetree via site-module i get the following error:
Call to undefined method TYPO3\CMS\Backend\View\BackendLayout\BackendLayout::getDrawingConfiguration()

Cleared the cache, dumped autoload, nothing works.

**Comment by NamelessCoder** [comment]
Hi @dennismetz - is it possible that somewhere in your configuration you've got the `fluidBasedPageModule` TYPO3 feature flag enabled? This feature flag only exists in TYPO3 10.3 and above and Flux will use this flag to detect the specific implementation used to render the page module. If the feature flag is disabled, Flux uses the legacy PageLayoutView and should never attempt to call the mentioned method.

If by chance you have a custom backport of the Fluid-based page module in your project, then depending on the upstream TYPO3 version this was backported from:

* From 10.3, BackendLayout::getDrawingConfiguration must exist and must return a DrawingConfiguration instance which must in turn return a BackendLayoutRenderer instance from the getBackendLayoutRenderer method.
* From 10.4+, the PageLayoutContext and BackendLayoutRenderer classes must exist.

**Comment by NamelessCoder** [comment]
Closing issue as solved. All usages of these 10.3+ classes in code are surrounded by `class_exists` checks and are therefore only vulnerable to special setups that declare these classes but don't implement them according to the original classes' APIs (side note: any overrides of these classes which also don't implement the APIs correctly would cause the same problem in any context, Flux or otherwise).

Flux v10 will remove the legacy compatibility layer in favor of only supporting the new Fluid-based page module - in which these classes and methods are guaranteed to exist.
