### ISSUE TITLE
TYPO3 8.7.32 + Flux 9.5.0 – Page Settings empty on translated pages

### ISSUE THREAD

**Issue by yesjoar** [FluidTYPO3/flux#1910]
Hi there.

Im using TYPO3 8.7.32 with flux 9.5.0 on two different projects for page layouts and content elements. Both pages have multiple languages and on both sites I got the problem, that the settings (page settings) for the translated page are empty. 

For the default language the settings are fine.
I haven't enabled the setting to show the page configuration field on translated pages.

Also I checked the database. In pages_languages_overlay the field for the settings is empty.
I updated both projects to the latest flux and TYPO3 version. Before this the error does not happened.

Anyone else here who can confirm this problem?
Or someone here who has a workaround to fix this problem?

Best

**Comment by lucmuller** [comment]
I'm also facing an issue of the same kind.

On my TYPO3 8.7.30 instance and using flux 9.5.0, when configuration translation is not enabled, the configuration used by flux seems to be the on set or inherited from the subpage configuration.

It seems to be the same issue than https://github.com/FluidTYPO3/fluidpages/issues/322 .

At the moment I didn't checked the behaviour in upper version of TYPO3, but this is struggling because my current project relies on TYPO3 8.7 :/

**Comment by NamelessCoder** [comment]
This is - apparently - the default behavior of TYPO3, but only when it concerns the "pages" table. I have no idea why, though. It simply will not copy almost every field of this specific table when doing a "localize" command.
