### ISSUE TITLE
TYPO3 10.4 Compatibility

### ISSUE THREAD

**Issue by ghwaldo** [FluidTYPO3/flux#1921]
If i use "Scan Extension Files" there are many "weak"-Entrys of deprecated and removed functionality used by flux.

**Comment by NamelessCoder** [comment]
This is an unfortunate side effect of the way TYPO3 scans for incompatibilities - it cannot analyse the code enough to know if the deprecated/invalid usages are guarded by version check conditions, which is frequently the case in Flux because of the wide range of supported TYPO3 versions.

If you find specific incompatibilities which aren't guarded by version checks then I'd welcome new issues. But I have to instruct to generally ignore the reported potential issues in the extension scanner for the reason above.
