### ISSUE TITLE
Future of this project

### ISSUE THREAD

**Issue by LukeDberg** [FluidTYPO3/flux#1922]
We are currently wondering about the future of this project. Currently there is very little progress and already the update to TYPO3 11 was "challenging" and not possible without the dev branch and some adjustments. Are there any further plans or information about this?

**Comment by crazy252** [comment]
As far as I know, the author is currently looking for more helpers for the project. There should also be a release soon. But I am not quite sure.
The support for Typo3 11 is also only noticed by a message in Typo3 Slack.
In my company we continue the extensions partly ourselves, because we depend on it. Maybe you should fork the project to keep the support upright.

**Comment by grischpel** [comment]
@crazy252 do you already forked it and do you can offer it for typo3 11 users?

**Comment by crazy252** [comment]
We are currently working on it. The current flux version of this repo can be used for typo3 11. Maybe we can develop the project further as a community.

**Comment by lukastaferner** [comment]
The dev-branch works for me with t3-v11 - nevertheless I will need a php8.1 compatible version and I think support for  php < 7.4 and t3 8 and 9 could be dropped. It is a pity that this nice extension is not updated any more . . .

**Comment by NamelessCoder** [comment]
Flux is being updated for TYPO3 v11 right now. Unfortunately, there's a longer wait currently between new releases due to a lack of team members and general lack of available time on my part.

> As far as I know, the author is currently looking for more helpers for the project.

I most certainly am! And I appreciate the contributions you and others made recently. It helps, but I could still use additional team members to handle merge requests and address incoming bug reports.

> In my company we continue the extensions partly ourselves, because we depend on it.

Assuming you created pull requests to fix the incompatibilities you faced, you soon would not need to create and maintain forks at least when it considered v11 support. As for the future of the project it would be _much_ more valuable to add some manpower to the team than creating and having to maintain forks ;)

> I will need a php8.1 compatible version

The next version will be, but you should be aware that the TYPO3 core itself still has a couple of rough edges if your TYPO3 instance is configured to produce exceptions for E_NOTICE level errors. You can adjust this in TYPO3's error level configuration!

> support for php < 7.4 and t3 8 and 9 could be dropped

Support for PHP <7.4 will be dropped in the next release. Support for TYPO3 v8 and v9 will be dropped in the next major release.
