### ISSUE TITLE
Wrong sorting item in flux:form.object when deleting one item (just happened total items > 15 )

### ISSUE THREAD

**Issue by emmadao** [FluidTYPO3/flux#1925]
Hi everyone, 
i got an issue with flux 9.5.0 and typo3 10. 
The list items used flux:form.section changed sorting item after i deleting one item but only happened if total items > 15.
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/71652467/153391606-a03915d5-489a-4719-b054-fafb28d7d557.png)

Please help me, thanks all.

**Comment by dominicmartin** [comment]
Hi everyone,

I have the same problem.

TYPO3 10.4.17
Flux 9.5

After deleting element 1249 in my list and saving the record, the sorting is messed up and I can't figure out a logic behind the new sorting.

![github_flux](https://user-images.githubusercontent.com/4675297/160106582-5877659c-54a5-44b0-8b1c-574c4693ac9c.png)

The configuration looks like this:

```
<flux:form.sheet name="elements" label="elements">
    <flux:form.section name="elements" label="elements">
        <flux:form.object name="element" label="element">
            <flux:field.input name="id" label="id" />
            <flux:field.input name="title" label="title" />
            <flux:field.text name="description" label="description" enableRichText="TRUE" />
        </flux:form.object>
    </flux:form.section>
</flux:form.sheet>
```

Is this a bug or am I doing something wrong?

I would be very thankful for help.

**Comment by dominicmartin** [comment]
Hi everyone,

Is there anything new on this topic?

**Comment by dominicmartin** [comment]
Hello everyone :-),

can anyone confirm this behaviour and is there any solution yet?

**Comment by NamelessCoder** [comment]
Hi @dominicmartin and @emmadao,

Sorry about the delay in answering.

Unfortunately I have to refer you to the TYPO3 core bug tracker in this case - https://forge.typo3.org/projects/typo3cms-core/issues. The reason is that Flux itself is not doing any sorting of section objects neither when saving the record nor when displaying the elements in forms. If sorting misbehavior occurs, it cannot be caused by Flux - but it isn't necessarily caused by the TYPO3 core either, since third party extensions **can** affect the sorting (even if Flux doesn't). The key here is that any implementation of a flexform DS that has section objects would be affected by this problem, whether or not Flux is even installed. Basically, you should be able to reproduce the same issue with a totally vanilla DS in a site that doesn't use Flux at all.

I did a quick search on Forge and the best match seems to be https://forge.typo3.org/issues/73761 - though I'm not sure if that's relevant since you don't state if you use workspaces when this problem occurs. If this issue isn't relevant then I'd suggest opening up a new issue that describes this error.

Hope this helps - and sorry I can't provide a solution in the context of Flux.
