### ISSUE TITLE
Problems while migrating from fluidcontent and fluidpages and multisite

### ISSUE THREAD

**Issue by JavierYD** [FluidTYPO3/flux#1943]
Hello,

I've migrated a site from TYPO3 8, based on fluidcontent, fluidpages and flux. I followed the general upgrading steps: first to latest version on branch 8, then to 9, run carefully all upgrade wizards, then to 10, again upgrade wizards, and then to 11. For this version to work I had to install the dev branch of flux. This TYPO3 is multisite and has a base extension which holds layouts and templates for all the sites with the following folder structure:

* Resources/site1/Private/Layouts/Content.html
* Resources/site1/Private/Layouts/Page.html
* Resources/site1/Private/Templates/Content/Text.html
* Resources/site1/Private/Templates/Content/TwoColumns.html
* Resources/site2/Private/Layouts/Content/Content.html
* Resources/site2/Private/Layouts/Content/Default.html
* Resources/site2/Private/Layouts/Content.html
* Resources/site2/Private/Layouts/Page.html
* Resources/site2/Private/Templates/Content/Text.html
* Resources/site2/Private/Templates/Content/Textmedia.html
* Resources/site2/Private/Templates/Content/Textpic.html
* Resources/site2/Private/Templates/Content/TwoColumns.html
* etc

Following Flux documentation, the base extension is registered as provider extension:

`
\FluidTYPO3\Flux\Core::registerProviderExtensionKey('myextension', 'Page');
\FluidTYPO3\Flux\Core::registerProviderExtensionKey('myextension', 'Content');
\FluidTYPO3\Flux\Core::registerProviderExtensionKey('myextension', 'Backend');
`

Also, the classes ContentController and PageController exist under Classes/Controller. Somehow, this configuration was good for TYPO3 10 to load the correct layouts and templates depending on the site, both FE and BE. However, since the upgrade to 11 this stopped working.

It seems that Flux is looking for the layouts and templates in the folder Resources/Private instead of Resources/siteX/Private. If I copy Resources/site1/Private to Resources/Private, things start to work properly, but of course only for site1.

Any hint on this issue?

**Comment by NamelessCoder** [comment]
Hi @JavierYD,

There have been many changes over the years in regards to extracting Flux definitions from template files. In order to guarantee consistency (the same Flux assert works the same way in any page) and to drastically limit the impact on performance, Flux now assumes that all templates are within the default template folders of your provider extension. There's a bit more detail in my answer here: https://github.com/FluidTYPO3/flux/issues/1485#issuecomment-1305660431.

For your specific use case, you would need to create a second provider extension so you have both `site1` and `site2` as individual extensions with templates located in the default `Resources/Private/*` folders. You can still use a shared library of for example partials and layouts _in context of FE output_ but your templates themselves must be in the default locations and may only render partials also located in the default location, within the same extension.
