### ISSUE TITLE
Translating the user interface

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/flux#1960]
Flux provides some language labels like "Page Layout - this page" in `Resources/Private/Language/locallang.xlf`.
How can they be translated in other languages?

I did not find flux on the crowdin server (https://crowdin.com/projects?q=typo3+flux) that is suggested by the core translation documentation at https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Internationalization/TranslationServer/Index.html

Shall the translations be managed there, somewhere else, or shall we just provide patches here on github?

**Comment by NamelessCoder** [comment]
Flux is not registered for translation with Crowdin. It is however registered on the old translation server: https://translation.typo3.org/projects/TYPO3.ext.flux/ (I'm currently unaware if this is still functional). Patches for languages other than English should not be created here on GitHub.

Should you wish to avoid external translation services you can still use the local XLF overrides approach:

```php
// ext_localconf.php or AdditionalConfiguration.php
$GLOBALS['TYPO3_CONF_VARS']['SYS']['locallangXMLOverride']['EXT:cms/locallang_tca.xlf'][] = 'EXT:examples/Resources/Private/Language/custom.xlf';
$GLOBALS['TYPO3_CONF_VARS']['SYS']['locallangXMLOverride']['de']['EXT:cms/locallang_tca.xlf'][] = 'EXT:examples/Resources/Private/Language/de.custom.xlf';
```

Untested, but paths to Flux XLF files in context of this `locallangXMLOverride` setting should be `EXT:flux/Resources/Private/Language/locallang.xlf`.

**Comment by cweiske** [comment]
Did anything change in this regard? The old translation server does not exist anymore, and flux is not on crowdin.

> Patches for languages other than English should not be created here on GitHub.

How else can I contribute a translation for German?

**Comment by NamelessCoder** [comment]
I'm fundamentally against forcing anyone to sign up with a third-party service and I'm also fundamentally opposed to the TYPO3 core decision to run translations through there. So Crowdin is still, as far as I am concerned, 100% out of the question. It's quite sad that TYPO3 decided to stop operating their translation service (Pootle was and is not the only viable option for self-hosting).

I'll relax the "no translation PR through GitHub" restriction and receive translations here on GitHub, since that is the lesser of all the evils, but it has to be with a couple of rules attached (I'll also put these in a README file along with the XLFs):

* Maintenance of any translation outside the default English will only happen as user contributions.
* Translations will be provided as-is.
* No AI or AI-assisted translations - a human brain and native speaker is required to understand the context of labels.

**Comment by cweiske** [comment]
Thanks!
