### ISSUE TITLE
Exception with flux:content.render when updating to Flux 9.6.x

### ISSUE THREAD

**Issue by rtoenjes** [FluidTYPO3/flux#1974]
TYPO3 9.5.31 composer
PHP 7.4.30
Flux 9.6.x

When updating Flux starting stepwise from 9.2, the step from 9.5.0 to 9.6.x results in an exception:
`Argument "column" or "area" for "flux:content.(get|render)" was a string column name "3", but this column was not defined`
I have no clue how to solve the reason because this is not my project and I got in touch with Flux for the first time.

**Comment by almfisch** [comment]
I had the same error after updating flux from 9.5.0 to 9.6.1.
The problem was the area attribute in flux:content.render. It seems that the colPos Id is not more working. After changing to the name value it was working again.

https://viewhelpers.fluidtypo3.org/fluidtypo3/flux/9.0.1/Content/Render.html
area: Name or "colPos" value of the content area to render
It seems that only Name is working.

**Comment by rtoenjes** [comment]
I can confirm that. Switching from colPos to Name in area the site is rendered properly.
Thanks a lot!

**Comment by NamelessCoder** [comment]
Solved - was caused by `ctype_digit` assuming that an integer-type variable with a value between -128 and 255 is intended as an ASCII character rather than a string of number(s).
