### ISSUE TITLE
Missing Default Flux Default Controller

### ISSUE THREAD

**Issue by joneppie** [FluidTYPO3/flux#1975]
When I try to upgrade the flux-based page template for TYPO3 v10 to v11, I get the following error message:

```Exception: The default controller for extension "Flux" and plugin "Page" can not be determined. Please check for TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php.```

What am I doing wrong, or what have I forgotten?

**Comment by Moongazer** [comment]
Having the same issue after an upgrade from v10 to v11. But the error seems not to be Flux related, because it also happens with various other extensions. E.g. on my root-page I have a contact-form, opening it will result in `The default controller for extension "Form" and plugin "Formframework" can not be determined.` (same as [here](https://forge.typo3.org/issues/95694))

On other pages I've custom plugins, where the error says `The default controller for extension "MyVendor" and plugin "MyPluginName" can not be determined.`! No idea what is wrong here...

**Comment by NamelessCoder** [comment]
Did you check through your site if any third-party extensions register middlewares which contain usages of Extbase ConfigurationManager? As described on https://forge.typo3.org/issues/95694 this can cause problems later in the request.

For the record, Flux doesn't contain such middlewares and if a middleware is responsible, it's not an issue that can be fixed by a change in Flux.

**Comment by joneppie** [comment]
Vielen Dank. Der Hinweis hat mich auf die richtige Fährte geführt. Der Fehler ist nun behoben.

**Comment by simare** [comment]
Hi @joneppie ,

can you tell us what caused the error? We are having the same problem.

**Comment by joneppie** [comment]
In our own middleware components, one of the objects for the frontent was created, although not all the necessary elements were available yet.

**Comment by christophlehmann** [comment]
Same Exception here during Upgrade from TYPO3 v10 to v11. Fixed by removing a broken redirect. The redirect target was `t3://page?uid=65` and the page doesn't exist anymore.

**Comment by simare** [comment]
We also have identified broken links or circle redirects as the main cause for this error.
Seems the redirect module does not do a good job in preventing those.

**Comment by patrickklosedev** [comment]
I had the same problem and it could be solved by removing circular redirects in the redirect module as mentioned by simare. However, this was only a problem after updating to Typo3 V11.
