### ISSUE TITLE
Redirect error in Typo 11.5

### ISSUE THREAD

**Issue by trokohl** [FluidTYPO3/flux#1992]
I have another error similar to the one in Ticket  #1893 but now in Typo3 11.
If i use Flux  and the Redirects-Module i get:

`
An exception occurred while executing 'SELECT * FROM `sys_template` WHERE (`pid` = ?) AND ((`sys_template`.`deleted` = 0) AND (`sys_template`.`hidden` = 0) AND (`sys_template`.`starttime` <= 1661948520) AND ((`sys_template`.`endtime` = 0) OR (`sys_template`.`endtime` > 1661948520))) ORDER BY `root` DESC, `sorting` ASC LIMIT 1' with params [138]: Can't create more than max_prepared_stmt_count statements (current value: 16382)`

in /var/www/typo3_src/typo3_src-11.5.14/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 128
in /var/www/typo3_src/typo3_src-11.5.14/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 182
in /var/www/typo3_src/typo3_src-11.5.14/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 159
in /var/www/typo3_src/typo3_src-11.5.14/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php line 2226
in /var/www/typo3_src/typo3_src-11.5.14/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php line 1313
in /var/www/typo3_src/typo3_src-11.5.14/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php line 212
in /var/www/typo3_src/typo3_src-11.5.14/typo3/sysext/core/Classes/Database/Query/QueryBuilder.php line 300
in /var/www/typo3_src/typo3_src-11.5.14/typo3/sysext/core/Classes/TypoScript/TemplateService.php line 553
in /var/www/typo3_src/typo3_src-11.5.14/typo3/sysext/extbase/Classes/Configuration/BackendConfigurationManager.php line 73
in /var/www/typo3_src/typo3_src-11.5.14/typo3/sysext/extbase/Classes/Configuration/ConfigurationManager.php line 111
in /var/www/html/typo3conf/ext/flux/Classes/Service/FluxService.php line 154
in /var/www/html/typo3conf/ext/flux/Classes/Service/FluxService.php line 141
in /var/www/html/typo3conf/ext/flux/Classes/Provider/AbstractProvider.php line 260
in /var/www/html/typo3conf/ext/flux/Classes/Provider/AbstractProvider.php line 384
in /var/www/html/typo3conf/ext/flux/Classes/Provider/AbstractProvider.php line 285
in /var/www/html/typo3conf/ext/flux/Classes/Integration/ContentTypeBuilder.php line 181
in /var/www/html/typo3conf/ext/flux/Classes/Integration/HookSubscribers/TableConfigurationPostProcessor.php line 124
in /var/www/html/typo3conf/ext/flux/Classes/Integration/HookSubscribers/TableConfigurationPostProcessor.php line 65
in /var/www/html/typo3conf/ext/flux/Classes/Integration/HookSubscribers/TableConfigurationPostProcessor.php line 41
in /var/www/typo3_src/typo3_src-11.5.14/typo3/sysext/core/Classes/Utility/GeneralUtility.php line 3117
in /var/www/typo3_src/typo3_src-11.5.14/typo3/sysext/core/Classes/TypoScript/TemplateService.php line 753
in /var/www/typo3_src/typo3_src-11.5.14/typo3/sysext/core/Classes/TypoScript/TemplateService.php line 630
in /var/www/typo3_src/typo3_src-11.5.14/typo3/sysext/core/Classes/TypoScript/TemplateService.php line 557
in /var/www/typo3_src/typo3_src-11.5.14/typo3/sysext/extbase/Classes/Configuration/BackendConfigurationManager.php line 73
in /var/www/typo3_src/typo3_src-11.5.14/typo3/sysext/extbase/Classes/Configuration/ConfigurationManager.php line 111
in /var/www/html/typo3conf/ext/flux/Classes/Service/FluxService.php line 154
....

If I use the workaround https://github.com/FluidTYPO3/flux/issues/1893#issuecomment-877077659 TableConfigurationPostProcessor->processData it works for now.

**Comment by derhansen** [comment]
Similar problem here in one project. It seems, that calling Fluid ViewHelpers like `<f:render partial='...` or `<f:be.infobox` in the `Configuration` section of a Flux content element will cause TYPO3s RedirectService to run in an endless loop while constructing the target link. 

I had to remove affected template code (replace partial rendering and remove infobox usage) in order to get working redirects again.

The suggested workaround did not work, since all flux content elements were not rendered, when affected redirect target page was uncached.

A flux core solution for this problem is however highly appreciated.

**Comment by NamelessCoder** [comment]
This was pretty hard to track down, but I found a workaround. See code comment in https://github.com/NamelessCoder/flux/commit/54f8e375356cf631f966d35059a5e119b4955069 for a detailed description.

The problem appears to only trigger in cases where TYPO3 caches are completely empty and TYPO3 attempts to parse TypoScript without knowing which extension static TS templates are in play. In this case, TYPO3 calls the hook method that Flux uses to attach static TS but sets the flag that Flux normally uses to determine if static TS should be generated, to false. This in turn causes recursion because Flux will internally attempt to read TS.

It's kind of a chicken-and-egg problem - parsing of TS while TS is being parsed. In almost every case this is safe to do because the flag Flux uses is set to `true` which prevents multiple executions of the hook method. But there is this one edge case that you found here in which it is NOT safe to do. The linked patch prevents recursion in this edge case.
