### ISSUE TITLE
Flux TCA configuration overrides colPos

### ISSUE THREAD

**Issue by wmarie-joseph** [FluidTYPO3/flux#2063]
Hello,

TYPO3 version : 11.5.22
Flux version :  9.6.1
containeritems version : 4.0.0
Mask version : 7.2.10

I'm using flux for my typo3 website, with custom contents and i realized that flux configuration is overriding other extensions such as containeritems and mask.

The overrides are creating conflicts with "colPos" which shows "INVALID VALUE" next to colPos, for containeritems and mask children. Example below :

![image-2022-12-05-10-20-53-612](https://user-images.githubusercontent.com/110893514/217213925-4f691e23-789f-444a-8e8d-8ecffea74df4.png)

What i did to hotfix this issue,  i commented these lines in Configuration/TCA/Overrides/tt_content.php : 

```php
//$GLOBALS['TCA']['tt_content']['columns']['colPos']['config']['itemsProcFunc'] =
//    \FluidTYPO3\Flux\Integration\Overrides\BackendLayoutView::class . '->colPosListItemProcFunc';
```

This hotfix does not break the functionalities that i am using on my website, for now. 

Is there any way to remove this hotfix and resolve my problem with an official release ?

Thanks in advance :3 !

Best regards

W

**Comment by NamelessCoder** [comment]
Hi @wmarie-joseph,

This is a known and very old problem with `itemsProcFunc` - the reason is that this setting is mutually exclusive: whichever extension sets this configuration *last*, is the only configuration that will be respected. While Flux doesn't strictly depend on this, it is necessary if you want your editors to be able to move a child content element from one column to another, from within the editing interface. Drag-and-drop or cut-and-paste through the page module works regardless.

In this case the problem appears to be EXT:mask registering an `itemsProcFunc` for `tt_content.colPos` and this being overridden by Flux. EXT:containeritems does not register an `itemsProcFunc` and is not affected.

What you *can* do, assuming you are fine with losing the functionality described above, is to inspect the generated TCA while your hotfix is applied, then create your own TCA override which forces the value of `itemsProcFunc` that you see with your hotfix applied, and add this TCA override in an extension that depends on, and therefore loads after, Flux.

Doing this means that you no longer require a hotfix change in a source file of Flux.

Lastly, for the record: using EXT:mask along with Flux introduces an edge case, albeit a minor one: if you have a content element with UID `9` that has nested content areas and one of those content areas has the number `99` then rendering child content of this column in the frontend will output every inline Mask element. Unfortunately, Mask did not opt for a negative colPos number which would have prevented this edge case (but it is quite unlikely to ever cause any problems, given that it is so very specific to a single UID of tt_content combined with a rarely used column number).

I will consider implementing a workaround in Flux to do something similar to how Mask proxies existing `itemsProcFunc` entries - technically it creates invalid TCA but it may be the only workaround possible. **This workaround would however not be backported to current versions of Flux and would only be part of the next release which will be `10.0.0`.**
