### ISSUE TITLE
addToAllTCAtypes not working on flux elements

### ISSUE THREAD

**Issue by MediKathi** [FluidTYPO3/flux#2064]
Hello,

It seams that 

`\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addToAllTCAtypes('tt_content', 'appearance', '', 'after:layout');`

is no longer working.

I had to replace it with this:
`\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addFieldsToPalette('tt_content', 'frames', 'appearance', 'after:layout');`

in order to get the Field back to the form.

Currently in use:
Typo3 11.5.24
Flux 9.7.2

**Comment by NamelessCoder** [comment]
Hi @MediKathi,

This could be because the TCA from Flux elements has to be added through a hook and therefore probably doesn't exist yet at the time where your TCA is added. By adding the field in the palette instead you are circumventing this, because the palette setup exists before Flux adds TCA. I'm sorry to say that there does not appear to be any other way for Flux to add this dynamic TCA (I tried many, many different ways and this is the only one that consistently works on all supported TYPO3 versions).

There is only one workaround that I can think of which might let you add the field with `addToAllTcaTypes` - and that is to use the same event that Flux uses: https://github.com/FluidTYPO3/flux/blob/development/Classes/Integration/Event/BootCompletedEventListener.php. I am however not sure if the Event subsystem will actually order event listeners correctly based on Composer dependency ordering - but if it does, you can listen for this even and place your call to `addToAllTcaTypes` in the execute method of your event listener. You just need to make sure that whichever extension you do this from, is set to depend on Flux.
