### ISSUE TITLE
Are custom form variables inside form fields supported? They fail now for me

### ISSUE THREAD

**Issue by BenjaminBeck** [FluidTYPO3/flux#2089]
I do use them like this for some customisation i made:

``` HTML
<flux:field.inline.fal name="image1" label="Bild 1" minItems="0" maxItems="1" collapseAll="true">
     <flux:form.variable name="forceCropRatio" value="{485/250}"/>
</flux:field.inline.fal>
```

This gives a exception like:
![image](https://github.com/FluidTYPO3/flux/assets/1185872/991b4038-f50d-4f77-95c2-0cae807f8496)

A fix like 
https://github.com/BenjaminBeck/flux/commit/26cba5fb7dcd1750f398f3be3acdb7e41015f3ff
does prevent the exception atm for me. I did not test if the variable is available.

**Comment by NamelessCoder** [comment]
Form variables are designed for use (as direct children) with only the root container element, `flux:form`. What is the use case for placing them elsewhere? If I am reading your patch correctly, it would resolve the Form instance anyway which is equivalent to using `flux:form.variable` as direct child of `flux:form` as it was intended.

A proper exception may be the right solution here, rather than silently assigning the variable to the root instead of the parent inside which it is used. Flux shouldn't give the impression that `flux:form.variable` can assign variables to other elements than `flux:form`.

**Comment by NamelessCoder** [comment]
I've made a change to allow flux:form.variable as child of any Flux component. Although variables only have a purpose in some limited cases (form, column etc.) the `variables` array was universally supported and this ViewHelper makes sense to use as a more verbose and simplified syntax alternative to specifying variables with this array.

For anyone reading this: Flux form fields have no natively supported variables. Benjamin's use case above implies that he's doing something with the form fields beyond Flux's native feature set. Which is fine, but it's not going to do anything out of the box on a vanilla Flux implementation ;)
