### ISSUE TITLE
Typo3 12 Registering own PageProvider in ext_localconf leads to an error

### ISSUE THREAD

**Issue by mrwhy-orig** [FluidTYPO3/flux#2102]
I'm in the process of upgrading a project to v12.

I'm facing an error while using an own PageProvider.

When I'm registering my PageProvider in ext_localconf with:

`\FluidTYPO3\Flux\Core::registerConfigurationProvider('BH\BHTemplates\Provider\PageProvider');`

I receive an error after clearing the caches. 

**_The default controller for extension "Flux" and plugin "Page" can not be determined. Please check for TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php._**

Reloads are leading to a different error: 

**_Typed property FluidTYPO3\Flux\Provider\PageProvider::$pageService must not be accessed before initialization_**

If i remove my registration the first error only appears once while filling the caches after that it is gone.

I would like to get rid of both errors ;)

Any ideas?

**Comment by NamelessCoder** [comment]
The first error is known and at this time there is no solution.

The second error is most likely caused by your custom provider class subclassing Flux's PageProvider and defining a custom `__construct` method but not calling `parent::__construct()` within that method (safest) or manually creating an instance of Flux's PageService and assigning that to `$this->pageService`(not safe, may break in future).

**Comment by mrwhy-orig** [comment]
Thank you very much @NamelessCoder while refactoring the `parent::__construct()` call was removed by accident. That part is working now.

For the cache warmup do you relate to this #1975 ? Or is there another one? Do you have a short explanation for this (don't wanna waste your time) or maybe a hint where to start to resolve it?

**Comment by NamelessCoder** [comment]
It's kind of a long story but the short version is:

* When an instance of ConfigurationManager is created, it is persisted (as SF DI service in the DI container) throughout the same request with no way to replace the instance.
* Some Fluid ViewHelpers (outside of Flux) use ConfigurationManager - e.g. f:form.
* Whenever the Fluid parser runs into a ViewHelper like this, the instance of ConfigurationManager is created.
* This instance is then either a FrontendConfigurationManager or a BackendConfigurationManager. It used to be that this was selected based on `TYPO3_MODE` but now it is based on the application type set in the application context.
* Flux configuration *must* be loaded at a point before this request is fully initialized, and because Flux is incapable of determining if we are in BE or FE context, and because the page context that is requried by a FrontendConfigurationManager may or may not exist, Flux must create a simulated request of type BE.
* Because of this, any combination of Flux-based template which uses any ViewHelper which uses a ConfigurationManager causes SF DI to create a BackendConfigurationManager as soon as the template is parsed (and a VH instance is created which has a dependency on a ConfigurationManager).
* SF DI then holds on to this ConfigurationManager instance which is now a BackendConfigurationManager.
* If this happens in an FE request, we then have the situation that the application type once it is set, is FE - but the ConfigurationManager instance that DI hangs on to, is BackendConfigurationManager.
* This causes the particular error because BackendConfigurationManager is incapable of resolving plugin configurations.

So this all boils down to the fact that FE/BE is now determined by TYPO3 very late in the request processing. Yet for various reasons related to sequence, Flux has no option but to perform Fluid template parsing earlier in the request processing.

Once the Fluid template is compiled, this is no longer a problem (because a ViewHelper instance no longer needs to be created). This is why you only see the error on one request and not any subsequence ones, until you once again flush the system caches.

I have no way to solve this chicken-and-egg problem, as you can see. I can't NOT parse Fluid template files or no forms could be extracted - and I can't remove any incorrect instance of ConfigurationManager once Flux is done parsing templates once it is created. It is outside my control whether one or more of the templates that get registered as Flux templates do or don't use a ViewHelper that requires a ConfigurationManager. It may be that my only option is to create a chimera/proxy ConfigurationManager that is both FE and BE capable and determines what the context is on a continuous basis; so that it functions as an emulated BackendConfigurationManager until the TYPO3 request and application type is available, then functions as whichever type of BE/FE ConfigurationManager once the application type is set. But I haven't had time to attempt this yet.

(I'm getting so sick and tired of the refactorings going on within TYPO3 these days. Every major version has broken something new by shuffling things around and making more assumptions about what type of code is executed at particular times, moving the determination of context further and further down the request processing line -yet never taking the time to actually adjust those pieces that demand a certain context, e.g. ConfigurationManager...)

**Comment by mrwhy-orig** [comment]
> by shuffling things around and making more assumptions about what type of code is executed at particular times, moving the determination of context further and further down the request processing line -yet never taking the time to actually adjust those pieces that demand a certain context, e.g. ConfigurationManager...)

I feel you, and thanks for the heads up.

Maybe a silly question, but couldn't we get around the context determination by explicitly requesting a FrontendConfigurationManager / BackendConfigurationManager?

**Comment by NamelessCoder** [comment]
Yep, it's a rather tough nut to crack, this one. Made harder by the fact that it's actually not Flux loading any of the classes that cause the problem, so we can't just load another class - it's all either core code or third-party code that triggers it by depending on classes that depend on ConfigurationManager.

**Comment by NamelessCoder** [comment]
Try `dev-development` now and see if that fixes the issue...

**Comment by mrwhy-orig** [comment]
I would also argue that it is in fact a bug in the core. It can't be intentional. Did you write a bug report for the core?

**Comment by NamelessCoder** [comment]
> I would also argue that it is in fact a bug in the core. It can't be intentional. Did you write a bug report for the core?

I didn't, because to be completely frank, I know what the reply will be - it's not intended to use this particular class (or even just parse Fluid templates) at this particular time in the request processing sequence, and the reaction would more likely be to simply shut down the entire ability to even do this which would in the end harm Flux much, much, much more than having to create these overrides could ever do.

**Comment by mrwhy-orig** [comment]
I see. I'm just not sure if thid kind of refactorings of the core will benefit the project in the long run. I see more and more people complaining about the decisions the core team make. 

Thanks for the update. I does work for me in 2 different installations.
