### ISSUE TITLE
Page cannot be edited

### ISSUE THREAD

**Issue by steffen-hph** [FluidTYPO3/flux#2116]
It is not possible to edit pages in the backend while Flux is active. It seems that the extension configuration provides an option which causes the error when it is active (default) "Page Integration [basic.pageIntegration]", however this should not be active by default, we think, especially if it can cause errors.

We don't use Flux Page Template. If we disable this setting it is possible to edit the page settings. 
But even if we used that, it wouldn't be possible to set the template, we think.

TYPO3 12.4.4
Flux: Latest from today (2023-08-09)

<img width="1165" alt="Clipboard - 9  August 2023 12_26" src="https://github.com/FluidTYPO3/flux/assets/78363413/3dc03d1f-9d8d-4dce-b874-d7770dfedd7c">

**Comment by NamelessCoder** [comment]
Page integration is enabled by default and this wouldn't normally cause an issue. The field mentioned in your error message is always added in SQL schema (no conditions are possible here) and when the option is enabled (or is not defined yet), the field is added as page rootline field. When this is the case, the error above should be impossible to encounter, unless:

* You intentionally did not add the field through SQL schema update.
* One of your other extensions is manipulating `$GLOBALS['TYPO3_CONF_VARS']['FE']['addRootLineFields']` in a way that removes the value Flux inserts - note that when you manipulate this variable, it should always be done with a concatenation and added comma, e.g. `$GLOBALS['TYPO3_CONF_VARS']['FE']['addRootLineFields'] .= ',myfield';`

But perhaps more obvious, unless the `basic.pageIntegration` option is either defined and set to `true`, or not defined at all (and defaulted to `true`) then the PageProvider should not be registered at all and there would be no way that the error can be raised.

If neither of the two suggested causes above apply, I would appreciate a full stack trace so I can see what causes the PageProvider to be unexpectedly invoked.

**Comment by steffen-hph** [comment]
We have checked the two things you mentioned. We also checked the $GLOBALS array just before the line where the error occurred, and the Flux fields are included in the string. The only third-party extension installed at the moment is Flux, so there is nothing else that can cause this problem.

[typo3_1249c4b7df.log](https://github.com/FluidTYPO3/flux/files/12310214/typo3_1249c4b7df.log)

**Comment by NamelessCoder** [comment]
@steffen-hph I'm sorry, but the log isn't helping. I'll need a stack trace so I can see the hierarchy of classes/methods that leads to this error. You should be able to get this by setting Development context.

**Comment by NamelessCoder** [comment]
Yep, that's it - thanks.

*Something* in your setup is causing an instance of PageProvider to be created and registered with Flux, even when the page integration option is disabled. I am unfortunately completely unable to reproduce the problem locally and can almost guarantee that it isn't caused by Flux itself. Something else *must* be going on to cause an instance of PageProvider to be created.

Are you absolutely 100% certain that your setup's extension configuration for Flux contains `basic.pageIntegration` and that the value of this setting is `false` (not `null`!)? Two things point to this setting either being `null` or `true`:

* The instance of PageProvider is created.
* You mention that you inspect the $GLOBALS array and see the Flux page fields in `addRootLineFields`.

So either the settings are telling Flux to register the PageProvider and add these fields to the root line, or some other code in your setup is doing that.

You can call `\FluidTYPO3\Flux\Utility\ExtensionConfigurationUtility::getOptions()` in the place where this problem is triggered so you can inspect the settings. Or call `\FluidTYPO3\Flux\Utility\ExtensionConfigurationUtility::getOption('pageIntegration')` to inspect just that one setting. As mentioned, the value must be `false` - `null` is treated as "not set" and will default the setting to `true`.

Hope this helps you track it down.

**Comment by steffen-hph** [comment]
Thank you for your help again!

We tested it again but we weren't able to force the error. We used your newest version of Flux, so maybe you changed something without knowing it? It doesn't really matter why, but it seems to work now.

I therefore close the ticket.
