### ISSUE TITLE
BUG: toggle button missing for grid based content element on TYPO3v11

### ISSUE THREAD

**Issue by sdelcroix** [FluidTYPO3/flux#2137]
**I have checked that the bug exists in the `dev-development` branch**
_Yes._

**I have checked that there are no already open issues or recently closed issues about this bug**
_Yes._

**Describe the bug**
In TYPO3v11, the toggle button of grid based content element is not displayed in "Page" module.

**To Reproduce**
Steps to reproduce the behavior on TYPO3v11 :
1. Go to 'Page' module
2. Add a flux based content with grid
3. See there's no toggle button on content "toolbar"

**Expected behavior**
The toggle button should be displayed on content "toolbar"

**Screenshots**
None

**Additional context**
This is related to #2086 

In this commit ( 1b9eaaa ), the "recStatInfoHooks" hook registration has been strictly restricted to TYPO3v10 and below in `ext_localconf.php`: https://github.com/FluidTYPO3/flux/commit/1b9eaaaabd52e9392f68c7b8afec15a91f46f99a#diff-5e15ae082e9095bfca62c8b83a7a2cdbcf8e5ac4c750ab8c832aa12cce7d7a74R102
But this hook has been removed from the core since TYPO3v12 ( https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-98441-HookRecStatInfoHooksRemoved.html ).

Maybe a typo ?
If I raise the restricted version to TYPO3v11 and below, as following, the toggle button is displayed and fully functional :
```
if (version_compare(\TYPO3\CMS\Core\Utility\VersionNumberUtility::getCurrentTypo3Version(), '12', '<'))  
{
        $GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['GLOBAL']['recStatInfoHooks']['flux'] =
            \FluidTYPO3\Flux\Integration\HookSubscribers\ContentIcon::class . '->addSubIcon';
```

**Comment by NamelessCoder** [comment]
This functionality had to be removed.

The hook in question is deprecated on 11.5 and triggers several deprecation notices for every page module request - the PSR event that was implemented as substitute only triggers in list view and therefore cannot add the icon. Rather than allow the dispatching of thousands of deprecation notices, and since the feature would inevitably have to be removed later anyway and would not be availble on v12, I opted to just remove it early.

If you want it back and don't mind the thousands of deprecation log messages then you can register the hook in question in the ext_localconf.php file of your provider extension. But beware, there is no alternative if/when you upgrade to TYPO3v12.

**Comment by sdelcroix** [comment]
Thanks for this clear explanation @NamelessCoder ;)
I admit that I did a really quick test and didn't look at any deprecation notices.
I understood in #2086 that it was fixed for page module in v11 too :)
I don't really need this feature, I just thought it was a "typo".
