### ISSUE TITLE
BUG: foobar fails when baz

### ISSUE THREAD

**Issue by dennismetz** [FluidTYPO3/flux#2165]
**I have checked that the bug exists in the `dev-development` branch**
Yes

**I have checked that there are no already open issues or recently closed issues about this bug**
Yes

**Describe the bug**
We have created some elements with Flux but for all elements where flux:field.file is used the file list tree does not load and we cannot select images anymore.

**To Reproduce**
Create a new content element, use flux:field.file and try to select an image.
Example code attached:

```
<f:comment><!-- Backend form --></f:comment>
<f:section name="Configuration">
    <flux:form id="linkTeaser" label="LLL:EXT:sample/Resources/Private/Language/locallang.xlf:fluidContent.linkTeaser" >

        <flux:form.option name="options">
            <flux:form.option.group value="Content"/>
        </flux:form.option>

        <flux:field.input label="Titel" name="title"/>
        <flux:field.file name="image" label="Bild" enabled="1" showThumbnails="1" internalType="file" useFalRelation="true"/>
        <flux:field.input label="Linktext" name="linktext"/>
	    <flux:field.input label="Link" name="link" config="{renderType:'inputLink'}" />
    </flux:form>
</f:section>
```

![grafik](https://github.com/FluidTYPO3/flux/assets/17856901/b7b3a8f2-1ec8-4ecc-88fb-2ff38cc5b8d0)

**Expected behavior**
Display of the file selection with all images, folders, etc.

**Additional context**
Latest Version of TYPO3 12, Flux, everything up2date.

Is there a migration from flux:field.file to flux:field.inline.fal? There is an update script for TYPO3 10, but not for 12, right?
Does it generally make sense to change the whole thing to flux:field.inline.fal?

**Comment by NamelessCoder** [comment]
As you're probably already aware, `flux:field.file` will not work the same on TYPO3v12 as it did on earlier TYPO3 versions. Other issues describe the reasons for this in great detail. The TL;DR is: Flux cannot recreate compatibility for this field type which was forcibly removed from TYPO3 itself in version 12. You _must_ find an alternative.

> Is there a migration from flux:field.file to flux:field.inline.fal? 

There is not, at least not an official one and no unofficial ones that I'm currently aware of. You're far from the first person to have this problem but I don't know if anyone else has solved it with a migration _and been nice enough to publish the migration script they used_.

> There is an update script for TYPO3 10, but not for 12, right?

Correct; that upgrade script however is only dealing with a much older Flux change and was only needed a couple of major versions and many years ago - it rewrites colPos values. It does not change file references at all.

> Does it generally make sense to change the whole thing to flux:field.inline.fal?

That field type is as of now (TYPO3v12 and future) the only one that will work to let you select a file as a `sys_file_reference` so that is the recommended approach. I know of others who tried using an `inputLink` field type with files as only link target type but this comes with multiple drawbacks (for one, it requires parsing of the field value to extract a UID of a file and AFAIK, will not support cropping or scaling of any kind).

If you go with `flux:field.inline.fal` or generic `flux:field type="file"` (which are the same thing on v12) see also https://github.com/FluidTYPO3/flux/issues/2139#issuecomment-2204424364.
