### ISSUE TITLE
cannot override templateRootPath in TS Template constants

### ISSUE THREAD

**Issue by erredeco** [FluidTYPO3/flux#714]
Steps to reproduce:
1. Enviroment
- TYPO3 6.2.6
- view 	2.0.0
- vhs 2.1.4
- flux 	7.1.2
- fluidpages 	3.1.2
- fluidcontent 	4.1.1 

2.Create a "frontend provider extension" (I call it bhsiteconf)
3.Provide templateRootPath, partialRootPath, layoutRootPath in constants.txt file; in my ext_tables.php I put:

TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addStaticFile($_EXTKEY, 'Configuration/TypoScript', 'My Provider extension for pages and content');

so in EXT:bhsiteconf/Configuration/Typoscript/constants.txt:

plugin.tx_bhsiteconf.view {
	templateRootPath = EXT:bhsiteconf/Resources/Private/Templates/
	partialRootPath = EXT:bhsiteconf/Resources/Private/Partials/
	layoutRootPath = EXT:bhsiteconf/Resources/Private/Layouts/
}

and in EXT:bhsiteconf/Configuration/Typoscript/setup.txt:
plugin.tx_bhsiteconf.view {
	templateRootPath = {$plugin.tx_bhsiteconf.view.templateRootPath}
	partialRootPath = {$plugin.tx_bhsiteconf.view.partialRootPath}
	layoutRootPath = {$plugin.tx_bhsiteconf.view.layoutRootPath}
}

In Templates, put a file called HomePageTemplate.html with the following content:
{namespace flux=FluidTYPO3\Flux\ViewHelpers}
{namespace v=FluidTYPO3\Vhs\ViewHelpers}
&lt;f:layout name="Home" /&gt;
&lt;f:section name="Configuration"&gt;
	&lt;flux:form id="fluidfluxpage" label="Home Page Template" icon="{f:uri.resource(path: 'Icons/Page.gif')}"&gt;
	&lt;flux:form.sheet name="settings.basics"&gt;   
		&lt;flux:grid&gt;
			&lt;flux:grid.row&gt;
				&lt;flux:grid.column colPos="0" name="settings.column0" /&gt;
			&lt;/flux:grid.row&gt;
		&lt;/flux:grid&gt;
	&lt;/flux:form.sheet&gt;
	&lt;/flux:form&gt;
&lt;/f:section&gt;
&lt;f:section name="Main"&gt;
&lt;h1&gt;OLD TEMPLATE&lt;/h1&gt;
&lt;v:content.render column="0" /&gt;
&lt;/f:section&gt;

in Layouts put a file called Home.html with the following content:
{namespace v=FluidTYPO3\Vhs\ViewHelpers}
&lt;f:layout name="Home" /&gt;
&lt;f:render section="Main" /&gt;

4. in the root page of TYPO3, put a TS template (Root template), load bhsiteconf as the last extension 
5. Till now, everything should be fine

6. Create the folder EXT:bhsiteconf/Resources/Private/Templates-other/ and copy HomePageTemplate.html renaming it HomePageTemplateOther.html 
Its content:
{namespace flux=FluidTYPO3\Flux\ViewHelpers}
{namespace v=FluidTYPO3\Vhs\ViewHelpers}
&lt;f:layout name="HomeOther" /&gt;
&lt;f:section name="Configuration"&gt;
	&lt;flux:form id="fluidfluxpage" label="Home Page Template" icon="{f:uri.resource(path: 'Icons/Page.gif')}"&gt;
	&lt;flux:form.sheet name="settings.basics"&gt;   
		&lt;flux:grid&gt;
			&lt;flux:grid.row&gt;
				&lt;flux:grid.column colPos="0" name="settings.column0" /&gt;
			&lt;/flux:grid.row&gt;
		&lt;/flux:grid&gt;
	&lt;/flux:form.sheet&gt;
	&lt;/flux:form&gt;
&lt;/f:section&gt;
&lt;f:section name="Main"&gt;
&lt;h1&gt;NEW TEMPLATE&lt;/h1&gt;
&lt;v:content.render column="0" /&gt;
&lt;/f:section&gt;

7. copy the file Home.html in EXT:bhsiteconf/Resources/Private/Layouts, renaming it HomeOther.html
Its content:
{namespace v=FluidTYPO3\Vhs\ViewHelpers}
&lt;f:layout name="HomeOther" /&gt;
&lt;f:render section="Main" /&gt;
&lt;p&gt;Bla bla bla&lt;/p&gt;

8. load the FE: the following error appears:
"C:/wamp/www/typo3.local.development.it/typo3conf/ext/bhsiteconf/Resources/Private/Templates-other/Page/HomePageTemplate.html" is not a valid template resource URI.

**Comment by NamelessCoder** [comment]
Possible causes going from your description:

1. You don't say where you define the constant for layoutRootPath but I assume it is in the root template. If not, that's a possible cause.
2. `Templates-other` is a very bad folder name especially on Windows. You should stick with the approved, known-to-be-working, `UpperCamelCaase` naming always, without exception, for all folders containing fluid templates and the fluid templates in those folders.
3. The name of your copied template is different and therefore will not match your currently selected templates in page properties. You may need to update one or more pages to select the differently named template because the template selections identify the template by name and may contain the old name. You should avoid renaming *templates*, but may rename *layouts* and *partials* freely as long as you are sure you also rename them in every place where you reference the layout or partial. But consider *templates* as having fixed names which are determined by the controller and its actions, if nothing else then because renaming the references to the template is a lot more complicated than when dealing with layouts and partials (e.g. not just a matter of fluid templates but also controllers, page properties, etc).

I'll consider this one solved with the source of your problem most likely being (3).
