### ISSUE TITLE
Argument "displayCond" not work into other "flux:form.sheet"

### ISSUE THREAD

**Issue by typo3ua** [FluidTYPO3/flux#732]
I have code:
~~~
[...]
<flux:form.sheet name="options1">
	<flux:field.checkbox name="checkbox1" default="1" requestUpdate="TRUE" />
	<flux:field.checkbox name="checkbox1" default="0" displayCond="FIELD:checkbox1:=:1" />
</flux:form.sheet>
<flux:form.sheet name="options2">
	<flux:field.input name="input1" displayCond="FIELD:checkbox1:=:1" />
	<flux:field.input name="input1" />
</flux:form.sheet>
[...]
~~~
Argument "displayCond" for field ""options2" -> "input1" not work into other group fields ""options1" -> "checkbox1""

What is that, error or ...???

**Comment by NamelessCoder** [comment]
You have duplicate field names, which means that the second field will overrule the first one in the object that is created. The `displayCond` does not prevent this - it only dictates whether or not the field is rendered - it will always be added and thus will always overwrite the existing, same-named field.

To avoid, do not use duplicate field names.

If this still does not work, please report this as a bug to the TYPO3 core bug tracker - the `displayCond` handling is not done by Flux; we simply transfer the property to the TCEforms array that TYPO3 then renders. But I'm pretty sure the problem is unpredictability caused by duplicate field names.

**Comment by typo3ua** [comment]
I meant ...
~~~
[...]
<flux:form.sheet name="options1">
    <flux:field.checkbox name="checkbox1" default="1" requestUpdate="TRUE" />
    <flux:field.checkbox name="checkbox2" default="0" displayCond="FIELD:checkbox1:=:1" />
</flux:form.sheet>
<flux:form.sheet name="options2">
    <flux:field.input name="input1" displayCond="FIELD:checkbox1:=:1" />
    <flux:field.input name="input2" />
</flux:form.sheet>
[...]
~~~
Argument "displayCond" for field ""options2" -> "input1" not work into other group fields ""options1" -> "checkbox1""
