### ISSUE TITLE
no valid handling of contained CEs

### ISSUE THREAD

**Issue by pi-phi** [FluidTYPO3/flux#753]
I defined container CEs with fluidcontent and updated to the latest extension versions (flux, fluidcontent, vhs).
After the update no contained CEs could be edited:
existing childs were no longer visible in page view, there are no Icons to insert new CEs. differnt approaches with variants for name, label, colPos in definition and fields in database result always in [ INVALID VALUE "..." ] and otherwise empty dropdowns for the fields 'Column', 'Content area of parent', 'Grid Container', 'Grid Container Columns'.

my configuration definition:
```xml
<f:section name="Configuration">
	<flux:form options="{group: 'myext', icon:'{v:extension.path.resources(path: \'Icons/myextAbcHeadings.png\', extensionName:\'myext_ces\')}'}" id="MyextAbcHeadings">
		<flux:form.sheet name="panels">
			<flux:form.section name="panels">
				<flux:form.object name="panel">
					<flux:field.input name="title" />
					<flux:field.select name="class" items="active,inactive" default="active" />
				</flux:form.object>
			</flux:form.section>
		</flux:form.sheet>
		<flux:grid name="tabs" variables="{foo:'bar'}">
			<f:for each="{panels}" as="panel" iteration="iteration">
				<flux:grid.column colPos="{v:math.sum(110,{iteration.index})}" name="content.{iteration.index}" label="righthere-{f:if(condition: panel.panel.title, then: panel.panel.title, else: 'Content, panel {iteration.cycle}')}" />
			</f:for>
		</flux:grid>
	</flux:form>
</f:section>
```
even creating new Child Content in the tab 'Relations'  resulted in new CEs in the main-column (no IRRE-records shown in BE page view).

**Comment by Idleworks** [comment]
I had a similar issue and found a solution. Maybe that helps you as well.
It seems that the "name" attribute for grid.column should not contain special characters like dashes (in my point) nor points. You could try to remove the point in your name attribute. But remember to update your database:
```sql
UPDATE tt_content SET tx_flux_column = REPLACE(tx_flux_column, '.', '');
```sql
to remove all points.

**Comment by NamelessCoder** [comment]
Philipp is absolutely correct. The technical reason is that this is internally processed as TypoScript because the DataProvider concept implemented by the TYPO3 core chose this as the preferred format. I did my best to push for an array or even some structural object being the preferred format, but the end result was that a TS string is expected. Flux therefore compacts the grid configuration to a TS string before it is delivered and the array used as base will use the names of grids as keys - and this is the reason why names with dots in them doesn't work as column names.
