### ISSUE TITLE
Frontend Editing (feedit) feature support

### ISSUE THREAD

**Issue by f000** [FluidTYPO3/flux#754]
Would be possible to implement support for TYPO3 Frontend Editing feature?

**Comment by erredeco** [comment]
+1 for this :)

**Comment by NamelessCoder** [comment]
Flux fields (like other FlexForm fields) can be rendered in the frontend editing extension so I assume this has to do with the markup needing some additional wrappers when editing is enabled. The problem here is that in FluidTYPO3 (and any other Fluid-based content rendering!) the responsibility of generating markup is put entirely on the developer; it is not manipulated unless each developer allows it to be manipiulated - and there is no convention for this sort of manipulation.

This subject is such a huge one that I barely know where to begin in order to explain how complicated it would be. It all boils down to the crazy amount of overrides that would be required in order to operate any Fluid template in two modes; one to render the output and one that lets users open various edit panels (not to speak of **styling** such edit panels). We just don't have the manpower to take care of something like that - but theoretically it is possible to introduce enough overrides that any Fluid template can add any amount of additional markup before outputting the content. I wouldn't want to use a system with that many overrides, but in theory you could do it. Cannot emphasise the **in theory** part enough, though. There are hundreds of possible dead-end blockers that I cannot predict.

So for practical reasons I have to reject this as a feature request. You're very welcome to continue discussing/investigating how it would be possible to replicate this CSC-based feature in a Fluid context, but it would not specifically relate to FluidTYPO3 - rather Fluid itself.

Honest opinion: I would focus on improving the backend editing experience through feature requests to the core itself. The separation of FE/BE contexts isn't just there for historical reasons - and in the future I expect to see the TYPO3 core use more and more selective loading of extensions, hooks etc. when in FE/BE context since this is a very effective way to both gain performance and increase security.
