### ISSUE TITLE
inline.fal in a form.container

### ISSUE THREAD

**Issue by lucasinteractive** [FluidTYPO3/flux#759]
Hi,
i try to wrap the fal in container. Example:

    <flux:form.container name="settings.foreground">
        <flux:field.inline.fal id="image" name="image" multiple="false" maxItems="1" allowedExtensions="'gif,jpg,jpeg,tif,tiff,bmp,pcx,tga,png,pdf,ai'" />
    </flux:form.container>
    <flux:form.container name="settings.background">
        <flux:field.inline.fal id="image" name="image" multiple="false" maxItems="1" allowedExtensions="'gif,jpg,jpeg,tif,tiff,bmp,pcx,tga,png,pdf,ai'" />
    </flux:form.container>

Now i added a picture to the first fal. After save the image is also shown in the second fal field. And if i change the second or first field ist duplicated to the other field.

**Comment by NamelessCoder** [comment]
Hi @lucasinteractive - I'm sorry to say that this is a long running problem in TYPO3. The situation is that the FAL relation field types were initially created for purely record relations, and the support for using the same field in a FlexForm context is more of an afterthought; an adaptation that allows the field to store at least basic relations when used in a FlexForm.

Technically, the issue is that when you save a record that has a FlexForm with a FAL field, the FAL relation is stored using the field name *without considering the nesting* which means that all your relations have the field name `image` after they're saved. Of course, when you reload the form, the methods that pre-fill the FAL relation fields are then detecting the same relation in all fields.

The bug (which I would call it) affects:

* FAL relations inside a raw `section` TCEforms element (Flux equivalent: `flux:form.container`).
* FAL relations inside an `object` section (Flux equivalent: `flux:form.container`).
* FAL relations inside an `object` inside a repeatable `section` (Flux equivalent: `flux:form.section` + `flux:form.object`).
* And, I induce, any other custom or core IRRE relation.

The solution would be to parse the nesting structure of the FlexForm when determining which field name to use when the relation is stored in the database. This would allow TYPO3 to store a field name like `settings.foreground.image` in your case, rather than simply `image`. If the method that renders the field is then also capable of determining the same (I believe this needs to be added) the puzzle should be solved, allowing any combination of nested FAL/IRRE fields inside and outside FlexForms in the same way.

So I'm sorry but I have to refer you to the core's bug tracker to create this issue and push for support: https://forge.typo3.org/projects/typo3cms-core/issues

...and we as well as the FluidTYPO3 community would be very happy if a fix was made ;)

**Comment by DenisMir** [comment]
@NamelessCoder Do you know if an issue has been created in the typo3 cms core bugtracker regarding this problem untill now?

**Comment by NamelessCoder** [comment]
@DenisMir I haven't checked lately.

**Comment by cweiske** [comment]
TYPO3 core bug created: [Bug #71239: FAL relation + flexform config: Use full setting path as name](https://forge.typo3.org/issues/71239).
