### ISSUE TITLE
Get Page UID in Flux Configuration section

### ISSUE THREAD

**Issue by robsonrobi** [FluidTYPO3/flux#785]
Hello.

It is more a question than an issue. Is it possible to get the current page uid inside the Flux Configuration Section? I like to make a select field in the form an depending on the current uid in the pagetree i like to set different items. That would be great.

When i use debug {_all} inside Configuration Section i get two outputs, the second debug has a record object the first not... :-(

May be someone has an idea?

**Comment by andrij2012** [comment]
@robsonrobi, you might use {record.pid} It contains the current page uid.

**Comment by robsonrobi** [comment]
No, the <Configuration>-Section is rendered twice. Using the Extbase Debugger, {record.pid} is an extrem negative value. Coming into the second render process, the {record.pid} is correct. I need the {record.pid} to set specific items="". But items="" is interpreted in the first render-process, where i do not have the information. Saving the element shows then correct values, because the {record.pid} exists. But you need to save the element, which is not clear for the person that handles the content

**Comment by xf-** [comment]
Hi,
fluidpages or fluidcontent?

**Comment by NamelessCoder** [comment]
Problem confirmed, but I'm afraid this is one of those things that *could* be solved inside Flux itself, but *shouldn't*. The reason you are getting this extremely low negative value is that it is a *session array index reference which stores target columns and areas*.

In other words, you are running into this for one of two reasons:

1. This could be a bug. If Flux failed to process the record correctly, your bad integer value may have been unexpectedly persisted. In which case, you'd need to *move the content element or page* and it should repair itself. If this is your problem and you are able to determine a cause we would appreciate a bug report about that ;)
2. This is happening while you are moving an element or creating it in a Flux content area. If this is the case then I'm afraid this one is expected behavior.

If you are hitting case no. 2, there are some things you can do about it:

* You can use `displayCond` to hide the selector until the PID is a nice, positive value.
* You can use a fluid condition to achieve the same.
* You can use TCA markers in the "condition" of your select field which reference the record values rather than uses the `{record.pid}` variable. Doing that will make TYPO3 read this value from the DB rather than memory and should always yield the correct PID.

With either solution you will also have the option to make a message output (a `custom` field type) which gets displayed if the record has not yet been saved or is in the process of being moved - but perhaps the more user friendly solution would be TCA markers in the condition.

See also: https://docs.typo3.org/typo3cms/TCAReference/Reference/Columns/Select/Index.html#foreign-table-where
