### ISSUE TITLE
Defining width of <flux:grid>

### ISSUE THREAD

**Issue by doerler** [FluidTYPO3/flux#791]
Making it possible to define a width for **\<flux:grid>** would be a nice feature.
In earlier versions, it was possible to arrange the grid and the preview section side by side using **\<flux:widget.grid />**.
Example:
```
<f:section name="Preview">
    <div style="float: left; width: 33%;">
        ###PREVIEW_CONTENT###
    </div>

    <div style="float: right; width: 66%">
        <flux:widget.grid/>
    </div>
</f:section>
```
Now (Flux 7.2), if my preview looks like this:
```
<f:section name="Preview">
    <div style="float: left; width: 33%;">
        ###PREVIEW_CONTENT###
    </div>
</f:section>
```
... the grid is situated below anyway because there is no way to influence the width of the grid and the table in the backend always has a width of 100% (\<table class="**flux-grid**"> **\->** the class **.flux-grid** has **width: 100%;**).
It would be nice if applying a width to **\<flux:grid>** sets the width of this table.

**Comment by doerler** [comment]
Another way of solving this problem (instead of giving \<flux:grid> a parameter) could be defining a new option to set the width in the already existing preview option:
```
<flux:form.option name="preview" value="{width: '66%', toggle: 0}" />
```

In this case, the width of the grid table could be set like in my attached diff file:
```diff
diff --git a/Classes/View/PreviewView.php b/Classes/View/PreviewView.php
index 0d9400f..9b016f8 100644
--- a/Classes/View/PreviewView.php
+++ b/Classes/View/PreviewView.php
@@ -42,6 +42,7 @@ class PreviewView {
 	const MODE_PREPEND = 'prepend';
 	const MODE_NONE = 'none';
 	const OPTION_TOGGLE = 'toggle';
+	const OPTION_WIDTH = 'width';
 
 	const PREVIEW_SECTION = 'Preview';
 	const CONTROLLER_NAME = 'Content';
@@ -120,7 +121,8 @@ class PreviewView {
 		if (FALSE === is_object($form) || FALSE === $form->hasOption(self::OPTION_PREVIEW)) {
 			return array(
 				self::OPTION_MODE => $this->getOptionMode(),
-				self::OPTION_TOGGLE => $this->getOptionToggle()
+				self::OPTION_TOGGLE => $this->getOptionToggle(),
+				self::OPTION_WIDTH => $this->getOptionWidth()
 			);
 		}
 
@@ -156,6 +158,17 @@ class PreviewView {
 	}
 
 	/**
+	 * @param array $options
+	 * @return boolean
+	 */
+	protected function getOptionWidth(array $options = NULL) {
+		if (TRUE === isset($options[self::OPTION_WIDTH])) {
+			return $options[self::OPTION_WIDTH];
+		}
+		return '100%';
+	}
+
+	/**
 	 * @param ProviderInterface $provider
 	 * @param array $row
 	 * @param Form $form
@@ -227,6 +240,7 @@ class PreviewView {
 		$canToggle = $this->getOptionToggle($options);
 		$isCollapsed = $this->isRowCollapsed($row);
 		$collapsedClass = TRUE === $canToggle && TRUE === $isCollapsed ? ' flux-grid-hidden' : '';
+		$gridWidth = $this->getOptionWidth($options);
 		$gridRows = $grid->getRows();
 		$content = '';
 		foreach ($gridRows as $gridRow) {
@@ -239,7 +253,7 @@ class PreviewView {
 		}
 
 		return <<<CONTENT
-		<table cellspacing="0" cellpadding="0" id="content-grid-{$row['uid']}" class="flux-grid$collapsedClass">
+		<table cellspacing="0" cellpadding="0" id="content-grid-{$row['uid']}" class="flux-grid$collapsedClass" style="width:$gridWidth">
 			<tbody>
 				$content
 			</tbody>

```

**Comment by NamelessCoder** [comment]
This needs to be thought out in a wider perspective. Assuming for a moment that this should be done in Flux, rather than inviting a heap of new properties and options for the grid, each grid ViewHelper should accept a general `style` or perhaps even `additionalAttributes` parameter which is rendered by the PreviewView. The default width should be applied in CSS, not hardcoded through PHP.

But: note that this will only ever work in content element grids because the page grid view does not support custom attributes for grid rows/cells. As such, it is already quite bad for consistency between page and content contexts that one grid supports some features the other doesn't. My own vote would actually go toward removing the style attribute entirely (and await a proper solution in the core; one that allows for example all tag attributes to be defined rather than just colspan+rowspan).

Ideally, Flux would contain not a single line of custom HTML output. Ideally, there would be core functions to designate grids using PHP objects that support tag attributes (the TagBuilder seems an obvious choice here). That is the situation we would like to move towards and this patch would be a step away from that. It is with this reason I must reject this patch and recommend suggesting this as a core feature; one that is *also* usable through TS grid setups etc.

Alternative suggestion: adapt the TYPO3 skin and target your columns using CSS selectors; this would work for both content and page grids.
