### ISSUE TITLE
Convention-based template icons not set correctly

### ISSUE THREAD

**Issue by doerler** [FluidTYPO3/flux#795]
The automatically chosen template icons are not shown as the image src is not correct.
Currently (Flux 7.2.0), the absolute server path is used.

Temporarily, I amended line 85 in file [MiscellaneousUtility.php](https://github.com/FluidTYPO3/flux/blob/7.2.0/Classes/Utility/MiscellaneousUtility.php#L70) to get it to work:
```diff
- return (TRUE === is_array($filesInFolder) && 0 < count($filesInFolder) ? reset($filesInFolder) : NULL);
+ return (TRUE === is_array($filesInFolder) && 0 < count($filesInFolder) ? str_replace(PATH_site, '../', reset($filesInFolder)) : NULL);
```

**Comment by NamelessCoder** [comment]
This patch would make other contexts unable to consume the icon because it is now a relative path. The friendly way to fix it is where the icon is being read out before it gets put in the `<img>`, but I would probably try to use the core's functions to get relative file name because it takes into consideration this relative location thing.
