### ISSUE TITLE
Error in FluxService.php on line 357 after moving content element up/down with feedit

### ISSUE THREAD

**Issue by misoe** [FluidTYPO3/flux#797]
Hi, I get this Fatal error when I tried to move down/up content elements with feedit extension in FE:

PHP Catchable Fatal Error: Argument 1 passed to TYPO3\CMS\Core\Utility\GeneralUtility::removeDotsFromTS()
must be of the type array, null given, called in /www.website.com/typo3conf/ext/flux/Classes/Service/FluxService.php on line 357
and defined in /webhosting/_typo3_src-6.2.10/typo3/sysext/core/Classes/Utility/GeneralUtility.php line 1846
TYPO3\CMS\Core\Error\Exception thrown in file
/webhosting/_typo3_src-6.2.10/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 101.

TYPO3 CMS 6.2.10, flux 7.2.0 I also tried current flux version from github but with the same error.
I can't find any solution via Google, so I hope somebody will know what can be wrong.

Thank you.

**Comment by NamelessCoder** [comment]
Error message prevented by casting potentially NULL return to array. However, this problem indicates that you possibly have another issue with your setup, since the literal meaning of this problem is "there is no typoscript whatsoever that your configurationmanager can detect and use" and you would likely see every extension breaking even after pulling the fix in question.

But, implemented all the same since it's just a value type cast.
