### ISSUE TITLE
Disable Page Layouts and Content Element

### ISSUE THREAD

**Issue by SventB** [FluidTYPO3/flux#828]
On this page (https://fluidtypo3.org/documentation/templating-manual/templating/using-templates/selecting-page-templates.html) you write

> It is important to note here that the page templates which can be selected, are all configured by TypoScript which means you can change which templates can be selected, at any point in your page tree.

but how? You provide no example and everything I tried was not successful.
For example, I thought when removing the TypoScript settings with the path to the templates

    plugin.tx_myext.view >

there will be no Page Layout to select in Page Properties, but it is.

It's also not possible this way: https://github.com/FluidTYPO3/flux/commit/8fe7e6efd1e60e81f5281e65d77343c7edf177d1

I use newest versions of flux/fluidpages/fluidcontent.

**Comment by lucasinteractive** [comment]
I'm also searching for a solution. I checked the source (fluidpages/Classes/Service/PageService.php:getAvailablePageTemplateFiles()) but all i can see is one TypoScript switch. So it seems that you only can disable backend layouts per extension with this ts snipped:

    plugin.tx_myext.view.enable = 0

So a workaround may to add an extension for each TypoScript backend layout condition.. More configuration like ```plugin.tx_myext.view.page.HomeSite.enable = 0``` would great but doesn't seems currently available.

**Comment by NamelessCoder** [comment]
It **should** be possible to do this if you set `plugin.tx_yourext.forms.{$formId}.enabled = 0`. The selector option gets removed here: https://github.com/FluidTYPO3/fluidpages/blob/development/Classes/Backend/PageLayoutSelector.php#L183 - and the property of the Form instance gets modified here: https://github.com/FluidTYPO3/flux/blob/development/Classes/Form/AbstractFormComponent.php#L444 (via `setEnabled` method that casts to boolean). All this is triggered when calling `getForm` on the exposed template view, which is how all Providers would access the Form instance: https://github.com/FluidTYPO3/flux/blob/development/Classes/View/ExposedTemplateView.php#L66

So putting all those puzzle pieces together I would assume that if you target the extension signature correctly in TS and use the proper scope (note: not `.view` but `.forms` because these are very different things!) and did so in a way that the TS is indeed applied on the page branch you are editing, then this should currently be working.

Using the global toggle to completely disable views is not advisable. It will also affect the entire frontend scope of all plugins etc. in your extension.
