### ISSUE TITLE
[ BE ] Templavoila and Flux: not a valid template resource URI

### ISSUE THREAD

**Issue by julianxhokaxhiu** [FluidTYPO3/flux#842]
Hi guys,

first of all let me thank you for all the great work your doing over this extension that makes the Development over Typo3 really fast.

With this issue I would like to report a problem but also a solution to this, that I've found when you have the latest version of Flux ( 7.2.1 ) and of Templavoila ( 1.9.7 ) on Typo3 6.2.10 ( but I think this happens also on 6.2.12 ).

What happens is that if you're using templavoila (maybe because you're coming from old installations) but you want to write so small parts using Fluid Templates with Flux View Helpers, the BE fails to load pages if you click on any URL inside the BE editing page (for example the link to "show/hide hidden elements").

When you try to do something like that you'll get this error:
```
'' is not a valid template resource URI.
```

The only way I found to fix this was by writing a one-line patch on the [AbstractProvider.php](https://github.com/FluidTYPO3/flux/blob/development/Classes/Provider/AbstractProvider.php#L211) after line 211:

```
if ( array_key_exists( 'tx_templavoila_flex', $row ) )
      return FALSE;
```

before the return.

I know it's quite ugly but actually it works. Maybe you can make it nicer, but this is my proposal for people that are maybe looking at this error and since there's nothing on the internet talking about this, I would like to provide some kind of documentation.

But it would be awesome if you can provide an OOB solution to this (maybe typoscript configuration? or a hook?).

Thanks in advance :)

**Comment by NamelessCoder** [comment]
Please check/follow/subscribe to https://github.com/FluidTYPO3/flux/issues/830 (same issue exists with custom extensions using flexforms in general) - the suggested solution should work if you're in a hurry and we expect the patch in the next Flux release.

I'll close this issue since it is a duplicate. People searching for this specific problem in connection with TV can then find the suggested solution and patch status in the link above.

Thanks for your kind words too ;)
