### ISSUE TITLE
Fal translation not working

### ISSUE THREAD

**Issue by metrgonzoo** [FluidTYPO3/flux#852]
Hi everyone,

I'm using Typo3 V6.2.14, flux 7.2.1, fluidcontent 4.2.4 and fluid 6.2.0.

In page mode, I create FCE in my default language with FAL image field (flux:field.inline.fal)

![fal](https://cloud.githubusercontent.com/assets/11647914/8703292/8c964fbe-2b1c-11e5-9b62-25797927c9df.png)

After translating my FCE in another language, the problem is that the FAL image is added into my default language FCE. And in my translated FCE the FAL image is missing.

![fal2](https://cloud.githubusercontent.com/assets/11647914/8703454/705b58f2-2b1d-11e5-99a1-235c73486441.png)

Any ideas?
Thx

**Comment by metrgonzoo** [comment]
Hi,

I found the problem. But I don't have the solution.
In the configuration of my FCE, I check the language ID. If the language ID isn't the default language, the FAL field is hidden.

<f:if condition="{record.sys_language_uid} == 0">	
	<o:image.responsive.responsiveImageField name="visual" allowed="jpg,png,gif" showThumbnails="TRUE" optional="TRUE" />
</f:if>

Someone have already this problem?

**Comment by NamelessCoder** [comment]
If you wish the FAL field to become translatable and behave correctly in this context, you can use the new option called `translation` on `flux:form`:

```xml
<flux:form options="{translation: 'mode'}" />
```

Where `mode` can be one of the values from this list: https://github.com/FluidTYPO3/flux/blob/development/Classes/Form.php#L35

Since Flux only generates TCEforms setup this is the only way you can affect translation. If neither of these options make this work, I'm afraid our only advise would be to submit a bug report to the TYPO3 issue tracker (but first look for an existing one, of course).

Hope this helps! And thanks, both for reporting and updating with a workaround - much appreciated!
