### ISSUE TITLE
Uninstalled Provider-Extension leads in "Oops, an error occurred!" Exception for left Content Elements linked with it.

### ISSUE THREAD

**Issue by typoworx-de** [FluidTYPO3/flux#895]
Using Provider-Extensions for Page/Content using FLUX will lead in "Oops, an error occurred!" Exceptions for linked Content-Elements left.

This occours in Frontend and Backend and will break the page!

This behaviour is not acceptable. It should not happend and only make a waring in Backend and/or for the Content-Element using the missing Provider-Key so that the Backend and Page-View will not get broken.

The error thrown does not indicate where the Problem comes from (Template could not be loaded. I tried "/Content/Index.html") which makes it hard sometimes to find the culprit / content-element that has to be disabled/removed.

Things like this should NEVER EVER happen in production environments or stable-releases!

**Comment by bjo3rnf** [comment]
> Things like this should NEVER EVER happen in production environments or stable-releases!

Just out of curiosity: why would you uninstall the provider extension in production environment in the first place?

**Comment by cedricziel** [comment]
By the way: We happily accept Pull Requests

**Comment by NamelessCoder** [comment]
Regarding the frontend: this error is absolute supposed to fall through; uninstalling your provider extension without also removing the plugin instances *should* generate an error - it corresponds to uninstalling a plugin without removing its plugin instances. You can try this with for example EXT:news - inserting a plugin, then uninstalling EXT:news and loading that page in FE causes an exception. You can catch this exception and turn it into a nice error by using the production exception handler.

Regarding the backend: cannot confirm that the backend breaks. What does happen is that viewing the page module with the instance shows it as an unlabeled, preview-less "Fluid content". And editing this content element automatically resets the "Fluid content type" selector to an empty value; forcing you to select another element type (or just disable the element).

Tested with development branches on 7.5-dev with production exception handler enabled.

Conclusion: behavior is intentional and is in sync with regular plugin behavior. Not using production exception handler may yield errors in the backend - but that's *also* intented behavior (or you wouldn't be able to debug your site).
