### ISSUE TITLE
flux:wizard.link doesn't save selected values

### ISSUE THREAD

**Issue by K3CK** [FluidTYPO3/flux#901]
TYPO3 7.4 and Flux latest development version.

When using `<flux:wizard.link label="Link" activeTab="page"/>` the chosen value from the popup gets inserted to the input field, but when saving the content element, the old value does not change / the new value does not get saved.

Configuration:
```
<flux:form id="linkButton" options="{group: 'FCE'}">
    <flux:field.input name="buttonText" label="Button text" />
    <flux:field.input name="buttonLink" label="Link target">
        <flux:wizard.link activeTab="page" />
    </flux:field.input>
</flux:form>
```
Strange thing is: When inserting a value to the input field by typing, the value gets saved.

**Comment by Marc-Bauer** [comment]
The Problem is that the value is not set into the hidden field. I think it is a JS Problem...

**Comment by xf-** [comment]
Looks related to this wizard problem
https://github.com/FluidTYPO3/flux/issues/908

**Comment by NamelessCoder** [comment]
See https://github.com/FluidTYPO3/flux/issues/908 - unfortunately there's not much we can do except suggest possible workarounds and recommend reporting this as a core bug (related to the JS and likely connected to the referencing of HTML elements with unsanitised name/id attributes). In your case Martin I'm sorry to say I can't even recommend a workaround because your fields already are named exactly like the workaround would suggest.

![javascript-535](https://cloud.githubusercontent.com/assets/2228052/9815218/ad52eeec-5894-11e5-8f2d-032577669783.jpg)
