### ISSUE TITLE
Localize flux:field.inline.fal

### ISSUE THREAD

**Issue by mkoehler2911** [FluidTYPO3/flux#906]
I added these attributes to my fal image:

- showPossibleLocalizationRecords="1"
- showAllLocalizationLink="1"

I exchanged the image in my default language and switched into my foreign language. 
I see the button and the new image from my default language grayed below the foreign language image. If I press on the localization button nothing happens.

What did I do wrong?

`<f:section name="Configuration">
    <flux:form id="image">
        <flux:field.inline.fal name="file" showPossibleLocalizationRecords="1" showAllLocalizationLink="1" maxItems="1" />
    </flux:form>
</f:section>`

Thanks!

Edit:
TYPO3 6.2.14 
Flux 7.2.1

**Comment by mkoehler2911** [comment]
My Second question about that:
I added the localizationMode="'keep'" attribute to my FAL 'cause I want the foreign image having the source from my default language image - won't work - I could still select my foreign language image and it won't get the source of my default language image.

What's wrong?
Thanks!

**Comment by NamelessCoder** [comment]
I hate to sound dismissive but... "if it works, it works. If it doesn't, blame the TYPO3 core". The reason is that Flux only creates TCEforms arrays and as such can only support whichever modes of translation support are supported by the native "flex" field type which consumes this TCEforms array. And on this TCEforms array we are allowed just a few settings to even activate translation support; see `options.translation` for Flux form (there's a fairly recent commit dealing specifically with this).

You can fiddle with these settings but may not get the result you want. If you don't, or if your FAL relations don't translate at all, either go to the TYPO3 core bug tracker (if it's backend) or see our issue tracker if it is frontend and you use for example VHS ViewHelpers to output. There are current issues with translating FAL records in the frontend but if the backend fails *after you set the translation modes* then that's not related to FluidTYPO3.
