### ISSUE TITLE
Select Wizard buggy

### ISSUE THREAD

**Issue by mithri** [FluidTYPO3/flux#908]
Hi,

i have the following code:

            <flux:field.input name="background-color" default="#ffffff">

                <flux:wizard.select label="Farbvorlagen" mode="'substitution'" items="{
                    0:{0:'Grau',1:'#49494a'},
                    1:{0:'BTA',1:'#0057a3'},
                    2:{0:'Gemeinde',1:'#771c80'},
                    3:{0:'Jugend',1:'#be0550'},
                    4:{0:'Kids',1:'#e2001a'},
                    5:{0:'Mission',1:'#f49e00'},
                    5:{0:'Standard',1:'#ffffff'}
                }"/>
            </flux:field.input>

If i change the value (with wizard or not) in the input field and save the CE, the old values stays. If i remove the wizard from the input field, the changes are saved to the database. I think in 7.3 and a older flux version this did work.

TYPO3 7.4.0
flux: branch development

**Comment by janviehweger** [comment]
Didn't test it but i think it must be mode="substitution".  The examples values in the docs are sometimes not that clear.

**Comment by mithri** [comment]
Not working either.

**Comment by xf-** [comment]
Confirmed - please note, it is likely this is related to a core change

**Comment by NamelessCoder** [comment]
This would be a core issue - and it may be related to the name used for the field itself. Neither `.` nor `-` play well when used as dynamic parts of Javascript calls which is definitely happening when using the wizards that manipulate the field value. If the name can be sanitised I would suggest that as a patch for the TYPO3 core. If they can't, I would maybe suggest error messaging when in Development context. If neither are possible then my only option is to suggest avoiding any sort of special characters in any field name and sheet name as well as the form ID itself.

Just to clarify: Flux doesn't render any HTML or JS for these fields. All it does is provide an array representation of a structure that can also be expressed as FlexForm XML (the "FlexForm data source"). If something doesn't work but options are passed correctly (they are, this has been checked multiple times and was working before) then it certainly is the fault of the TYPO3 core or the input values; e.g. the names of fields and things like whether or not the wizard options fit the field it is associated with.

I know this feels a little unresolved but there's not much we can do about this. We can't even throw a meaningful error about it because technically, it isn't an error and the fields work flawlessly - the JS just cannot handle referencing them in these particular cases.

**Comment by mithri** [comment]
No problem at all. Thank you for the clarification!

**Comment by NamelessCoder** [comment]
You're very welcome, @mithri!
