### ISSUE TITLE
FAL field - modifiy TCA

### ISSUE THREAD

**Issue by mithri** [FluidTYPO3/flux#909]
Hi,

is it possible to set ['appearance']['fileUploadAllowed'] = FALSE on the flux:field.inline.fal field?

I want to disalbe the select & upload button.

Thanks
tobias

**Comment by xf-** [comment]
hi

should do the trick. Isn't possible as flux attribute - Pull Requests are welcome
```php
$GLOBALS['TCA']['sys_file_reference']['columns']['uid_local']['config']['appearance']['fileUploadAllowed'] = FALSE;
```

**Comment by fnagel** [comment]
Is there any way to do this for flux fields only? I want to modify image crop variants for a flux inline fal field.

**Comment by NamelessCoder** [comment]
> Is there any way to do this for flux fields only? I want to modify image crop variants for a flux inline fal field.

There is not, sorry - but I'd merge a feature request that adds the `appearance` argument as array for fields that support it, in a heartbeat ;)

**Comment by fnagel** [comment]
Thanks for the response :-D

Not sure if the `appearance` field would help, as I would need to change `overrideChildTca` in order to change the `imageoverlayPalette` (for disabling link and description field) and the `sys_file_reference` `crop` field (or better its cropVariants config). 

https://docs.typo3.org/typo3cms/TCAReference/ColumnsConfig/Type/Inline.html#file-abstraction-layer

The general approach would work too: add an argument for passing `overrideChildTca` as an array.
