### ISSUE TITLE
Dash in name-attribut of FAL-viewhelper is not working.

### ISSUE THREAD

**Issue by rotespferd** [FluidTYPO3/flux#912]
I added the flux:field.inline.fal viewhelper in a "Configuration"-section of an fluidcontent contentelement. The code was the following:
```html
<flux:field.inline.fal name="slide-1_img" label="Image" allowedExtensions="png,jpeg,jpg" />
```
When I now want to use the created contentelement in the TYPO3-Backend and add a new image through the created field, nothing happend. The choosen image was not added to the contentelement.

When I now remove the dash from the name "slide-1_img", everything works fine. So its seems that the dash in the name is the problem.

I use Flux v7.2.1 and TYPO3 v6.2.14.

**Comment by NamelessCoder** [comment]
Only lowerCamelCase names are allowed. It's not enforced with exceptions to be slightly graceful (not all contexts have this limitation!). In other words, it's by design and you have to avoid it (and should also avoid underscores).

We may one day begin to throw Exceptions (and maybe handle them somehow, too) when using invalid field names. But for the time being you have to be aware ;)
