### ISSUE TITLE
form.object with one nested object is not working when exceeding a certain object count of the 1st level object inside a page template  

### ISSUE THREAD

**Issue by boettner-it** [FluidTYPO3/flux#916]
I have a FluidTYPO3 page template with nested <flux:form.object/> not working when exceeding a certain object count on the 1st level object. Only the other flux fields get saved into tx_fed_page_flexform, the xml structure remains valid though. This is my template: https://gist.github.com/boettner-it/6f29fd2e5c9d66705f84

**Comment by NamelessCoder** [comment]
See https://github.com/FluidTYPO3/flux#known-issues

**Comment by boettner-it** [comment]
Unfortunately raising max_input_vars is no solution in my case. Raised it to 50.000, 500.000 to no avail. I even get no error messages at all, not in backend, not in the logs. display_errors in on.

**Comment by NamelessCoder** [comment]
Max input variables is just the most likely reason. There can be quite a few reasons why a big request payload might be truncated. Including but not limited to:

* Proxies, reverse and otherwise, rejecting large POST (varnish, cloudflare, nginx clusters, etc).
* Web server itself configured to reject large POST (after successfully passed by proxy, or received directly).
* PHP configured to reject large inputs (size, number of variables, number of files posted, etc)
* MySQL configured with a too low packet size (however, this would probably cause more severe issues)

Neither of these will by default cause an error as they silently reject invalid input regardless of `display_errors` (most are not even related to PHP). Depending on where this happens it may not be logged at all. And not all of those may be possible to affect on your host.

Testing for them can be quite hard, too. My best advise is to create a completely "naked" PHP script and begin posting large sets. Affect what you can via php.ini and find out what the limits are.

The best advise is absolutely to limit the size of your forms that you post. It is *always* safer to just stay below the defaults (and complain if a provider lowers these defaults to unreasonable levels without a way to configure that).

**Comment by boettner-it** [comment]
Thanks for assisting me Claus. To reduce form data madness I split the content into separate CEs for city and project data and do the aggregation via workspacesAwareRecordService in the PageController.

**Comment by NamelessCoder** [comment]
I have a trick to teach you - just a moment :)

**Comment by NamelessCoder** [comment]
Alright, the trick: Flux's Outlet and Pipes.

Basic background: Flux's Form supports attaching an "Outlet" which in turn contains X number of "Pipes" that can "conduct" (=verify, manipulate, whatever) the data. A "Pipe" can for example be "save $data as JSON", "call controller X when $data happens" etc.

Since https://github.com/FluidTYPO3/flux/commit/9bd48f3a75865ae1221978ed0edba6682970241b these Outlets and Pipes are now called whenever a database operation takes place, via the Provider.

Using the Outlet and Pipe concept seems the perfect choice for what you need. It would allow you access to all the right data and instances for causing cascading etc. - and performing any aggregation; warning up caches or whatever.

To use the Pipes you've got quite a lot of options:

1. You can use `<flux:pipe.controller ... />` inside your `flux:form` and have the corresponding controller do the work.
2. You can create a custom Pipe subclass and corresponding ViewHelper (Flux has base classes and interfaces for both). You don't need to create a custom Outlet - but you can do so. The default one simply "conducts" all Pipes you add.
3. You can overrule the Provider that handles the record in question, manipulating for example the `getForm` method so that any Form instance returned from the Provider always uses your Pipe. You can also add a secondary Provider based on the first, but override the `trigger` method so it only listens to your particular record type - and the `getForm` method to attach your Pipe(s).
4. You can even attach Pipes to a given Form instance via TypoScript - `plugin.tx_yourext.forms.$formId.outlet.pipes.0 { type: $className, ... }`.

So that should give you a wide range of options for doing X exactly at the right time for aggregating the data which at the time of this execution is already saved to DB and passed as data to your Pipe.

**Comment by boettner-it** [comment]
Thanks for the whole Flux ecosystem, I can´t imagine TYPO3 without it anymore. Even more impressive to see options getting even wider. 

I had a look at the code but can´t see the benefit for my use case at the moment. The initial problem was a backend form potentially getting too large due to nested flux.form.objects. As I understand it Outlets and Pipes won´t get me to shrink this form as they work during rendering in frontend, right?

**Comment by NamelessCoder** [comment]
> As I understand it Outlets and Pipes won´t get me to shrink this form as they work during rendering in frontend, right?

No, they work in the backend (where the DataHandler database commands trigger; they don't in FE). One or more Pipes could let you receive limited user input and expand, aggregate, version, multiply data or whatever, based on the limited input. You mentioned you created a record service implementation so I assumed you wanted to "do something when record is changed" and that's exactly what the Pipes are all about ;)

> Thanks for the whole Flux ecosystem, I can´t imagine TYPO3 without it anymore. Even more impressive to see options getting even wider.

Thanks, much appreciated! Don't forget that you can now use Fluid as standalone. And a budget request was sent in for Q1 2016 to decouple Flux as well, letting you use Fluid and Flux metadata anywhere.

**Comment by boettner-it** [comment]
> You mentioned you created a record service implementation so I assumed you wanted to "do something when record is changed" and that's exactly what the Pipes are all about ;)

Yes, the initial problem was that the backend form could grow too large with nested objects. So I split the forms to use one single content element per customer project.

I could imagine using Pipes for performance reasons when one of these "project" content elements changes to aggregate the whole stuff into one JSON (in my case) for rendering in frontend and not aggregate anytime during page rendering which is what I´m doing now but it performs well so no real need to change that now.

> Don't forget that you can now use Fluid as standalone.

Yes, I´m following your Blog and Twitter and will jump onto that train as soon as a project fits. One upcoming project is a offline mobile data collection app with automated online sync functionality I will probably build on TYPO3 Flow, Angular and Hoodie for syncing but that´s not finally decided yet. So Fluid would be already on board there for the backend stuff mainly.

**Comment by NamelessCoder** [comment]
> aggregate the whole stuff into one JSON

It's funny you should mention that. Very, very soon TYPO3 will have a special JSON-based variable provider that you can plug into your Views for an extremely performant solution. Not only that, such JSON would also be ideal to consume in JS - also as directly requested file.

And there's the Fluid HTTP server which you could call with a template source and URL to JSON variables file and receive a Fluid rendering in as low as 1ms. But that's another story altogether :)
