### ISSUE TITLE
Misleading documentation for the "clear" argument

### ISSUE THREAD

**Issue by derhansen** [FluidTYPO3/flux#951]
The documentation for the ```clear```argument of Field-Viewhelpers is as following:
<pre>If TRUE, a "clear value" checkbox is displayed next to the field which when checked.</pre>

I was'nt able to get the "clear value" checkbox to appear, regardless to what value I set the ```clear```argument. Anyway, I believe that the ```clear```argument works as expected (e.g. overriding inherited values), but just the documentation seems to be misleading/wrong at this point.

**Comment by NamelessCoder** [comment]
This could be because the type of field you attempt to use, doesn't support wizards (I'm only guessing). You can see the code responsible here: https://github.com/FluidTYPO3/flux/blob/development/Classes/Form/AbstractFormField.php#L210 - and it does indeed behave as documented, by adding a custom wizard when the property is set to TRUE.

Maybe you could give an example of the field you use?

**Comment by derhansen** [comment]
I'm using a checkbox, where it of course doesn't make sense to render another checkbox beside to clear that value. Sorry, seems that it was too late yesterday I opened the issue ;-)
