### ISSUE TITLE
Support min/max restriction for flux:form.section

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/flux#977]
It would be nice to be able to specify a minimum required and maximum allowed number of elements inside a `<flux:form.section>` tag.

Probably depends on https://forge.typo3.org/issues/21282

**Comment by NamelessCoder** [comment]
Currently not possible due to limitations of TCA/FormEngine.

**Comment by NamelessCoder** [comment]
Since this is likely to be quite a long time in the future and we like a clean issue list, we prefer closing this issue. I'm monitoring the forge issue and will implement this when the core gains such support, but I wouldn't be surprised if it doesn't get picked up for another year or so.

Closed, but not forgotten ;)

**Comment by Gitsko** [comment]
is that possible now ?

**Comment by cweiske** [comment]
@Gitsko look at the related typo3 forge feature request
